-- Classroom Phase 1: owner-priced CBG + CBC room packages.
create table if not exists public.cb_classroom_settings(
 id boolean primary key default true check(id),cbc_gold_price integer not null default 0 check(cbc_gold_price>=0),
 pawn_cbg integer not null default 0,pawn_cbc integer not null default 0,bishop_cbg integer not null default 0,bishop_cbc integer not null default 0,
 knight_cbg integer not null default 0,knight_cbc integer not null default 0,rook_cbg integer not null default 0,rook_cbc integer not null default 0,
 queen_cbg integer not null default 0,queen_cbc integer not null default 0,king_cbg integer not null default 0,king_cbc integer not null default 0,
 updated_at timestamptz not null default now(),check(pawn_cbg>=0 and pawn_cbc>=0 and bishop_cbg>=0 and bishop_cbc>=0 and knight_cbg>=0 and knight_cbc>=0 and rook_cbg>=0 and rook_cbc>=0 and queen_cbg>=0 and queen_cbc>=0 and king_cbg>=0 and king_cbc>=0));
insert into public.cb_classroom_settings(id) values(true) on conflict(id) do nothing;
create table if not exists public.cb_classroom_wallets(user_id uuid primary key references auth.users(id) on delete cascade,cbc bigint not null default 0 check(cbc>=0),updated_at timestamptz not null default now());
create table if not exists public.cb_classroom_credit_ledger(id text primary key,user_id uuid not null references auth.users(id) on delete cascade,delta bigint not null,kind text not null,reference_id uuid,created_at timestamptz not null default now());
create table if not exists public.cb_classroom_rooms(id uuid primary key default gen_random_uuid(),teacher_id uuid not null references auth.users(id) on delete cascade,package_kind text not null check(package_kind in('pawn','bishop','knight','rook','queen','king')),name text not null check(char_length(name) between 2 and 60),invite_code text not null unique check(invite_code~'^[A-Z0-9]{8}$'),max_students integer not null check(max_students between 1 and 40),cbg_paid integer not null,cbc_included integer not null check(cbc_included>=0),status text not null default 'active' check(status in('active','closed')),created_at timestamptz not null default now(),expires_at timestamptz not null);
create table if not exists public.cb_classroom_enrollments(room_id uuid not null references public.cb_classroom_rooms(id) on delete cascade,student_id uuid not null references auth.users(id) on delete cascade,joined_at timestamptz not null default now(),primary key(room_id,student_id));
create index if not exists cb_classroom_rooms_active_idx on public.cb_classroom_rooms(status,expires_at);create index if not exists cb_classroom_enrollments_student_idx on public.cb_classroom_enrollments(student_id,joined_at desc);
alter table public.cb_classroom_settings enable row level security;alter table public.cb_classroom_wallets enable row level security;alter table public.cb_classroom_credit_ledger enable row level security;alter table public.cb_classroom_rooms enable row level security;alter table public.cb_classroom_enrollments enable row level security;
revoke all on public.cb_classroom_settings,public.cb_classroom_wallets,public.cb_classroom_credit_ledger,public.cb_classroom_rooms,public.cb_classroom_enrollments from anon,authenticated;

create or replace function public.cb_buy_cbc(p_user_id uuid,p_quantity integer,p_request_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare unit_price integer;total integer;gold integer;balance bigint;ledger_id text:='cbc-buy:'||p_request_id::text;
begin if p_quantity<1 or p_quantity>1000 then raise exception 'CBC quantity must be 1 to 1000';end if;select cbc_gold_price into unit_price from public.cb_classroom_settings where id=true;if coalesce(unit_price,0)<1 then raise exception 'CBC sales are not priced by the owner yet';end if;total:=unit_price*p_quantity;
insert into public.cb_classroom_wallets(user_id)values(p_user_id)on conflict(user_id)do nothing;if exists(select 1 from public.cb_classroom_credit_ledger where id=ledger_id)then select cbc into balance from public.cb_classroom_wallets where user_id=p_user_id;select gold_points into gold from public.cb_profiles where user_id=p_user_id;return jsonb_build_object('cbc',balance,'gold',gold);end if;
select gold_points into gold from public.cb_profiles where user_id=p_user_id for update;if gold<total then raise exception 'Not enough CBG';end if;update public.cb_profiles set gold_points=gold_points-total where user_id=p_user_id returning gold_points into gold;update public.cb_classroom_wallets set cbc=cbc+p_quantity,updated_at=now()where user_id=p_user_id returning cbc into balance;
insert into public.cb_gold_ledger(id,user_id,delta,kind,reference_id)values(ledger_id,p_user_id,-total,'cbc_purchase',p_request_id);insert into public.cb_classroom_credit_ledger(id,user_id,delta,kind,reference_id)values(ledger_id,p_user_id,p_quantity,'purchase',p_request_id);return jsonb_build_object('cbc',balance,'gold',gold);end $$;

create or replace function public.cb_create_classroom(p_user_id uuid,p_package text,p_name text,p_request_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$
declare cbg_cost integer;cbc_bundle integer;slots integer;lifetime interval;gold integer;r public.cb_classroom_rooms%rowtype;code text;ledger_id text:='classroom-room:'||p_request_id::text;
begin select case lower(p_package)when'pawn'then pawn_cbg when'bishop'then bishop_cbg when'knight'then knight_cbg when'rook'then rook_cbg when'queen'then queen_cbg when'king'then king_cbg end,case lower(p_package)when'pawn'then pawn_cbc when'bishop'then bishop_cbc when'knight'then knight_cbc when'rook'then rook_cbc when'queen'then queen_cbc when'king'then king_cbc end into cbg_cost,cbc_bundle from public.cb_classroom_settings where id=true;
select x.slots,x.life into slots,lifetime from(values('pawn',5,interval'12 hours'),('bishop',10,interval'1 day'),('knight',15,interval'3 days'),('rook',20,interval'5 days'),('queen',30,interval'7 days'),('king',40,interval'14 days'))x(kind,slots,life)where x.kind=lower(p_package);
if slots is null then raise exception'Unknown classroom package';end if;if coalesce(cbg_cost,0)<1 or coalesce(cbc_bundle,0)<1 then raise exception'This room package is not fully configured by the owner yet';end if;if char_length(trim(p_name))not between 2 and 60 then raise exception'Room name must be 2 to 60 characters';end if;
select rooms.* into r from public.cb_gold_ledger l join public.cb_classroom_rooms rooms on rooms.id=l.reference_id where l.id=ledger_id;if found then return to_jsonb(r);end if;insert into public.cb_classroom_wallets(user_id)values(p_user_id)on conflict(user_id)do nothing;select gold_points into gold from public.cb_profiles where user_id=p_user_id for update;if gold<cbg_cost then raise exception'Not enough CBG';end if;
loop code:=upper(substr(md5(random()::text||clock_timestamp()::text),1,8));exit when not exists(select 1 from public.cb_classroom_rooms where invite_code=code);end loop;insert into public.cb_classroom_rooms(teacher_id,package_kind,name,invite_code,max_students,cbg_paid,cbc_included,expires_at)values(p_user_id,lower(p_package),trim(p_name),code,slots,cbg_cost,cbc_bundle,now()+lifetime)returning*into r;
update public.cb_profiles set gold_points=gold_points-cbg_cost where user_id=p_user_id;update public.cb_classroom_wallets set cbc=cbc+cbc_bundle,updated_at=now()where user_id=p_user_id;insert into public.cb_gold_ledger(id,user_id,delta,kind,reference_id)values(ledger_id,p_user_id,-cbg_cost,'classroom_room',r.id);insert into public.cb_classroom_credit_ledger(id,user_id,delta,kind,reference_id)values(ledger_id,p_user_id,cbc_bundle,'room_bundle',r.id);return to_jsonb(r);end $$;

create or replace function public.cb_join_classroom(p_user_id uuid,p_code text,p_request_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.cb_classroom_rooms%rowtype;student_count integer;balance bigint;begin select*into r from public.cb_classroom_rooms where invite_code=upper(trim(p_code))for update;if not found or r.status<>'active'or r.expires_at<=now()then raise exception'This classroom code is invalid or expired';end if;if r.teacher_id=p_user_id then raise exception'Teachers cannot join their own room';end if;if exists(select 1 from public.cb_classroom_enrollments where room_id=r.id and student_id=p_user_id)then return to_jsonb(r);end if;select count(*)into student_count from public.cb_classroom_enrollments where room_id=r.id;if student_count>=r.max_students then raise exception'This classroom is full';end if;insert into public.cb_classroom_wallets(user_id)values(p_user_id)on conflict(user_id)do nothing;select cbc into balance from public.cb_classroom_wallets where user_id=p_user_id for update;if balance<1 then raise exception'You need 1 CBC in My Bag to enter this classroom';end if;insert into public.cb_classroom_enrollments(room_id,student_id)values(r.id,p_user_id);update public.cb_classroom_wallets set cbc=cbc-1,updated_at=now()where user_id=p_user_id;insert into public.cb_classroom_credit_ledger(id,user_id,delta,kind,reference_id)values('classroom-join:'||p_request_id::text,p_user_id,-1,'join_room',r.id)on conflict(id)do nothing;return to_jsonb(r);end $$;
create or replace function public.cb_rename_classroom(p_user_id uuid,p_room_id uuid,p_name text)returns void language plpgsql security definer set search_path=public as $$begin if char_length(trim(p_name))not between 2 and 60 then raise exception'Room name must be 2 to 60 characters';end if;update public.cb_classroom_rooms set name=trim(p_name)where id=p_room_id and teacher_id=p_user_id and status='active'and expires_at>now();if not found then raise exception'Active classroom not found';end if;end $$;
create or replace function public.cb_gift_cbc(p_sender_id uuid,p_username text,p_quantity integer,p_request_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare recipient uuid;sender_balance bigint;recipient_balance bigint;sender_gold integer;ledger_id text:='cbc-gift:'||p_request_id::text;begin if p_quantity<1 or p_quantity>1000 then raise exception'CBC quantity must be 1 to 1000';end if;select user_id into recipient from public.cb_profiles where lower(username)=lower(trim(leading'@'from p_username));if recipient is null or recipient=p_sender_id then raise exception'Choose another valid student username';end if;insert into public.cb_classroom_wallets(user_id)values(p_sender_id),(recipient)on conflict(user_id)do nothing;if exists(select 1 from public.cb_classroom_credit_ledger where id=ledger_id||':out')then select cbc into sender_balance from public.cb_classroom_wallets where user_id=p_sender_id;return jsonb_build_object('cbc',sender_balance);end if;select cbc into sender_balance from public.cb_classroom_wallets where user_id=p_sender_id for update;select gold_points into sender_gold from public.cb_profiles where user_id=p_sender_id for update;if sender_balance<p_quantity then raise exception'Not enough CBC';end if;if sender_gold<4 then raise exception'You need 4 CBG for the gift transaction';end if;update public.cb_classroom_wallets set cbc=cbc-p_quantity,updated_at=now()where user_id=p_sender_id;update public.cb_classroom_wallets set cbc=cbc+p_quantity,updated_at=now()where user_id=recipient returning cbc into recipient_balance;update public.cb_profiles set gold_points=gold_points-4 where user_id=p_sender_id;insert into public.cb_classroom_credit_ledger(id,user_id,delta,kind,reference_id)values(ledger_id||':out',p_sender_id,-p_quantity,'gift',p_request_id),(ledger_id||':in',recipient,p_quantity,'gift',p_request_id);insert into public.cb_gold_ledger(id,user_id,delta,kind,reference_id)values(ledger_id,p_sender_id,-4,'cbc_gift_fee',p_request_id);return jsonb_build_object('cbc',sender_balance-p_quantity,'recipient_cbc',recipient_balance);end $$;
revoke all on function public.cb_buy_cbc(uuid,integer,uuid),public.cb_create_classroom(uuid,text,text,uuid),public.cb_join_classroom(uuid,text,uuid),public.cb_rename_classroom(uuid,uuid,text),public.cb_gift_cbc(uuid,text,integer,uuid)from public,anon,authenticated;grant execute on function public.cb_buy_cbc(uuid,integer,uuid),public.cb_create_classroom(uuid,text,text,uuid),public.cb_join_classroom(uuid,text,uuid),public.cb_rename_classroom(uuid,uuid,text),public.cb_gift_cbc(uuid,text,integer,uuid)to service_role;
