-- Unified read-only rankings. Uses existing game results; changes no rewards or ratings.
-- Apply after the existing Puzzle, CPU, Chess Math, and Grand Arena migrations.
begin;
create or replace function public.cb_game_rankings(p_board text,p_page integer default 1,p_user_id uuid default null,p_session_id uuid default null)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare source_sql text;result jsonb;
begin
 if p_page is null or p_page not between 1 and 100000 then raise exception 'Choose a valid rankings page.';end if;
 case p_board
 when 'cbr' then source_sql:=$source$select user_id,cbr::numeric value,cbr::numeric sort_value,wins::numeric secondary,wins::text||' wins' detail from public.cb_profiles$source$;
 when 'ocbr' then source_sql:=$source$select user_id,ocbr::numeric value,ocbr::numeric sort_value,0::numeric secondary,'Offline rating'::text detail from public.cb_profiles$source$;
 when 'puzzle_today' then source_sql:=$source$select c.user_id,count(*)::numeric value,count(*)::numeric sort_value,coalesce(max(p.puzzle_rating),1000)::numeric secondary,'Solved today'::text detail from public.cb_daily_puzzle_claims c left join public.cb_puzzle_profiles p using(user_id) where c.puzzle_day=((now()-interval '1 minute') at time zone 'Asia/Manila')::date group by c.user_id$source$;
 when 'puzzle_total' then source_sql:=$source$select user_id,solved_total::numeric value,solved_total::numeric sort_value,puzzle_rating::numeric secondary,puzzle_rating::text||' puzzle rating' detail from public.cb_puzzle_profiles where solved_total>0$source$;
 when 'puzzle_rating' then source_sql:=$source$select user_id,puzzle_rating::numeric value,puzzle_rating::numeric sort_value,solved_total::numeric secondary,solved_total::text||' solved' detail from public.cb_puzzle_profiles where solved_total>0$source$;
 when 'puzzle_streak' then source_sql:=$source$select user_id,best_streak::numeric value,best_streak::numeric sort_value,solved_total::numeric secondary,solved_total::text||' solved' detail from public.cb_puzzle_profiles where best_streak>0$source$;
 when 'cpu_today' then source_sql:=$source$select user_id,wins::numeric value,wins::numeric sort_value,cbr_gain::numeric secondary,cbr_gain::text||' CBR gained' detail from public.cb_cpu_player_stats where period_key='day' and period_start=(now() at time zone 'Asia/Manila')::date and mode_key='all' and wins>0$source$;
 when 'cpu_week' then source_sql:=$source$select user_id,wins::numeric value,wins::numeric sort_value,cbr_gain::numeric secondary,cbr_gain::text||' CBR gained' detail from public.cb_cpu_player_stats where period_key='week' and period_start=date_trunc('week',now() at time zone 'Asia/Manila')::date and mode_key='all' and wins>0$source$;
 when 'cpu_all' then source_sql:=$source$select user_id,wins::numeric value,wins::numeric sort_value,cbr_gain::numeric secondary,cbr_gain::text||' CBR gained' detail from public.cb_cpu_player_stats where period_key='all_time' and period_start='2000-01-01'::date and mode_key='all' and wins>0$source$;
 when 'cpu_rapid' then source_sql:=$source$select user_id,wins::numeric value,wins::numeric sort_value,cbr_gain::numeric secondary,cbr_gain::text||' CBR gained' detail from public.cb_cpu_player_stats where period_key='all_time' and period_start='2000-01-01'::date and mode_key='Rapid' and wins>0$source$;
 when 'cpu_blitz' then source_sql:=$source$select user_id,wins::numeric value,wins::numeric sort_value,cbr_gain::numeric secondary,cbr_gain::text||' CBR gained' detail from public.cb_cpu_player_stats where period_key='all_time' and period_start='2000-01-01'::date and mode_key='Blitz' and wins>0$source$;
 when 'cpu_bullet' then source_sql:=$source$select user_id,wins::numeric value,wins::numeric sort_value,cbr_gain::numeric secondary,cbr_gain::text||' CBR gained' detail from public.cb_cpu_player_stats where period_key='all_time' and period_start='2000-01-01'::date and mode_key='Bullet' and wins>0$source$;
 when 'arena_all' then source_sql:=$source$select e.user_id,sum(e.arena_points)::numeric value,sum(e.arena_points)::numeric sort_value,sum(e.wins)::numeric secondary,sum(e.wins)::text||' wins · '||sum(e.arena_cbr_gain)::text||' CBR gained' detail from public.cb_arena_entries e join public.cb_arena_sessions s on s.id=e.session_id where e.status<>'registered' and true group by e.user_id$source$;
 when 'arena_today' then source_sql:=$source$select e.user_id,sum(e.arena_points)::numeric value,sum(e.arena_points)::numeric sort_value,sum(e.wins)::numeric secondary,sum(e.wins)::text||' wins · '||sum(e.arena_cbr_gain)::text||' CBR gained' detail from public.cb_arena_entries e join public.cb_arena_sessions s on s.id=e.session_id where e.status<>'registered' and s.session_date=(now() at time zone 'Asia/Manila')::date group by e.user_id$source$;
 when 'arena_week' then source_sql:=$source$select e.user_id,sum(e.arena_points)::numeric value,sum(e.arena_points)::numeric sort_value,sum(e.wins)::numeric secondary,sum(e.wins)::text||' wins · '||sum(e.arena_cbr_gain)::text||' CBR gained' detail from public.cb_arena_entries e join public.cb_arena_sessions s on s.id=e.session_id where e.status<>'registered' and s.session_date>=date_trunc('week',now() at time zone 'Asia/Manila')::date and s.session_date<date_trunc('week',now() at time zone 'Asia/Manila')::date+7 group by e.user_id$source$;
 when 'arena_session' then source_sql:=$source$select e.user_id,sum(e.arena_points)::numeric value,sum(e.arena_points)::numeric sort_value,sum(e.wins)::numeric secondary,sum(e.wins)::text||' wins · '||sum(e.arena_cbr_gain)::text||' CBR gained' detail from public.cb_arena_entries e join public.cb_arena_sessions s on s.id=e.session_id where e.status<>'registered' and s.id=coalesce($1,(select id from public.cb_arena_sessions where owner_scheduled and starts_at<=now() order by starts_at desc limit 1)) group by e.user_id$source$;
 when 'arena_champions' then source_sql:=$source$select champion_id user_id,count(*)::numeric value,count(*)::numeric sort_value,0::numeric secondary,'Session championships'::text detail from public.cb_arena_sessions where champion_id is not null and champion_rewarded_at is not null group by champion_id$source$;
 when 'math_easy_score' then source_sql:=$source$select user_id,score::numeric value,score::numeric sort_value,-elapsed_ms::numeric secondary,cardinality(question_ids)::text||' questions · '||round(elapsed_ms::numeric/1000,1)::text||' seconds' detail from (select distinct on(user_id) * from public.cb_chess_math_sessions where difficulty='easy' and finished_at is not null order by user_id,score desc,elapsed_ms,id) b$source$;
 when 'math_easy_speed' then source_sql:=$source$select user_id,ms_per_correct value,-ms_per_correct sort_value,-elapsed_ms::numeric secondary,score::text||' correct · 70% accuracy minimum' detail from (select distinct on(user_id) *,round(elapsed_ms::numeric/greatest(score,1)) ms_per_correct from public.cb_chess_math_sessions where difficulty='easy' and finished_at is not null and answered_count=cardinality(question_ids) and score>=ceil(cardinality(question_ids)*0.7) order by user_id,round(elapsed_ms::numeric/greatest(score,1)),elapsed_ms,id) b$source$;
 when 'math_easy_finishers' then source_sql:=$source$select user_id,count(*)::numeric value,count(*)::numeric sort_value,0::numeric secondary,'Fully answered quizzes'::text detail from public.cb_chess_math_sessions where difficulty='easy' and finished_at is not null and answered_count=cardinality(question_ids) group by user_id$source$;
 when 'math_medium_score' then source_sql:=$source$select user_id,score::numeric value,score::numeric sort_value,-elapsed_ms::numeric secondary,cardinality(question_ids)::text||' questions · '||round(elapsed_ms::numeric/1000,1)::text||' seconds' detail from (select distinct on(user_id) * from public.cb_chess_math_sessions where difficulty='medium' and finished_at is not null order by user_id,score desc,elapsed_ms,id) b$source$;
 when 'math_medium_speed' then source_sql:=$source$select user_id,ms_per_correct value,-ms_per_correct sort_value,-elapsed_ms::numeric secondary,score::text||' correct · 70% accuracy minimum' detail from (select distinct on(user_id) *,round(elapsed_ms::numeric/greatest(score,1)) ms_per_correct from public.cb_chess_math_sessions where difficulty='medium' and finished_at is not null and answered_count=cardinality(question_ids) and score>=ceil(cardinality(question_ids)*0.7) order by user_id,round(elapsed_ms::numeric/greatest(score,1)),elapsed_ms,id) b$source$;
 when 'math_medium_finishers' then source_sql:=$source$select user_id,count(*)::numeric value,count(*)::numeric sort_value,0::numeric secondary,'Fully answered quizzes'::text detail from public.cb_chess_math_sessions where difficulty='medium' and finished_at is not null and answered_count=cardinality(question_ids) group by user_id$source$;
 when 'math_hard_score' then source_sql:=$source$select user_id,score::numeric value,score::numeric sort_value,-elapsed_ms::numeric secondary,cardinality(question_ids)::text||' questions · '||round(elapsed_ms::numeric/1000,1)::text||' seconds' detail from (select distinct on(user_id) * from public.cb_chess_math_sessions where difficulty='hard' and finished_at is not null order by user_id,score desc,elapsed_ms,id) b$source$;
 when 'math_hard_speed' then source_sql:=$source$select user_id,ms_per_correct value,-ms_per_correct sort_value,-elapsed_ms::numeric secondary,score::text||' correct · 70% accuracy minimum' detail from (select distinct on(user_id) *,round(elapsed_ms::numeric/greatest(score,1)) ms_per_correct from public.cb_chess_math_sessions where difficulty='hard' and finished_at is not null and answered_count=cardinality(question_ids) and score>=ceil(cardinality(question_ids)*0.7) order by user_id,round(elapsed_ms::numeric/greatest(score,1)),elapsed_ms,id) b$source$;
 when 'math_hard_finishers' then source_sql:=$source$select user_id,count(*)::numeric value,count(*)::numeric sort_value,0::numeric secondary,'Fully answered quizzes'::text detail from public.cb_chess_math_sessions where difficulty='hard' and finished_at is not null and answered_count=cardinality(question_ids) group by user_id$source$;
 when 'attack_score' then source_sql:=$source$select user_id,correct::numeric value,correct::numeric sort_value,-elapsed_ms::numeric secondary,round(elapsed_ms::numeric/1000,1)::text||' seconds' detail from (select distinct on(user_id) * from public.cb_chess_math_attack where finished_at is not null order by user_id,correct desc,elapsed_ms,id) b$source$;
 when 'attack_pace' then source_sql:=$source$select user_id,pace value,pace sort_value,correct::numeric secondary,correct::text||' correct · minimum 10' detail from (select distinct on(user_id) *,round(correct::numeric*60000/greatest(elapsed_ms,1),2) pace from public.cb_chess_math_attack where finished_at is not null and correct>=10 order by user_id,round(correct::numeric*60000/greatest(elapsed_ms,1),2) desc,correct desc,elapsed_ms,id) b$source$;
 when 'attack_total' then source_sql:=$source$select user_id,sum(correct)::numeric value,sum(correct)::numeric sort_value,count(*)::numeric secondary,count(*)::text||' completed attempts' detail from public.cb_chess_math_attack where finished_at is not null group by user_id$source$;
 else raise exception 'Choose a valid game leaderboard.';
 end case;
 execute 'with scores as ('||source_sql||'), ranked as (
 select row_number() over(order by s.sort_value desc,s.secondary desc,s.user_id) as rank,
 s.user_id,p.username,p.display_name,p.avatar_url,s.value,s.detail
 from scores s join public.cb_profiles p using(user_id)
 ), totals as (select count(*)::integer total from ranked), paging as (
 select total,greatest(1,ceil(total::numeric/10)::integer) pages,
 least($3,greatest(1,ceil(total::numeric/10)::integer)) page from totals
 ) select jsonb_build_object(''total'',total,''pages'',pages,''page'',page,''page_size'',10,
 ''rows'',coalesce((select jsonb_agg(to_jsonb(r) order by rank) from ranked r where rank>(page-1)*10 and rank<=page*10),''[]''::jsonb),
 ''mine'',(select to_jsonb(r) from ranked r where user_id=$2)) from paging'
 into result using p_session_id,p_user_id,p_page;
 return result;
end $$;
revoke all on function public.cb_game_rankings(text,integer,uuid,uuid) from public,anon,authenticated;
grant execute on function public.cb_game_rankings(text,integer,uuid,uuid) to service_role;
commit;
