import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {PGlite} from '@electric-sql/pglite';
const recurrence=readFileSync(new URL('../api/_arena-recurrence.ts',import.meta.url),'utf8');
const m={exports:{}};new Function('module','exports',ts.transpileModule(recurrence,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(m,m.exports);
const {arenaOccurrences}=m.exports;
const owner='00000000-0000-0000-0000-000000000001',player='00000000-0000-0000-0000-000000000002';
const baseline=readFileSync(new URL('../supabase/0101_arena_owner_created_battles.sql',import.meta.url),'utf8');
const sql=readFileSync(new URL('../supabase/0103_arena_repeat_schedules.sql',import.meta.url),'utf8');
async function fixture(limit=12){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;
create table cb_profiles(user_id uuid,role text);insert into cb_profiles values('${owner}','owner'),('${player}','player');
create table cb_arena_settings(id boolean primary key,losses_to_eliminate integer,upcoming_weekly_limit integer,prize_mode text,fixed_prize_gold integer,match_control text,updated_by uuid,updated_at timestamptz);
insert into cb_arena_settings values(true,3,${limit},'fixed',48,'5+0',null,now());
create table cb_arena_sessions(id uuid primary key default gen_random_uuid(),session_date date,slot integer,starts_at timestamptz,ends_at timestamptz,title text,loss_limit integer,owner_scheduled boolean,prize_mode text,prize_gold integer,match_control text,unique(session_date,slot));`);
await db.exec(baseline.slice(baseline.indexOf('create or replace function public.cb_save_arena_controls')).replace(/commit;\s*$/,''));await db.exec(sql);return db;}
const create=(db,repeat='daily',count=7,user=owner)=>db.query("select cb_create_arena_series($1,'Evening battle','2030-12-30T23:00:00+08:00','2030-12-31T01:00:00+08:00',3,$2,$3)",[user,repeat,count]);
const sessions=async db=>(await db.query('select * from cb_arena_sessions order by starts_at')).rows;
test('preview keeps daily overnight hours and crosses year in Philippine time',()=>{const rows=arenaOccurrences('2030-12-30T23:00:00+08:00','2030-12-31T01:00:00+08:00','daily',7);assert.equal(rows.length,7);assert.equal(rows[6].starts_at,'2031-01-05T15:00:00.000Z');assert.equal(rows[6].ends_at,'2031-01-05T17:00:00.000Z');});
test('weekly preview stays on same weekday and invalid options/count/duration fail',()=>{const r=arenaOccurrences('2030-12-30T19:00:00+08:00','2030-12-30T21:00:00+08:00','weekly',4);assert.equal(Date.parse(r[3].starts_at)-Date.parse(r[0].starts_at),21*86400000);for(const [repeat,count] of [['daily',1],['weekly',29],['daily',2.5],['never',4]])assert.throws(()=>arenaOccurrences(r[0].starts_at,r[0].ends_at,repeat,count));assert.throws(()=>arenaOccurrences('bad','bad','daily',7));assert.throws(()=>arenaOccurrences(r[0].ends_at,r[0].starts_at,'daily',7));});
test('database publishes seven distinct daily sessions with same rewards and overnight duration',async()=>{const db=await fixture();try{await create(db);const rows=await sessions(db);assert.equal(rows.length,7);assert.equal(new Set(rows.map(r=>r.id)).size,7);for(const row of rows){assert.equal(row.loss_limit,3);assert.equal(row.prize_gold,48);assert.equal(row.match_control,'5+0');assert.equal(Date.parse(row.ends_at)-Date.parse(row.starts_at),7200000);}assert.equal(new Date(rows[6].session_date).toISOString().slice(0,10),'2031-01-05');}finally{await db.close();}});
test('weekly batch respects four-battle cap and spaces separate dates by seven days',async()=>{const db=await fixture(4);try{await create(db,'weekly',4);const rows=await sessions(db);assert.equal(rows.length,4);assert.equal(Date.parse(rows[3].starts_at)-Date.parse(rows[0].starts_at),21*86400000);}finally{await db.close();}});
test('weekly-limit conflict rolls back entire daily batch',async()=>{const db=await fixture(4);try{await assert.rejects(create(db),/weekly limit/);assert.equal((await sessions(db)).length,0);}finally{await db.close();}});
test('later overlap rolls back prior new dates and preserves existing session',async()=>{const db=await fixture();try{await db.query("select cb_save_arena_session($1,null,'Existing','2030-12-31T23:30:00+08:00','2031-01-01T01:30:00+08:00',5)",[owner]);await assert.rejects(create(db),/overlap/);const rows=await sessions(db);assert.equal(rows.length,1);assert.equal(rows[0].title,'Existing');assert.equal(rows[0].loss_limit,5);}finally{await db.close();}});
test('owner-only, bounded count, authenticated RPC blocked, migration rerunnable',async()=>{const db=await fixture();try{await db.exec(sql);await assert.rejects(create(db,'daily',7,player),/Owner access/);await assert.rejects(create(db,'daily',29),/2–28/);await assert.rejects(create(db,'none',7),/daily or weekly/);await db.exec('set role authenticated');await assert.rejects(create(db),/permission denied/);}finally{await db.close();}});
const apiSource=readFileSync(new URL('../api/grand-arena.ts',import.meta.url),'utf8');
const apiCode=ts.transpileModule(apiSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
async function apiCall({role='owner',repeat='daily',count=7,id=null,rpcError=null}={}){
 const calls=[];const profile={user_id:owner,role,agreement_version:1,avatar_url:`https://example.supabase.co/storage/v1/object/public/cb-profile-media/${owner}/avatar-photo.webp`};
 const client={auth:{getUser:async()=>({data:{user:{id:owner}},error:null})},from(table){const q={select(){return q;},eq(){return q;},gt(){return q;},order(){return q;},single:async()=>({data:profile,error:null}),maybeSingle:async()=>({data:{id:true,upcoming_weekly_limit:7},error:null}),then(resolve){return Promise.resolve({data:[],error:null}).then(resolve);}};return q;},rpc:async(name,args)=>{calls.push({name,args});return{data:{},error:rpcError};}};
 const api={exports:{}};new Function('require','module','exports',apiCode)(name=>name==='./_arena-recurrence.js'?m.exports:{createClient:()=>client},api,api.exports);
 const oldUrl=process.env.NEXT_PUBLIC_SUPABASE_URL,oldKey=process.env.SUPABASE_SERVICE_ROLE_KEY;process.env.NEXT_PUBLIC_SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='test';
 let status,payload;const res={setHeader(){},status(n){status=n;return res;},json(data){payload=data;}};
 try{await api.exports.default({method:'POST',headers:{authorization:'Bearer test'},body:{action:'save-owner-session',repeat,repeat_count:count,id,title:'Battle',starts_at:'2030-12-30T23:00:00+08:00',ends_at:'2030-12-31T01:00:00+08:00',loss_limit:3}},res);return{status,payload,calls};}finally{if(oldUrl===undefined)delete process.env.NEXT_PUBLIC_SUPABASE_URL;else process.env.NEXT_PUBLIC_SUPABASE_URL=oldUrl;if(oldKey===undefined)delete process.env.SUPABASE_SERVICE_ROLE_KEY;else process.env.SUPABASE_SERVICE_ROLE_KEY=oldKey;}
}
test('API authenticates owner and sends recurrence through one atomic RPC',async()=>{const r=await apiCall();assert.equal(r.status,200);assert.equal(r.calls.length,1);assert.equal(r.calls[0].name,'cb_create_arena_series');assert.equal(r.calls[0].args.p_owner_id,owner);assert.equal(r.calls[0].args.p_count,7);assert.equal(r.calls[0].args.p_repeat,'daily');});
test('API rejects nonowners, invalid repeat count, and repeating an existing paid session',async()=>{for(const [opts,status] of [[{role:'player'},403],[{count:29},400],[{repeat:'bad'},400],[{id:owner},400]]){const r=await apiCall(opts);assert.equal(r.status,status);assert.equal(r.calls.length,0);}});
test('one-off creation uses existing RPC and missing migration has clear setup error',async()=>{const single=await apiCall({repeat:'none'});assert.equal(single.status,200);assert.equal(single.calls[0].name,'cb_save_arena_session');const missing=await apiCall({rpcError:{code:'PGRST202',message:'missing'}});assert.equal(missing.status,503);assert.match(missing.payload.error,/0103_arena_repeat_schedules.sql/);});
