import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const sql=readFileSync(new URL('../supabase/0102_chess_open_play.sql',import.meta.url),'utf8');
const owner='00000000-0000-0000-0000-000000000001',a='00000000-0000-0000-0000-000000000002',b='00000000-0000-0000-0000-000000000003';
async function fixture(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;
create table cb_profiles(user_id uuid primary key,role text default 'player',cbr integer default 88,wins integer default 0);
create table cb_presence(user_id uuid primary key,latitude double precision,longitude double precision,accuracy double precision,gps_enabled boolean,seen_at timestamptz);
insert into cb_profiles(user_id,role) values('${owner}','owner'),('${a}','player'),('${b}','player');`);await db.exec(sql);return db;}
async function create(db,{capacity=null,bonus=20,lat=11.244,lng=125.003}={}){return (await db.query("select * from cb_save_open_play($1,null,$2,$3,'Automatic pin location',now()+interval '1 hour',now()+interval '3 hours',$4,$5)",[owner,lat,lng,bonus,capacity])).rows[0];}
const join=(db,id,user=a)=>db.query('select cb_join_open_play($1,$2,true)',[user,id]);
const row=async(db,q,args=[])=> (await db.query(q,args)).rows[0];
async function activate(db,id){await db.query("update cb_open_play_sessions set starts_at=now()-interval '1 hour' where id=$1",[id]);}
async function presence(db,{lat=11.244,lng=125.003,accuracy=3,gps=true,age=0}={}){await db.query("insert into cb_presence values($1,$2,$3,$4,$5,now()-($6||' seconds')::interval) on conflict(user_id) do update set latitude=excluded.latitude,longitude=excluded.longitude,accuracy=excluded.accuracy,gps_enabled=excluded.gps_enabled,seen_at=excluded.seen_at",[a,lat,lng,accuracy,gps,String(age)]);}
async function win(db){await db.query('update cb_profiles set cbr=cbr+8,wins=wins+1 where user_id=$1',[a]);}
test('owner may pin distant locations without a session limit; members cannot create',async()=>{const db=await fixture();try{for(let i=0;i<6;i++)await create(db,{lat:40+i,lng:-75});assert.equal((await row(db,'select count(*)::integer n from cb_open_play_sessions')).n,6);await assert.rejects(db.query("select cb_save_open_play($1,null,0,0,'GPS',now()+interval '1 hour',now()+interval '2 hours',20,null)",[a]),/Only an owner/);await assert.rejects(create(db,{bonus:101}),/valid pin/);}finally{await db.close();}});
test('capacity is enforced with locked session, duplicate registration is free, leaving frees a spot',async()=>{const db=await fixture();try{const s=await create(db,{capacity:1});await join(db,s.id);await join(db,s.id);await assert.rejects(join(db,s.id,b),/full/);assert.equal((await row(db,'select count(*)::integer n from cb_open_play_registrations')).n,1);await db.query('select cb_join_open_play($1,$2,false)',[a,s.id]);await join(db,s.id,b);assert.equal((await row(db,'select user_id from cb_open_play_registrations')).user_id,b);}finally{await db.close();}});
test('unlimited joiners; edit keeps registration and rejects cap reduction or moving registered pin',async()=>{const db=await fixture();try{const s=await create(db);await join(db,s.id);await join(db,s.id,b);const edit=(cap,lat=11.244)=>db.query("select cb_save_open_play($1,$2,$3,125.003,'Pin',now()+interval '2 hours',now()+interval '4 hours',30,$4)",[owner,s.id,lat,cap]);await assert.rejects(edit(1),/below/);await assert.rejects(edit(null,45),/cannot move/);await edit(2);assert.equal((await row(db,'select bonus_percent from cb_open_play_sessions')).bonus_percent,30);assert.equal((await row(db,'select count(*)::integer n from cb_open_play_registrations')).n,2);}finally{await db.close();}});
test('registered onsite wins receive rounded bonus atomically, while gains without a new win do not',async()=>{const db=await fixture();try{const s=await create(db);await join(db,s.id);await activate(db,s.id);await presence(db);await win(db);assert.equal((await row(db,'select cbr from cb_profiles where user_id=$1',[a])).cbr,98);assert.equal((await row(db,'select bonus,base_gain from cb_open_play_bonus_ledger')).bonus,2);await db.query('update cb_profiles set cbr=cbr+8 where user_id=$1',[a]);assert.equal((await row(db,'select count(*)::integer n from cb_open_play_bonus_ledger')).n,1);await win(db);assert.equal((await row(db,'select count(*)::integer n from cb_open_play_bonus_ledger')).n,2);}finally{await db.close();}});
test('overlapping sessions apply highest promo once, with audit record',async()=>{const db=await fixture();try{for(const bonus of [20,50]){const s=await create(db,{bonus});await join(db,s.id);await activate(db,s.id);}await presence(db);await win(db);assert.equal((await row(db,'select cbr from cb_profiles where user_id=$1',[a])).cbr,100);assert.equal((await row(db,'select count(*)::integer n,max(bonus_percent) p from cb_open_play_bonus_ledger')).p,50);}finally{await db.close();}});
for(const [name,fix] of [['outside 10 m',{lat:11.2442}],['inaccurate GPS',{accuracy:11}],['GPS disabled',{gps:false}],['stale GPS',{age:60}]])test(name+' does not qualify',async()=>{const db=await fixture();try{const s=await create(db);await join(db,s.id);await activate(db,s.id);await presence(db,fix);await win(db);assert.equal((await row(db,'select cbr from cb_profiles where user_id=$1',[a])).cbr,96);assert.equal((await row(db,'select count(*)::integer n from cb_open_play_bonus_ledger')).n,0);}finally{await db.close();}});
test('unregistered, future, ended and cancelled sessions cannot award a promo',async()=>{const db=await fixture();try{const s=await create(db);await presence(db);await win(db);await join(db,s.id);await win(db);await activate(db,s.id);await db.query('select cb_cancel_open_play($1,$2)',[owner,s.id]);await win(db);await assert.rejects(join(db,s.id,b),/closed/);await assert.rejects(db.query('select cb_cancel_open_play($1,$2)',[a,s.id]),/Only an owner/);assert.equal((await row(db,'select count(*)::integer n from cb_open_play_bonus_ledger')).n,0);const ended=await create(db);await join(db,ended.id);await db.query("update cb_open_play_sessions set starts_at=now()-interval '2 hours',ends_at=now()-interval '1 hour' where id=$1",[ended.id]);await win(db);await assert.rejects(join(db,ended.id,b),/closed/);assert.equal((await row(db,'select count(*)::integer n from cb_open_play_bonus_ledger')).n,0);}finally{await db.close();}});
test('10 m distance uses geographic meters and migration is safe to rerun',async()=>{const db=await fixture();try{await db.exec(sql);const r=await row(db,'select cb_open_play_distance(11.244,125.003,11.24408,125.003) near,cb_open_play_distance(11.244,125.003,11.2441,125.003) far');assert.ok(r.near<10);assert.ok(r.far>10);await db.exec('set role authenticated');await assert.rejects(db.query('select cb_join_open_play($1,$2,true)',[a,owner]),/permission denied/);}finally{await db.close();}});
