'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {cbgPurchases,type CbgOrder,type CbgPackage} from './cbg-purchases-client';
import DonationEditor from './donation-editor';
import './cbg-editor.css';
const blank=(slot:number):CbgPackage=>({slot,cbg_amount:100,price_php:100,active:true,promo_percent:0,promo_first_n:0,promo_start_at:null});
export default function CbgEditor(){
 const [packs,setPacks]=useState<CbgPackage[]>([]),[orders,setOrders]=useState<CbgOrder[]>([]),[editing,setEditing]=useState<CbgPackage|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [sales,setSales]=useState<CbgOrder[]>([]),[saleCount,setSaleCount]=useState(0),[page,setPage]=useState(1),[filters,setFilters]=useState({reference:'',date:'',amount:'',user:'',cbg:''}),[applied,setApplied]=useState({reference:'',date:'',amount:'',user:'',cbg:''}),[salesError,setSalesError]=useState('');
 const loadSales=async(p=page,search=applied)=>{try{const result=await cbgPurchases<{orders:CbgOrder[];count:number}>('sales',{page:p,...search});setSales(result.orders);setSaleCount(result.count);setSalesError('')}catch(e){setSalesError((e as Error).message)}};
 const load=async()=>{try{const [catalog,pending]=await Promise.all([cbgPurchases<{packages:CbgPackage[]}>('catalog'),cbgPurchases<{orders:CbgOrder[]}>('pending')]);setPacks(catalog.packages);setOrders(pending.orders);setError('')}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load();void loadSales(1)},[]);
 const save=async()=>{if(!editing)return;setBusy(true);try{await cbgPurchases('save-package',editing);setEditing(null);await load();toast.success('CBG price list saved.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const review=async(order:CbgOrder,approve:boolean)=>{if(!window.confirm(`${approve?'Approve':'Reject'} ${order.cbg_amount} CBG for @${order.buyer?.username||'buyer'}? Verify the payment in your payment app first.`))return;let reason='';if(!approve){reason=window.prompt('Reason shown to the buyer','Payment could not be verified.')||'';if(!reason)return}setBusy(true);try{await cbgPurchases('review',{id:order.id,approve,reason});await load();await loadSales();toast.success(approve?'Payment approved and CBG credited.':'Order rejected.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const available=Array.from({length:10},(_,i)=>i+1).find(slot=>!packs.some(pack=>pack.slot===slot));
 return <section className="cbg-editor"><header><div><small>OWNER PRICING</small><h2>CBG Editor</h2><p>Create up to ten price lists. Package and promotion changes affect new reservations only.</p></div><button type="button" disabled={!available||busy} onClick={()=>available&&setEditing(blank(available))}>Add price list ({packs.length}/10)</button></header>
 {error&&<p role="alert" className="cbg-editor-error">{error}</p>}
 <div className="cbg-editor-grid">{packs.map(pack=><article key={pack.slot}><small>PRICE LIST {pack.slot} · {pack.active?'ACTIVE':'HIDDEN'}</small><strong>{pack.cbg_amount.toLocaleString()} CBG</strong><b>₱{Number(pack.price_php).toFixed(2)}</b><span>{pack.promo_percent?`${pack.promo_percent}% off for first ${pack.promo_first_n} from ${new Date(pack.promo_start_at!).toLocaleDateString()}`:'Regular price'}</span><button type="button" onClick={()=>setEditing({...pack})}>Edit</button></article>)}</div>
 {editing&&<form className="cbg-editor-form" onSubmit={e=>{e.preventDefault();void save()}}><h3>Edit price list {editing.slot}</h3><label>CBG amount<input required type="number" min="1" max="1000000" value={editing.cbg_amount} onChange={e=>setEditing({...editing,cbg_amount:Number(e.target.value)})}/></label><label>Price in Philippine pesos<input required type="number" min="0.01" step="0.01" value={editing.price_php} onChange={e=>setEditing({...editing,price_php:Number(e.target.value)})}/></label><label>Pricing<select value={editing.promo_percent?'promo':'regular'} onChange={e=>setEditing({...editing,promo_percent:e.target.value==='promo'?10:0,promo_first_n:e.target.value==='promo'?10:0,promo_start_at:e.target.value==='promo'?new Date().toISOString():null})}><option value="regular">Regular</option><option value="promo">Promo</option></select></label>{editing.promo_percent>0&&<><label>Discount percentage<input required type="number" min="1" max="99" value={editing.promo_percent} onChange={e=>setEditing({...editing,promo_percent:Number(e.target.value)})}/></label><label>First number of purchases<input required type="number" min="1" max="100000" value={editing.promo_first_n} onChange={e=>setEditing({...editing,promo_first_n:Number(e.target.value)})}/></label><label>Promo starts<input required type="datetime-local" value={editing.promo_start_at?new Date(editing.promo_start_at).toLocaleString('sv-SE').replace(' ','T').slice(0,16):''} onChange={e=>setEditing({...editing,promo_start_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label></>}<label className="cbg-editor-active"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> Visible in Shop</label><div><button disabled={busy} type="submit">Save price list</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 <div className="cbg-pending"><header><h3>Pending payment verification ({orders.length})</h3><button type="button" onClick={()=>void load()}>Refresh</button></header><p>Check your QRPh payment app for the full transaction and amount. The six digit reference alone does not prove payment.</p>{!orders.length&&<p>No pending purchases.</p>}{orders.map(order=><article key={order.id}><div><b>{order.buyer?.display_name||'Player'} · @{order.buyer?.username||'unknown'}</b><span>{order.cbg_amount.toLocaleString()} CBG · Paid amount ₱{Number(order.amount_php).toFixed(2)} · Reference ending {order.reference_last6}</span><small>{new Date(order.created_at).toLocaleString()}</small></div><button type="button" disabled={busy} onClick={()=>void review(order,true)}>Approve</button><button type="button" disabled={busy} onClick={()=>void review(order,false)}>Reject</button></article>)}</div>
 <DonationEditor/>
 <div className="cbg-sales"><header><div><h3>CBG sales log</h3><p>{saleCount.toLocaleString()} approved purchases · 10 per page</p></div><button type="button" onClick={()=>void loadSales()}>Refresh</button></header>
 <form className="cbg-sales-search" onSubmit={e=>{e.preventDefault();setApplied({...filters});setPage(1);void loadSales(1,filters)}}><label>Reference (last 6)<input inputMode="numeric" maxLength={6} value={filters.reference} onChange={e=>setFilters({...filters,reference:e.target.value.replace(/\D/g,'')})}/></label><label>Approval date (UTC)<input type="date" value={filters.date} onChange={e=>setFilters({...filters,date:e.target.value})}/></label><label>Amount paid (₱)<input type="number" min="0" step="0.01" value={filters.amount} onChange={e=>setFilters({...filters,amount:e.target.value})}/></label><label>Buyer<input placeholder="Username or name" value={filters.user} onChange={e=>setFilters({...filters,user:e.target.value})}/></label><label>CBG credited<input type="number" min="1" step="1" value={filters.cbg} onChange={e=>setFilters({...filters,cbg:e.target.value})}/></label><button type="submit">Trace sales</button><button type="button" onClick={()=>{const empty={reference:'',date:'',amount:'',user:'',cbg:''};setFilters(empty);setApplied(empty);setPage(1);void loadSales(1,empty)}}>Clear</button></form>
 {salesError&&<p className="cbg-editor-error" role="alert">{salesError}</p>}{!salesError&&!sales.length&&<p>No approved sales match these filters.</p>}
 <div className="cbg-sales-list">{sales.map(order=><article key={order.id}><b>{order.buyer?.display_name||'Player'} · @{order.buyer?.username||'unknown'}</b><span>₱{Number(order.amount_php).toFixed(2)} paid · {order.cbg_amount.toLocaleString()} CBG credited{order.promo_percent>0?` · ${order.promo_percent}% promo`:''}</span><small>Ref ending {order.reference_last6} · Approved {new Date(order.reviewed_at||order.created_at).toLocaleString()}</small></article>)}</div>
 {saleCount>10&&<nav className="cbg-sales-pages" aria-label="CBG sales pages"><button type="button" disabled={page<=1} onClick={()=>{setPage(page-1);void loadSales(page-1)}}>Previous</button><span>Page {page} of {Math.ceil(saleCount/10)}</span><button type="button" disabled={page>=Math.ceil(saleCount/10)} onClick={()=>{setPage(page+1);void loadSales(page+1)}}>Next</button></nav>}</div>
 </section>;
}
