'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {cbgPurchases,packagePrice,type CbgOrder,type CbgPackage} from './cbg-purchases-client';
import './cbg-shop.css';
export default function CbgShop(){
 const [packs,setPacks]=useState<CbgPackage[]>([]),[orders,setOrders]=useState<CbgOrder[]>([]),[chosen,setChosen]=useState<CbgOrder|null>(null),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const result=await cbgPurchases<{packages:CbgPackage[];orders:CbgOrder[]}>('catalog');setPacks(result.packages);setOrders(result.orders);setError('');}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load()},[]);
 const choose=async(pack:CbgPackage)=>{setBusy(true);try{const result=await cbgPurchases<{order:CbgOrder}>('reserve',{id:crypto.randomUUID(),slot:pack.slot});setChosen(result.order);setReference('');await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const pay=async()=>{if(!chosen||!/^[0-9]{6}$/.test(reference))return;setBusy(true);try{await cbgPurchases('submit',{id:chosen.id,reference_last6:reference});setChosen(null);setReference('');await load();toast.success('Payment reference submitted for owner verification.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const cancel=async(order:CbgOrder)=>{if(!window.confirm('Cancel this unpaid CBG order? Only cancel if you have not sent payment.'))return;setBusy(true);try{await cbgPurchases('cancel',{id:order.id});if(chosen?.id===order.id)setChosen(null);await load();toast.success('Unpaid order cancelled.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 return <section className="cbg-store" aria-label="Purchase CBG"><header><img src="/inventory/cbg-coin.webp" alt=""/><span><small>CHESS BURGER GOLD</small><h2>Purchase CBG</h2><p>Choose a pack, pay through QRPh, and submit the last six digits of your payment reference.</p></span></header>
 {error&&<p className="cbg-store-error" role="alert">{error}</p>}
 {!error&&!packs.length&&<p>CBG packages will appear when the owner publishes them.</p>}
 <div className="cbg-pack-grid">{packs.map(pack=><button type="button" key={pack.slot} disabled={busy} onClick={()=>void choose(pack)} className={chosen?.id&&chosen.cbg_amount===pack.cbg_amount?'selected':''}><strong>{pack.cbg_amount.toLocaleString()} CBG</strong><span>Pay ₱{packagePrice(pack).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}</span>{pack.applied_promo_percent? <small>{pack.applied_promo_percent}% off · regular ₱{Number(pack.price_php).toFixed(2)}</small>:<small>Regular price{pack.promo_percent>0?' · promo currently unavailable':''}</small>}</button>)}</div>
 {chosen&&<div className="cbg-checkout"><h3>Exact amount to send: ₱{Number(chosen.amount_php).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}</h3><strong>Receive {chosen.cbg_amount.toLocaleString()} CBG{chosen.promo_percent>0?` · ${chosen.promo_percent}% promo applied`:''}</strong><small>Reserved price until {new Date(chosen.expires_at||'').toLocaleString()}</small><p>Scan the QRPh code using your banking or e-wallet app. Enter the exact amount above in your payment app. The QR code may not include the amount. Confirm it before sending.</p><img src="/shop/chess-burger-qrph.png" alt="Chess Burger QRPh payment code"/><label>Last 6 digits of the payment reference<input inputMode="numeric" autoComplete="off" maxLength={6} pattern="[0-9]{6}" placeholder="000000" value={reference} onChange={e=>setReference(e.target.value.replace(/\D/g,'').slice(0,6))}/></label><button type="button" disabled={busy||reference.length!==6} onClick={()=>void pay()}>{busy?'Submitting…':'I paid · Send for verification'}</button><p role="status">After you submit, owner approval usually takes 5 minutes to 3 hours. CBG is added only after the owner confirms receiving your payment. Keep your payment receipt.</p><div className="cbg-checkout-actions"><button type="button" className="cbg-cancel" onClick={()=>setChosen(null)}>Close checkout</button><button type="button" className="cbg-cancel" disabled={busy} onClick={()=>void cancel(chosen)}>Cancel unpaid order</button></div></div>}
 {orders.some(order=>order.status!=='awaiting_payment'||new Date(order.expires_at||'').getTime()>Date.now())&&<div className="cbg-orders"><h3>Your CBG orders</h3><button type="button" onClick={()=>void load()}>Refresh status</button>{orders.filter(order=>order.status!=='awaiting_payment'||new Date(order.expires_at||'').getTime()>Date.now()).map(order=><article key={order.id}><b>{order.cbg_amount.toLocaleString()} CBG · ₱{Number(order.amount_php).toFixed(2)}</b><span>{order.reference_last6?`Reference ending ${order.reference_last6}`:'Payment reference not submitted'} · {{awaiting_payment:'Awaiting payment',pending:'Under review',approved:'Approved',rejected:'Not verified'}[order.status]}</span>{order.status==='awaiting_payment'&&<><button type="button" disabled={busy} onClick={()=>setChosen(order)}>Continue payment</button><button type="button" disabled={busy} onClick={()=>void cancel(order)}>Cancel unpaid order</button></>}{order.reject_reason&&<small>{order.reject_reason}</small>}</article>)}</div>}
 </section>;
}
