"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {QRCodeSVG} from "qrcode.react";
import jsQR from "jsqr";
import {getSupabase} from "./supabase";
import "./seba-tournament.css";
import "./certificates.css";

export type Certificate={id:string;student_id:string;student_name:string;title:string;coach_name:string;session_started_at:string;rank:number|null;issued_at:string;code?:string|null};
export const certificateUrl=(code:string)=>`${location.origin}/?verify-certificate=${encodeURIComponent(code)}`;
async function api<T>(action:"list"|"verify",value?:string):Promise<T>{
 const client=action==="list"?await getSupabase():null,session=client?(await client.auth.getSession()).data.session:null;
 const response=await fetch("/api/certificates",{method:"POST",headers:{"Content-Type":"application/json",...(session?{Authorization:`Bearer ${session.access_token}`}:{})},body:JSON.stringify({action,...(value?{code:value}:{})}),cache:"no-store"});
 const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error||"Certificate service unavailable.");return data as T;
}
export function CertificatePaper({certificate}:{certificate:Certificate}){return <div className="seba-certificate-paper"><div className="seba-certificate-border"><div className="seba-certificate-watermark" aria-hidden="true"/><img className="seba-certificate-logo" src="/seba-certificate-logo-dark.png" alt="Chess Burger logo"/><small>SEba CLASSROOM</small><h2>Certificate of Achievement</h2><p>Presented to</p><h3>{certificate.student_name}</h3><p>for participating in</p><strong>{certificate.title}</strong>{certificate.rank&&<div className="seba-certificate-rank">Tournament ranking · #{certificate.rank}</div>}{certificate.code&&<div className="seba-certificate-qr" aria-label="Certificate verification QR code"><QRCodeSVG value={certificateUrl(certificate.code)} size={130} bgColor="#fffdf5" fgColor="#142d25" marginSize={1}/><small>SCAN TO VERIFY</small></div>}<div className="seba-certificate-footer"><span>Session started<br/><b>{new Date(certificate.session_started_at).toLocaleString()}</b></span><span>Coach<br/><b>AIM Bobbie Alota, CPA<br/>National Arbiter / National Instructor</b></span></div><small className="seba-certificate-disclaimer">This is a system generated cert and does not need a signature</small></div></div>}
export function CertificateViewer({certificate,onClose}:{certificate:Certificate;onClose:()=>void}){return <div className="seba-certificate-overlay" role="dialog" aria-modal="true" aria-label="Classroom certificate" onClick={onClose}><div className="seba-certificate-shell" onClick={e=>e.stopPropagation()}><button className="seba-certificate-close" onClick={onClose}>Close ×</button><CertificatePaper certificate={certificate}/><p className="seba-certificate-tip">Certificate expanded · take a screenshot to save it</p></div></div>}
const readCode=(value:string)=>{try{const url=new URL(value);if(url.origin!==location.origin)return "";return url.searchParams.get("verify-certificate")||""}catch{return ""}};
export function CertificateSection(){
 const [rows,setRows]=useState<Certificate[]>([]),[selected,setSelected]=useState<Certificate|null>(null),[message,setMessage]=useState(""),[verified,setVerified]=useState<Certificate|null>(null),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false),video=useRef<HTMLVideoElement|null>(null),stream=useRef<MediaStream|null>(null);
 const verify=useCallback(async(code:string)=>{setBusy(true);setVerified(null);try{if(!/^[A-Za-z0-9_-]{43}$/.test(code))throw Error("No Chess Burger verification QR found.");const result=await api<{valid:boolean;certificate?:Certificate}>("verify",code);setVerified(result.valid?result.certificate||null:null);setMessage(result.valid?"Verified · issued by Chess Burger":"Certificate not found or revoked.")}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}},[]);
 useEffect(()=>{let live=true;void api<{certificates:Certificate[]}>("list").then(v=>{if(live)setRows(v.certificates)}).catch(e=>{if(live)setMessage((e as Error).message)});return()=>{live=false}},[]);
 useEffect(()=>{if(!camera)return;let cancelled=false,raf=0;const canvas=document.createElement("canvas"),context=canvas.getContext("2d",{willReadFrequently:true});const scan=()=>{const element=video.current;if(!cancelled&&element&&element.readyState>=2&&context){canvas.width=element.videoWidth;canvas.height=element.videoHeight;context.drawImage(element,0,0);const pixels=context.getImageData(0,0,canvas.width,canvas.height),found=jsQR(pixels.data,pixels.width,pixels.height);if(found){const code=readCode(found.data);if(code){setCamera(false);void verify(code);return}}}if(!cancelled)raf=requestAnimationFrame(scan)};void navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}}).then(s=>{if(cancelled){s.getTracks().forEach(t=>t.stop());return}stream.current=s;if(video.current){video.current.srcObject=s;void video.current.play().then(()=>{raf=requestAnimationFrame(scan)})}}).catch(()=>{setCamera(false);setMessage("Camera unavailable. Upload a QR image instead.")});return()=>{cancelled=true;cancelAnimationFrame(raf);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}},[camera,verify]);
 async function upload(file?:File){if(!file)return;setMessage("");try{const image=await createImageBitmap(file),canvas=document.createElement("canvas");canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext("2d");if(!context)throw Error("Cannot read this image.");context.drawImage(image,0,0);image.close();const pixels=context.getImageData(0,0,canvas.width,canvas.height),found=jsQR(pixels.data,pixels.width,pixels.height);if(!found)throw Error("No QR code found in the image.");await verify(readCode(found.data))}catch(e){setMessage((e as Error).message)}}
 return <section className="training-certificates" aria-label="Saved certificates"><header><div><small>SEba · VERIFIED ACHIEVEMENTS</small><h2>Certificates</h2><p>Your issued certificates are saved to your account for future reference.</p></div></header><div className="training-certificate-grid">{rows.map(c=><button key={c.id} type="button" onClick={()=>setSelected(c)}><span>✦</span><strong>{c.title}</strong><small>{new Date(c.issued_at).toLocaleDateString()} · {c.student_name}</small><b>View certificate ↗</b></button>)}{!rows.length&&<p>No certificates issued to your account yet.</p>}</div><div className="training-certificate-scanner"><div><h3>Verify a certificate</h3><p>Scan its QR with your camera or upload an image of the QR. Anyone with the certificate can check its authenticity.</p></div><button type="button" onClick={()=>setCamera(v=>!v)}>{camera?"Stop camera":"Scan with camera"}</button><label>Upload QR image<input type="file" accept="image/*" onChange={e=>{void upload(e.target.files?.[0]);e.target.value=""}}/></label>{camera&&<video ref={video} playsInline muted aria-label="QR scanner camera"/>}{message&&<p role="status" className={verified?"certificate-valid":"certificate-invalid"}>{busy?"Checking…":message}</p>}{verified&&<dl><div><dt>Student</dt><dd>{verified.student_name}</dd></div><div><dt>Session</dt><dd>{verified.title}</dd></div><div><dt>Started</dt><dd>{new Date(verified.session_started_at).toLocaleString()}</dd></div><div><dt>Issued</dt><dd>{new Date(verified.issued_at).toLocaleString()}</dd></div></dl>}</div>{selected&&<CertificateViewer certificate={selected} onClose={()=>setSelected(null)}/>}</section>
}
export function CertificateVerificationPage({code}:{code:string}){const [result,setResult]=useState<{valid:boolean;certificate?:Certificate}|null>(null),[error,setError]=useState("");useEffect(()=>{void api<{valid:boolean;certificate?:Certificate}>("verify",code).then(setResult).catch(e=>setError((e as Error).message))},[code]);return <main className="certificate-public-check"><img src="/seba-certificate-logo-dark.png" alt="Chess Burger"/><small>CHESS BURGER · CERTIFICATE VERIFICATION</small><h1>{error?"Verification unavailable":!result?"Checking certificate…":result.valid?"Certificate verified":"Certificate not found or revoked"}</h1>{result?.valid&&result.certificate&&<dl><div><dt>Student</dt><dd>{result.certificate.student_name}</dd></div><div><dt>Session</dt><dd>{result.certificate.title}</dd></div><div><dt>Started</dt><dd>{new Date(result.certificate.session_started_at).toLocaleString()}</dd></div><div><dt>Issued</dt><dd>{new Date(result.certificate.issued_at).toLocaleString()}</dd></div></dl>}{error&&<p role="alert">{error}</p>}<a href="/">Open Chess Burger</a></main>}
