'use client';
import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import {CalendarDays,Clock,LocateFixed,MapPin,Plus,Users,X} from 'lucide-react';
import {arena} from './arena-client';
import type {Position} from './gps-presence';
import './chess-open-play.css';
export type OpenPlaySession={id:string;title:string;latitude:number;longitude:number;location:string;radius_m:number;starts_at:string;ends_at:string;bonus_percent:number;capacity:number|null;registered:boolean;registrant_count:number};
type Props={enabled:boolean;position:Position|null;toggle:()=>void;error:string};
type Draft={id?:string;lat:number;lng:number;start:string;end:string;bonus:string;capacity:string};
const localInput=(value:string)=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const when=(s:OpenPlaySession)=>new Date(s.starts_at).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});
const clock=(value:string)=>new Date(value).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});
export default function ChessOpenPlay({enabled,position,toggle,error:gpsError}:Props){
 const node=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layers=useRef<L.LayerGroup|null>(null),self=useRef<L.CircleMarker|null>(null),draftLayer=useRef<L.LayerGroup|null>(null),placingRef=useRef(false),centered=useRef(false);
 const [sessions,setSessions]=useState<OpenPlaySession[]>([]),[owner,setOwner]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState(''),[ready,setReady]=useState(false),[placing,setPlacing]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false);
 const form=useRef<HTMLFormElement>(null),details=useRef<HTMLElement>(null);
 const selected=sessions.find(s=>s.id===selectedId)??null;
 placingRef.current=placing&&owner;
 async function refresh(){const data=await arena<{sessions:OpenPlaySession[];owner:boolean}>('open-play-list');setSessions(data.sessions);setOwner(data.owner);}
 useEffect(()=>{let alive=true,pending=false;const load=async()=>{if(pending||document.visibilityState==='hidden')return;pending=true;try{const data=await arena<{sessions:OpenPlaySession[];owner:boolean}>('open-play-list');if(alive){setSessions(data.sessions);setOwner(data.owner);setError('');}}catch(e){if(alive)setError((e as Error).message);}finally{pending=false;if(alive)setLoading(false);}};void load();const timer=setInterval(load,20000);return()=>{alive=false;clearInterval(timer);};},[]);
 useEffect(()=>{
  if(!node.current)return;
  let instance:L.Map;try{instance=L.map(node.current).setView([11.244,125.003],14);map.current=instance;
  const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19});let fallback=false;
  tiles.on('tileerror',()=>{if(fallback)return;fallback=true;tiles.remove();L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO',maxZoom:20}).addTo(instance);});tiles.addTo(instance);
  layers.current=L.layerGroup().addTo(instance);draftLayer.current=L.layerGroup().addTo(instance);
  instance.on('click',(event:L.LeafletMouseEvent)=>{if(!placingRef.current)return;setDraft({lat:event.latlng.lat,lng:event.latlng.lng,start:'',end:'',bonus:'20',capacity:''});setSelectedId(null);setPlacing(false);});
  setReady(true);
  }catch{setError('The map could not load. Switch tabs and try again.');return;}
  const frame=requestAnimationFrame(()=>instance.invalidateSize());return()=>{cancelAnimationFrame(frame);instance.remove();map.current=null;layers.current=null;draftLayer.current=null;self.current=null;};
 },[]);
 useEffect(()=>{if(!ready||!map.current||!layers.current)return;layers.current.clearLayers();for(const s of sessions){
  L.circle([s.latitude,s.longitude],{radius:10,color:'#12aab8',weight:2,fillColor:'#23d4d4',fillOpacity:.2}).addTo(layers.current);
  const icon=L.divIcon({className:'open-play-pin',html:'<span aria-hidden="true">♟</span>',iconSize:[38,44],iconAnchor:[19,40]});
  L.marker([s.latitude,s.longitude],{icon,title:'Chess Open Play'}).bindTooltip(`Chess Open Play · +${s.bonus_percent}% CBR`).on('click',()=>{if(placingRef.current)return;setSelectedId(s.id);setDraft(null);}).addTo(layers.current);
 }if(!centered.current&&sessions.length&&!position){map.current.fitBounds(L.latLngBounds(sessions.map(s=>[s.latitude,s.longitude] as [number,number])),{padding:[48,48],maxZoom:16});centered.current=true;}
 },[ready,sessions,position]);
 useEffect(()=>{if(!ready||!map.current)return;if(enabled&&position){if(!self.current)self.current=L.circleMarker([position.lat,position.lng],{radius:7,color:'#fff',weight:3,fillColor:'#138bef',fillOpacity:1}).bindTooltip('Your location').addTo(map.current);else self.current.setLatLng([position.lat,position.lng]);if(!centered.current){map.current.setView([position.lat,position.lng],17);centered.current=true;}}else{self.current?.remove();self.current=null;}},[ready,enabled,position]);
 useEffect(()=>{draftLayer.current?.clearLayers();if(draft&&draftLayer.current){L.circle([draft.lat,draft.lng],{radius:10,color:'#d7a128',weight:3,fillOpacity:.25}).addTo(draftLayer.current);L.marker([draft.lat,draft.lng],{icon:L.divIcon({className:'open-play-pin draft',html:'<span aria-hidden="true">＋</span>',iconSize:[38,44],iconAnchor:[19,40]})}).addTo(draftLayer.current);form.current?.scrollIntoView({behavior:'smooth',block:'nearest'});}},[draft?.lat,draft?.lng]);
 useEffect(()=>{if(selected)details.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[selectedId]);
 function choose(s:OpenPlaySession){setSelectedId(s.id);setDraft(null);setPlacing(false);map.current?.setView([s.latitude,s.longitude],19);}
 async function act(action:string,id:string){setBusy(true);setError('');setStatus('');try{await arena(action,{id});await refresh();setStatus(action==='open-play-join'?'You are registered. Visit the pin during the session to activate the CBR promo.':action==='open-play-leave'?'Your registration was removed.':'Session cancelled.');if(action==='open-play-cancel')setSelectedId(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(event:React.FormEvent){event.preventDefault();if(!draft)return;setBusy(true);setError('');try{const result=await arena<{session:OpenPlaySession}>('open-play-save',{id:draft.id??null,lat:draft.lat,lng:draft.lng,starts_at:new Date(draft.start).toISOString(),ends_at:new Date(draft.end).toISOString(),bonus_percent:Number(draft.bonus),capacity:draft.capacity?Number(draft.capacity):null});await refresh();setDraft(null);setSelectedId(result.session.id);setStatus('Chess Open Play is scheduled. Its location was automatically set from the pin.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const live=sessions.filter(s=>Date.parse(s.starts_at)<=Date.now());
 let distance:number|null=null;if(position&&selected)distance=L.latLng(position.lat,position.lng).distanceTo([selected.latitude,selected.longitude]);
 const eligible=!!selected&&selected.registered&&enabled&&!!position&&position.accuracy<=10&&distance!==null&&distance<=10&&Date.parse(selected.starts_at)<=Date.now()&&Date.parse(selected.ends_at)>Date.now();
 return <section className="open-play-page">
  <header className="open-play-heading"><div><span className="open-play-eyebrow">MEET • PLAY • EARN</span><h1>Chess Open Play</h1><p>Find your next chess meetup. Register, visit the pin, and earn bonus CBR from wins.</p></div><button className={'gps-toggle '+(enabled?'on':'')} aria-pressed={enabled} onClick={toggle}><LocateFixed size={16}/>{enabled?'GPS on':'Enable GPS'}</button></header>
  <div className="open-play-summary"><span><CalendarDays size={17}/>{sessions.length} scheduled</span><span><i/>{live.length} live now</span><span><MapPin size={17}/>10 m promo zone</span></div>
  <div className={'open-play-map '+(placing?'placing':'')}><div ref={node} className="open-play-map-canvas"/>{placing&&<div className="open-play-map-hint">Tap anywhere on the map to place your 10 m pin.</div>}<div className="open-play-map-tools">{owner&&<button className="gold-button" aria-pressed={placing} onClick={()=>{setPlacing(!placing);setDraft(null);}}><Plus size={17}/>{placing?'Cancel pin':'Pin Open Play'}</button>}<button aria-label="Center on my location" disabled={!enabled||!position} onClick={()=>position&&map.current?.setView([position.lat,position.lng],19)}><LocateFixed size={20}/></button></div><span className="open-play-map-legend">♟ Open Play <i/> Your location</span></div>
  {(error||gpsError)&&<p className="inline-error" role="alert">{error||gpsError}</p>}{status&&<p className="open-play-status" role="status">{status}</p>}
  {draft&&owner&&<form ref={form} className="open-play-editor" onSubmit={save}><div className="section-title"><h2>{draft.id?'Edit session':'Schedule Chess Open Play'}</h2><button type="button" aria-label="Close schedule editor" onClick={()=>setDraft(null)}><X size={20}/></button></div><p><MapPin size={16}/> {draft.lat.toFixed(6)}, {draft.lng.toFixed(6)} · 10 m radius</p><small>The address is automatically resolved from this pin when saved. Times use your device timezone ({Intl.DateTimeFormat().resolvedOptions().timeZone}).</small><div className="open-play-fields"><label>Start date & time<input type="datetime-local" required value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label>End date & time<input type="datetime-local" required value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label><label>Extra CBR (%)<input type="number" required min="0" max="100" step="1" value={draft.bonus} onChange={e=>setDraft({...draft,bonus:e.target.value})}/></label><label>Joiner limit<input type="number" min="1" max="10000" step="1" value={draft.capacity} placeholder="Unlimited" onChange={e=>setDraft({...draft,capacity:e.target.value})}/><small>Leave blank for unlimited joiners.</small></label></div><button className="gold-button" disabled={busy}>{busy?'Saving…':'Publish session'}</button></form>}
  {selected&&<article className="open-play-detail" ref={details}><div className="section-title"><h2>Chess Open Play</h2><button aria-label="Close session details" onClick={()=>setSelectedId(null)}><X size={20}/></button></div><strong className="open-play-promo">+{selected.bonus_percent}% CBR from wins</strong><p><MapPin size={17}/>{selected.location}</p><p><CalendarDays size={17}/>{when(selected)}</p><p><Clock size={17}/>{clock(selected.starts_at)} – {clock(selected.ends_at)}{new Date(selected.ends_at).toDateString()!==new Date(selected.starts_at).toDateString()?' · ends '+new Date(selected.ends_at).toLocaleDateString():''}</p><p><Users size={17}/>{selected.registrant_count} registered · {selected.capacity===null?'Unlimited joiners':selected.capacity+' spots'}</p><p className="open-play-eligibility">{eligible?'Within promo zone. Keep GPS enabled while playing.':!selected.registered?'Register to unlock this session’s promo.':Date.parse(selected.starts_at)>Date.now()?'Your place is reserved. The promo starts with the session.':!enabled?'Enable GPS to activate your onsite promo.':position&&position.accuracy>10?'Waiting for GPS accuracy within 10 m.':distance!==null?`${Math.round(distance)} m from the pin. Move within 10 m for the promo.`:'Waiting for your GPS location.'}</p><small>Bonus applies to earned CBR from wins, with a fresh GPS fix inside the 10 m radius and accuracy within 10 m. Bonus CBR rounds up; overlapping promos use the highest percentage.</small><div className="open-play-actions">{selected.registered?<button disabled={busy} onClick={()=>void act('open-play-leave',selected.id)}>Leave session</button>:<button className="gold-button" disabled={busy||(selected.capacity!==null&&selected.registrant_count>=selected.capacity)} onClick={()=>void act('open-play-join',selected.id)}>{busy?'Registering…':selected.capacity!==null&&selected.registrant_count>=selected.capacity?'Session full':'Register to join'}</button>}<a href={`https://www.google.com/maps/dir/?api=1&destination=${selected.latitude},${selected.longitude}`} target="_blank" rel="noreferrer">Directions ↗</a>{owner&&<>{Date.parse(selected.starts_at)>Date.now()&&<button disabled={busy} onClick={()=>{setDraft({id:selected.id,lat:selected.latitude,lng:selected.longitude,start:localInput(selected.starts_at),end:localInput(selected.ends_at),bonus:String(selected.bonus_percent),capacity:selected.capacity===null?'':String(selected.capacity)});setSelectedId(null);}}>Edit session</button>}<button disabled={busy} onClick={()=>void act('open-play-cancel',selected.id)}>Cancel session</button></>}</div></article>}
  <section className="open-play-schedule"><div className="section-title"><h2>Open Play sessions</h2><span>{loading?'Loading…':sessions.length+' available'}</span></div><p className="open-play-timezone">Schedule shown in {Intl.DateTimeFormat().resolvedOptions().timeZone}.</p><div className="open-play-cards">{sessions.map(s=><button key={s.id} className={'open-play-card '+(selectedId===s.id?'selected':'')} onClick={()=>choose(s)}><span className="open-play-card-top"><span className="open-play-card-icon">♟</span><span><strong>Chess Open Play</strong><small>{Date.parse(s.starts_at)<=Date.now()?'LIVE NOW':when(s)}</small></span><b>+{s.bonus_percent}%<small>CBR</small></b></span><span className="open-play-card-location"><MapPin size={15}/>{s.location}</span><span className="open-play-card-time"><Clock size={15}/>{clock(s.starts_at)} – {clock(s.ends_at)}</span><span className="open-play-card-bottom"><span><Users size={14}/>{s.registrant_count}{s.capacity===null?' joined':' / '+s.capacity+' joined'}</span><strong>{s.registered?'✓ Registered':s.capacity!==null&&s.registrant_count>=s.capacity?'Full':'View & register →'}</strong></span></button>)}</div>{!loading&&!sessions.length&&!error&&<div className="open-play-empty"><MapPin size={30}/><h3>No sessions scheduled yet</h3><p>{owner?'Pin a location anywhere on the map to schedule your first Chess Open Play.':'Come back soon for the next Chess Open Play schedule.'}</p></div>}</section>
 </section>;
}
