"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Chess,type Square} from "chess.js";
import type {RealtimeChannel} from "@supabase/supabase-js";
import {ArrowLeft,Clock3,Coins,Eraser,Expand,Hand,Library,MousePointer2,OctagonX,PenLine,RotateCcw,ShoppingBag,Users,X} from "lucide-react";
import {toast} from "sonner";
import {classroom} from "./classroom-client";
import {getSupabase} from "./supabase";
import {DAILY_PUZZLES} from "./puzzle-data";
import "./classroom-workshop.css";

type Mark={type:"pen"|"arrow";color:"red"|"cyan";points?:number[][];from?:number[];to?:number[]};
type BoardState={fen:string;version?:number;annotations?:Mark[]};
type Student={user_id:string;display_name?:string;username?:string;avatar_url?:string;access_expires_at:string;board:BoardState};
type WorkshopState={role:"teacher"|"student";room:{id:string;name:string;max_students:number};workspace:BoardState&{annotations:Mark[];time_control:string;selected_student_id?:string|null};students:Student[];own_student_id?:string|null;wallet:{cbc:number};economy:{gold:number;cbc_gold_price:number}};
const symbols:Record<string,string>={wp:"♙",wn:"♘",wb:"♗",wr:"♖",wq:"♕",wk:"♔",bp:"♟",bn:"♞",bb:"♝",br:"♜",bq:"♛",bk:"♚"};
const controls=["3+0","5+0","10+0","15+10","30+0"];
const normalizeFen=(fen:string)=>fen==="start"?new Chess().fen():fen;

const invertPoint=(p:number[])=>[1-p[0],1-p[1]];
const invertMark=(mark:Mark):Mark=>mark.type==="pen"?{...mark,points:(mark.points||[]).map(invertPoint)}:{...mark,from:mark.from?invertPoint(mark.from):mark.from,to:mark.to?invertPoint(mark.to):mark.to};

function TeachingBoard({state,editable,tool="hand",color="red",marks=[],remoteDraft=null,allowedColor="both",flipped=false,invertMarks=false,freeMove=false,onChange,onMarks,onDraft,className=""}:{state:BoardState;editable:boolean;tool?:"hand"|"pen"|"arrow"|"eraser";color?:"red"|"cyan";marks?:Mark[];remoteDraft?:Mark|null;allowedColor?:"w"|"b"|"both";flipped?:boolean;invertMarks?:boolean;freeMove?:boolean;onChange?:(fen:string)=>void;onMarks?:(marks:Mark[])=>void;onDraft?:(mark:Mark|null)=>void;className?:string}){
  const chess=useMemo(()=>{try{return new Chess(normalizeFen(state.fen))}catch{return new Chess()}},[state.fen]);
  const [selected,setSelected]=useState<Square|null>(null),[legal,setLegal]=useState<Square[]>([]),[draft,setDraft]=useState<Mark|null>(null),drawing=useRef<number[][]>([]),boardRef=useRef<HTMLDivElement>(null),arrowStart=useRef<number[]|null>(null),frame=useRef<number|null>(null),lastPreview=useRef(0);
  const cells=chess.board().flat().map((piece,i)=>({piece,sq:("abcdefgh"[i%8]+(8-Math.floor(i/8))) as Square}));if(flipped)cells.reverse();
  const choose=(sq:Square)=>{if(!editable||tool!=="hand")return;if(!selected){const p=chess.get(sq);if(!p||!freeMove&&allowedColor!=="both"&&p.color!==allowedColor)return;setSelected(sq);setLegal(freeMove?cells.filter(c=>c.sq!==sq).map(c=>c.sq):chess.moves({square:sq,verbose:true}).map(m=>m.to as Square));return}try{const next=new Chess(chess.fen());if(freeMove){const piece=next.get(selected);if(piece){next.remove(selected);next.remove(sq);next.put(piece,sq);onChange?.(next.fen())}}else{next.move({from:selected,to:sq,promotion:"q"});onChange?.(next.fen())}}catch{}setSelected(null);setLegal([])};
  const point=(e:React.PointerEvent)=>{const r=boardRef.current!.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]};
  const eraseAt=(p:number[])=>{let closest=-1,distance=.075;marks.forEach((m,i)=>{if(m.type==="arrow"){const a=m.from||[0,0],b=m.to||[0,0],dx=b[0]-a[0],dy=b[1]-a[1],length=dx*dx+dy*dy,t=length?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/length)):0,q=[a[0]+t*dx,a[1]+t*dy],d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<distance){distance=d;closest=i}}else for(const q of m.points||[]){const d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<distance){distance=d;closest=i}}});if(closest>=0)onMarks?.(marks.filter((_,i)=>i!==closest))};
  const down=(e:React.PointerEvent)=>{if(!editable||tool==="hand")return;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);if(tool==="eraser")eraseAt(p);else if(tool==="pen"){const mark:Mark={type:"pen",color,points:[p]};drawing.current=[p];setDraft(mark);onDraft?.(mark)}else{const mark:Mark={type:"arrow",color,from:p,to:p};arrowStart.current=p;setDraft(mark);onDraft?.(mark)}};
  const move=(e:React.PointerEvent)=>{const p=point(e);if(tool==="pen"&&drawing.current.length)drawing.current=[...drawing.current,p];else if(tool!=="arrow"||!arrowStart.current)return;if(frame.current===null)frame.current=requestAnimationFrame(()=>{frame.current=null;const mark:Mark=tool==="pen"?{type:"pen",color,points:drawing.current}:{type:"arrow",color,from:arrowStart.current||p,to:p};setDraft(mark);if(Date.now()-lastPreview.current>=40){lastPreview.current=Date.now();onDraft?.(mark)}})};
  const up=(e:React.PointerEvent)=>{if(!editable||tool==="hand")return;if(frame.current!==null){cancelAnimationFrame(frame.current);frame.current=null}const p=point(e);if(tool==="pen"&&drawing.current.length){onMarks?.([...marks,{type:"pen",color,points:drawing.current}]);drawing.current=[]}else if(tool==="arrow"&&arrowStart.current){onMarks?.([...marks,{type:"arrow",color,from:arrowStart.current,to:p}]);arrowStart.current=null}setDraft(null);onDraft?.(null)};
  return <div className={`teaching-board ${className}`} ref={boardRef} onPointerDown={down} onPointerMove={move} onPointerUp={up}>
    {cells.map(({piece,sq},i)=><button type="button" key={sq} className={`teach-square ${(Math.floor(i/8)+i)%2?"dark":"light"} ${selected===sq?"selected":""} ${legal.includes(sq)?"legal":""}`} onClick={()=>choose(sq)}><span>{piece?symbols[piece.color+piece.type]:""}</span></button>)}
    <svg className="board-ink" viewBox="0 0 100 100" preserveAspectRatio="none">
      <defs><marker id="red-head" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6Z" fill="#ff3f4d"/></marker><marker id="cyan-head" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6Z" fill="#24e5f3"/></marker></defs>
      {[...(invertMarks?marks.map(invertMark):marks),...(remoteDraft?[invertMarks?invertMark(remoteDraft):remoteDraft]:[]),...(draft?[draft]:[])].map((m,i)=>m.type==="pen"?<polyline key={i} points={(m.points||[]).map(p=>`${p[0]*100},${p[1]*100}`).join(" ")} fill="none" stroke={m.color==="red"?"#ff3f4d":"#24e5f3"} strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>:<line key={i} x1={(m.from?.[0]||0)*100} y1={(m.from?.[1]||0)*100} x2={(m.to?.[0]||0)*100} y2={(m.to?.[1]||0)*100} stroke={m.color==="red"?"#ff3f4d":"#24e5f3"} strokeWidth="1.5" markerEnd={`url(#${m.color}-head)`}/>) }
    </svg>
  </div>
}

export default function ClassroomWorkshop({roomId,onExit}:{roomId:string;onExit:()=>void}){
  const liveChannel=useRef<RealtimeChannel|null>(null),persistQueue=useRef<Promise<unknown>>(Promise.resolve()),fastUpdateAt=useRef(0),exitRef=useRef(onExit);exitRef.current=onExit;
  const [data,setData]=useState<WorkshopState|null>(null),[error,setError]=useState(""),[tool,setTool]=useState<"hand"|"pen"|"arrow"|"eraser">("hand"),[color,setColor]=useState<"red"|"cyan">("red"),[library,setLibrary]=useState(false),[market,setMarket]=useState(false),[quantity,setQuantity]=useState(1),[recipient,setRecipient]=useState(""),[focus,setFocus]=useState<string|null>(null),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
  const [remoteInk,setRemoteInk]=useState<{scope:"workspace"|"student";student_id?:string;mark:Mark|null}|null>(null);
  const load=useCallback(async()=>{try{const next=await classroom<WorkshopState>("workshop-state",{room_id:roomId});setData(next);setError("")}catch(e){setError(e instanceof Error?e.message:"Workshop unavailable.")}},[roomId]);
  useEffect(()=>{let active=true,client:Awaited<ReturnType<typeof getSupabase>>=null;void load();void getSupabase().then(supabase=>{if(!active||!supabase)return;client=supabase;const channel=supabase.channel(`classroom:${roomId}`).on("broadcast",{event:"workspace"},message=>{const row=message.payload as WorkshopState["workspace"];if(row?.fen){fastUpdateAt.current=Date.now();setRemoteInk(null);setData(current=>current?{...current,workspace:{...current.workspace,...row}}:current)}}).on("broadcast",{event:"student-board"},message=>{const row=message.payload as BoardState&{student_id?:string};if(row?.student_id){fastUpdateAt.current=Date.now();setRemoteInk(null);setData(current=>current?{...current,students:current.students.map(student=>student.user_id===row.student_id?{...student,board:{...student.board,...row}}:student)}:current)}}).on("broadcast",{event:"ink-preview"},message=>setRemoteInk(message.payload as {scope:"workspace"|"student";student_id?:string;mark:Mark|null})).on("broadcast",{event:"terminated"},()=>{toast.info("The teacher ended this SEba session.");exitRef.current()}).on("postgres_changes",{event:"*",schema:"public",table:"cb_classroom_workspaces",filter:`room_id=eq.${roomId}`},payload=>{if(Date.now()-fastUpdateAt.current<2000)return;const row=payload.new as WorkshopState["workspace"];if(row?.fen)setData(current=>current?{...current,workspace:{...current.workspace,...row}}:current)}).on("postgres_changes",{event:"*",schema:"public",table:"cb_classroom_student_boards",filter:`room_id=eq.${roomId}`},payload=>{if(Date.now()-fastUpdateAt.current<2000)return;const row=payload.new as BoardState&{student_id?:string};if(row?.student_id)setData(current=>current?{...current,students:current.students.map(student=>student.user_id===row.student_id?{...student,board:{...student.board,...row}}:student)}:current)}).subscribe();liveChannel.current=channel}).catch(()=>{if(active)toast.warning("Live connection unavailable. Classroom will keep refreshing automatically.")});const recovery=setInterval(()=>void load(),10000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{active=false;clearInterval(recovery);clearInterval(clock);const channel=liveChannel.current;liveChannel.current=null;if(client&&channel)void client.removeChannel(channel)}},[load,roomId]);
  const broadcast=(event:"workspace"|"student-board"|"ink-preview"|"terminated",payload:unknown)=>{fastUpdateAt.current=Date.now();const channel=liveChannel.current;if(channel)void channel.send({type:"broadcast",event,payload})};
  const previewInk=(scope:"workspace"|"student",mark:Mark|null,student_id?:string)=>broadcast("ink-preview",{scope,student_id,mark});
  const persist=(body:Record<string,unknown>,message:string)=>{persistQueue.current=persistQueue.current.then(()=>classroom("workshop-update",body)).catch(e=>{toast.error(e instanceof Error?e.message:message)})};
  const updateMaster=(patch:Partial<WorkshopState["workspace"]>)=>{if(!data)return;const next={...data.workspace,...patch};setData(current=>current?{...current,workspace:{...current.workspace,...patch}}:current);broadcast("workspace",next);persist({room_id:roomId,kind:"master",fen:next.fen,annotations:next.annotations,time_control:next.time_control,selected_student_id:next.selected_student_id||null},"Lesson board did not sync.")};
  const updateShared=(fen:string)=>{if(!data)return;const next={...data.workspace,fen};setData(current=>current?{...current,workspace:{...current.workspace,fen}}:current);broadcast("workspace",next);persist({room_id:roomId,kind:"shared",fen},"Shared board did not sync.")};
  const updateStudent=(studentId:string,fen:string,annotations?:Mark[])=>{if(!data)return;const existing=data.students.find(student=>student.user_id===studentId)?.board||{fen:"start"},next={...existing,student_id:studentId,fen,...(annotations?{annotations}: {})};setData(current=>current?{...current,students:current.students.map(student=>student.user_id===studentId?{...student,board:{...student.board,fen,...(annotations?{annotations}: {})}}:student)}:current);broadcast("student-board",next);persist({room_id:roomId,kind:"student",student_id:studentId,fen,...(annotations?{annotations}: {})},"Student board did not sync.")};
  const terminate=async()=>{if(!window.confirm("Terminate this Classroom Session now? All enrolled students will be cleared and the room code will stop working."))return;setBusy(true);try{await classroom("terminate",{room_id:roomId});broadcast("terminated",{room_id:roomId});toast.success("Classroom Session terminated and enrollments cleared.");onExit()}catch(e){toast.error(e instanceof Error?e.message:"Unable to terminate this classroom.")}finally{setBusy(false)}};
  const buyCbc=async()=>{if(!data)return;setBusy(true);try{if(data.role==="teacher"){if(!recipient.trim())throw Error("Enter an enrolled student username.");const result=await classroom<{gold:number;recipient_cbc:number}>("buy-cbc-for-student",{room_id:roomId,username:recipient,quantity,request_id:crypto.randomUUID()});setData({...data,economy:{...data.economy,gold:result.gold}});toast.success(`${quantity} CBC sent directly to ${recipient}.`)}else{const result=await classroom<{gold:number;cbc:number}>("buy-cbc",{quantity,request_id:crypto.randomUUID()});setData({...data,wallet:{cbc:result.cbc},economy:{...data.economy,gold:result.gold}});toast.success(`${quantity} CBC added to your Bag.`)}setMarket(false);setRecipient("")}catch(e){toast.error(e instanceof Error?e.message:"CBC purchase failed.")}finally{setBusy(false)}};
  if(error&&!data)return <div className="classroom-workshop loading workshop-error"><section><h1>Classroom could not open</h1><p>{error}</p><div><button onClick={()=>void load()}>Try again</button><button onClick={onExit}>Return to Classroom</button></div></section></div>;
  if(!data)return <div className="classroom-workshop loading">Preparing your workshop…</div>;
  const teacher=data.role==="teacher",own=data.students.find(s=>s.user_id===data.own_student_id),oneOnOne=data.students.length===1,focused=data.students.find(s=>s.user_id===focus),remaining=own?Math.max(0,new Date(own.access_expires_at).getTime()-now):0,remainingText=`${String(Math.floor(remaining/60000)).padStart(2,"0")}:${String(Math.floor(remaining%60000/1000)).padStart(2,"0")}`;
  const master=<TeachingBoard state={data.workspace} editable={teacher} tool={tool} color={color} marks={data.workspace.annotations||[]} remoteDraft={!teacher&&remoteInk?.scope==="workspace"?remoteInk.mark:null} invertMarks={!teacher} freeMove={teacher} onChange={fen=>void updateMaster({fen})} onMarks={annotations=>void updateMaster({annotations})} onDraft={teacher?mark=>previewInk("workspace",mark):undefined}/>;
  return <section className="classroom-workshop">
    <header className="workshop-topbar"><button onClick={onExit}><ArrowLeft/>Exit</button><div><small>{teacher?"TEACHER WORKSHOP":"STUDENT WORKSHOP"}</small><h1>{data.room.name}</h1></div><div className="seba-brand" aria-label="SEba by Chess Burger version 1.021"><strong>SEba</strong><small>BY CHESS BURGER · v1.021</small></div>{!teacher&&<><span className="student-session-stat"><Clock3/><b>{remainingText}</b> remaining</span><span className="student-session-stat"><img src="/classroom/cbc-token.webp" alt=""/><b>{data.wallet.cbc}</b> CBC</span></>}<button className="seba-cbc-button" onClick={()=>setMarket(true)}><ShoppingBag/>{teacher?"Buy CBC for student":"Buy CBC"}</button><span><Users/>{data.students.length} active</span><span><Clock3/>{data.workspace.time_control}</span></header>
    {teacher&&<aside className="teacher-toolbar"><b>TEACHER TOOLS</b><button className={tool==="hand"?"active":""} onClick={()=>setTool("hand")}><Hand/>Hand</button><button className={tool==="pen"?"active":""} onClick={()=>setTool("pen")}><PenLine/>Pen</button><button className={tool==="arrow"?"active":""} onClick={()=>setTool("arrow")}><MousePointer2/>Arrow</button><button className={tool==="eraser"?"active":""} onClick={()=>setTool("eraser")}><Eraser/>Eraser</button><button className={`ink red ${color==="red"?"active":""}`} onClick={()=>setColor("red")}>Red</button><button className={`ink cyan ${color==="cyan"?"active":""}`} onClick={()=>setColor("cyan")}>Cyan</button><button onClick={()=>void updateMaster({annotations:[]})}><Eraser/>Clear all</button><button onClick={()=>setLibrary(true)}><Library/>Puzzle Library</button><label>Time control<select value={data.workspace.time_control} onChange={e=>void updateMaster({time_control:e.target.value})}>{controls.map(c=><option key={c}>{c}</option>)}</select></label><button onClick={()=>void updateMaster({fen:"start",annotations:[]})}><RotateCcw/>Reset board</button><button className="terminate-room" disabled={busy} onClick={()=>void terminate()}><OctagonX/>Terminate room</button></aside>}
    <main className={`workshop-stage ${teacher?"teacher-view":"student-view"} ${oneOnOne?"one-on-one":"group-view"}`}>
      {teacher?<>{oneOnOne?<section className="one-board"><h2>One-on-one shared board · Teacher controls all pieces</h2><TeachingBoard state={data.workspace} editable tool={tool} color={color} marks={data.workspace.annotations||[]} flipped freeMove onChange={fen=>void updateMaster({fen})} onMarks={annotations=>void updateMaster({annotations})} onDraft={mark=>previewInk("workspace",mark)}/></section>:focused?<section className="focus-board"><button onClick={()=>setFocus(null)}><X/>Close one-on-one focus</button><h2>{focused.display_name||focused.username||"Student"} · Teacher controls all pieces</h2><TeachingBoard state={focused.board} editable tool={tool} color={color} marks={focused.board.annotations||[]} flipped freeMove onChange={fen=>void updateStudent(focused.user_id,fen)} onMarks={annotations=>void updateStudent(focused.user_id,focused.board.fen,annotations)} onDraft={mark=>previewInk("student",mark,focused.user_id)}/></section>:<><section className="master-board-panel"><div><small>LIVE LESSON BOARD</small><h2>Teacher Board</h2></div>{master}<p>Desktop or laptop is recommended to maximize teaching tools.</p></section><section className="student-monitor"><header><small>LIVE STUDENT TABLES</small><h2>Tap a board for one-on-one instruction</h2></header><div>{data.students.map(s=><article key={s.user_id} onClick={()=>setFocus(s.user_id)}><span><img src={s.avatar_url||"/avatar-default.svg"} alt=""/><b>{s.display_name||s.username||"Student"}</b><Expand/></span><TeachingBoard state={s.board} editable={false} marks={s.board.annotations||[]}/></article>)}</div></section></>}</>:<>{oneOnOne&&own?<section className="one-board"><h2>One-on-one shared board · You play White</h2><TeachingBoard state={data.workspace} editable marks={data.workspace.annotations||[]} remoteDraft={remoteInk?.scope==="workspace"?remoteInk.mark:null} invertMarks allowedColor="w" onChange={fen=>void updateShared(fen)}/></section>:<><section className="student-teacher-board"><h2>Teacher lesson board</h2>{master}</section><section className="student-own-board"><h2>My practice board · White pieces</h2>{own?<TeachingBoard state={own.board} editable marks={own.board.annotations||[]} remoteDraft={remoteInk?.scope==="student"&&remoteInk.student_id===own.user_id?remoteInk.mark:null} invertMarks allowedColor="w" onChange={fen=>void updateStudent(own.user_id,fen)}/>:<p>Waiting for your board…</p>}</section></>}</>}
    </main>
    {library&&teacher&&<div className="puzzle-picker" role="dialog" aria-modal="true"><section><header><div><small>CHESSBURGER LIBRARY</small><h2>Choose a lesson puzzle</h2></div><button onClick={()=>setLibrary(false)}><X/></button></header><div>{DAILY_PUZZLES.map(p=><button key={p.id} disabled={busy} onClick={async()=>{setBusy(true);await updateMaster({fen:p.fen,annotations:[]});setBusy(false);setLibrary(false);toast.success(`${p.title} loaded`);}}><b>Chapter {p.chapter} · Puzzle {p.number}</b><strong>{p.title}</strong><span>{p.difficulty} · {p.rating} · {p.theme}</span></button>)}</div></section></div>}
    {market&&<div className="seba-market" role="dialog" aria-modal="true"><section><button className="seba-market-close" onClick={()=>setMarket(false)} aria-label="Close"><X/></button><div className="seba-market-token"><img src="/classroom/cbc-token.webp" alt="CBC token"/><span><small>SEba LEARNING CURRENCY</small><h2>{teacher?"Buy CBC for a student":"Buy CBC"}</h2><p>{teacher?"Purchase credits with your CBG and deposit them directly into an enrolled student’s Bag.":"Purchase CBC with CBG without leaving your active class session."}</p></span></div><div className="seba-market-balance"><span><Coins/><small>MY CBG</small><b>{data.economy.gold.toLocaleString()}</b></span>{!teacher&&<span><img src="/classroom/cbc-token.webp" alt=""/><small>MY CBC</small><b>{data.wallet.cbc.toLocaleString()}</b></span>}<span><small>RATE</small><b>{data.economy.cbc_gold_price.toLocaleString()} CBG / CBC</b></span></div>{teacher&&<label>Enrolled student username<input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="@student" maxLength={40}/></label>}<label>CBC quantity<input type="number" min={1} max={1000} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(1000,Number(e.target.value)||1)))}/></label><div className="seba-market-total"><span>Total cost</span><strong>{(data.economy.cbc_gold_price*quantity).toLocaleString()} CBG</strong></div><button className="seba-market-buy" disabled={busy||data.economy.cbc_gold_price<1||data.economy.gold<data.economy.cbc_gold_price*quantity||(teacher&&!recipient.trim())} onClick={()=>void buyCbc()}>{busy?"Processing…":data.economy.cbc_gold_price<1?"Awaiting owner price":data.economy.gold<data.economy.cbc_gold_price*quantity?"Not enough CBG":teacher?"Buy and send CBC":"Buy CBC"}</button></section></div>}
  </section>;
}
