"use client";
import {useEffect,useState} from "react";
import {Megaphone,Trophy,Coins,ScrollText,Image as ImageIcon,ShieldCheck} from "lucide-react";
import {toast} from "sonner";
import {PlayerProfile} from "./supabase";
import Tournaments from "./tournaments";
import {arena} from "./arena-client";
import StaffImageEditor from './staff-image-editor';
import {uploadStaffImage} from "./media";
type Log={id:string;actor_user_id:string;action:string;details:unknown;created_at:string};
type Post={id:string;content:string;image_url:string;expires_at:string};
export default function Cms({profile,onClose}:{profile:PlayerProfile;onClose:()=>void}){
 const[section,setSection]=useState("tournament"),[busy,setBusy]=useState(false),[text,setText]=useState(""),[image,setImage]=useState(""),[deadline,setDeadline]=useState(""),[editing,setEditing]=useState<string|null>(null),[posts,setPosts]=useState<Post[]>([]),[username,setUsername]=useState(""),[gold,setGold]=useState(10),[cardUrl,setCardUrl]=useState(""),[role,setRole]=useState("admin"),[logs,setLogs]=useState<Log[]>([]),[page,setPage]=useState(0),[logError,setLogError]=useState(""),[localLogs,setLocalLogs]=useState<Array<{at:string;actor:string;action:string;tournament:string}>>([]);
 const [featureLoaded,setFeatureLoaded]=useState(false);
 const [crop,setCrop]=useState<{file:File;target:"announcement"|"card"}|null>(null);
 const owner=profile.role==="owner",staff=owner||profile.role==="admin";
 const menu=[["tournament","Tournaments",Trophy],["announcement","Announcements",Megaphone],["card","App photo",ImageIcon],["gold","Gold",Coins],...(owner?[["roles","GM roles",ShieldCheck]]:[]),["logs","Activity logs",ScrollText]] as const;
 async function run(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function loadPosts(){const data=await arena<{posts:Post[]}>("cms-announcements");setPosts(data.posts);}
 useEffect(()=>{if(section==="card"){setFeatureLoaded(false);void arena<{image_url:string}>("app-feature",{},true).then(data=>{setCardUrl(data.image_url);setFeatureLoaded(true);}).catch(()=>toast.error("Could not load the app photo. Reopen this tab to retry."));}if(section==="announcement")void run(loadPosts);if(section==="logs"){setLogError("");void arena<{logs:Log[]}>("logs",{page}).then(data=>setLogs(data.logs)).catch(()=>setLogError("Activity logs are temporarily unavailable."));try{setLocalLogs(JSON.parse(localStorage.getItem("cb-offline-audit")??"[]"));}catch{setLocalLogs([]);}}},[section,page]);
 async function publish(){if(!text.trim()&&!image)throw Error("Add text or an image.");const end=new Date(deadline);if(!Number.isFinite(end.getTime())||end.getTime()<=Date.now())throw Error("Choose a future end date.");await arena("save-announcement",{id:editing,content:text.trim(),image_url:image,expires_at:end.toISOString()});setText("");setImage("");setDeadline("");setEditing(null);await loadPosts();window.dispatchEvent(new Event("cb-profile-saved"));toast.success("Announcement published.");}
 async function upload(file:File,target:"announcement"|"card"){const url=await uploadStaffImage(file,profile.user_id);if(target==="announcement")setImage(url);else setCardUrl(url);toast.success("Image uploaded. Save to publish it.");}
 if(!staff)return <p>Owner or GM access is required.</p>;
 return <section className="cms-page"><div className="cms-heading"><div><span>{owner?"OWNER":"GM ADMIN"} CONTROL</span><h1>Chess Burger CMS</h1></div><button onClick={onClose}>Close</button></div><div className="cms-tabs">{menu.map(([key,label,Icon])=><button key={key as string} className={section===key?"active":""} onClick={()=>setSection(key as string)}><Icon/>{label as string}</button>)}</div>
 {section==="tournament"&&<Tournaments profile={profile} host/>}
 {section==="announcement"&&<div className="cms-panel"><h2>{editing?"Edit announcement":"Post announcement"}</h2><label>Text<textarea maxLength={500} value={text} onChange={e=>setText(e.target.value)}/></label><label>Upload image<input disabled={busy} type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setCrop({file:f,target:"announcement"});}}/></label>{image&&<img src={image} alt="Announcement preview"/>}<label>End date and time<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><button disabled={busy} onClick={()=>void run(publish)}>Publish announcement</button>{editing&&<button onClick={()=>{setEditing(null);setText("");setImage("");setDeadline("");}}>Cancel edit</button>}<h3>Active announcements</h3>{posts.map(p=><article key={p.id}><p>{p.content||"Image announcement"}</p><p>Ends {new Date(p.expires_at).toLocaleString()}</p><div className="cms-actions"><button onClick={()=>{setEditing(p.id);setText(p.content);setImage(p.image_url);const date=new Date(p.expires_at);setDeadline(new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16));}}>Edit</button><button disabled={busy} onClick={()=>void run(async()=>{await arena("delete-announcement",{id:p.id});await loadPosts();window.dispatchEvent(new Event("cb-profile-saved"));})}>Delete</button></div></article>)}</div>}
 {section==="card"&&<div className="cms-panel"><h2>App featured photo</h2><p>One announcement or advertisement displayed beneath every User Card.</p><label>Upload photo<input disabled={busy} type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setCrop({file:f,target:"card"});}}/></label><button type="button" onClick={()=>setCardUrl("")}>Clear selected photo</button>{cardUrl&&<img src={cardUrl} alt="App advertisement preview"/>}<button disabled={busy||!featureLoaded} onClick={()=>void run(async()=>{await arena("set-app-feature",{url:cardUrl});toast.success("App featured photo updated for everyone.");})}>Save featured photo</button><p className="cms-note">Crop, reposition and resize before publishing. Photos are saved as WebP under 1 MB. Clear the photo and save to remove the advertisement.</p></div>}
 {section==="gold"&&<div className="cms-panel"><h2>Grant Gold</h2><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username"/></label><label>Gold amount<input type="number" min={1} max={10000} value={gold} onChange={e=>setGold(Number(e.target.value))}/></label><button disabled={busy||!username.trim()} onClick={()=>void run(async()=>{if(!Number.isInteger(gold)||gold<1||gold>10000)throw Error("Enter 1–10,000 Gold.");await arena("grant-gold",{username,amount:gold,request_id:crypto.randomUUID()});toast.success("Gold granted and logged.");})}>Grant Gold</button></div>}
 {section==="roles"&&owner&&<div className="cms-panel"><h2>Manage GM access</h2><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username"/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="admin">GM / Admin</option><option value="player">Player</option></select></label><button disabled={busy||!username.trim()} onClick={()=>void run(async()=>{await arena("set-role",{username,role});toast.success("Role updated and logged.");})}>Save role</button></div>}
 {section==="logs"&&<div className="cms-panel"><h2>Owner and GM activity</h2>{logError&&<p role="status">{logError}</p>}<ul className="activity-logs">{logs.map(log=><li key={log.id}><strong>{log.action.replaceAll("_"," ")}</strong><time>{new Date(log.created_at).toLocaleString()}</time><small>Actor: {log.actor_user_id??"Scheduled cleanup"}</small><pre>{JSON.stringify(log.details,null,2)}</pre></li>)}</ul>{!logs.length&&!logError&&<p>No activity recorded yet.</p>}<div className="cms-actions"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={logs.length<20} onClick={()=>setPage(p=>p+1)}>Next</button></div><h3>Offline activity on this device</h3><p className="cms-note">Device records are informational. Online database logs are the authoritative audit trail.</p><ul className="activity-logs">{localLogs.slice(0,50).map((log,i)=><li key={i}>{log.actor} · {log.action} · {log.tournament}<time>{new Date(log.at).toLocaleString()}</time></li>)}</ul></div>}
 <StaffImageEditor file={crop?.file??null} onCancel={()=>setCrop(null)} onSave={async file=>{if(!crop)return;await upload(file,crop.target);setCrop(null);}}/>
 </section>;
}
