"use client";
import {useEffect,useState} from "react";
import {Megaphone,Trophy,Coins,ScrollText,Image as ImageIcon,ShieldCheck,Clock3,GraduationCap,Gift} from "lucide-react";
import {toast} from "sonner";
import {getSupabase,PlayerProfile} from "./supabase";
import {setCmsRole} from "./cms-role-client";
import Tournaments from "./tournaments";
import {arena} from "./arena-client";
import StaffImageEditor from './staff-image-editor';
import {uploadStaffImage,validateImageFile} from "./media";
import {TIME_CONTROLS} from "./game-rules";
import {classroom} from "./classroom-client";
import {FEED_BANNERS} from "./feed-banner-catalog";
import "./classroom-cms-readable.css";
import "./cms-daily-login.css";
type Log={id:string;actor_user_id:string;actor_name?:string;action:string;details:Record<string,unknown>;created_at:string};
type Post={id:string;content:string;image_url:string;expires_at:string};
type ArenaSettings={slot1_start:string;slot1_end:string;slot2_start:string;slot2_end:string;prize_mode:'fixed'|'auto';fixed_prize_gold:number;match_control:string};
const defaultArenaSettings:ArenaSettings={slot1_start:'19:00',slot1_end:'21:00',slot2_start:'22:00',slot2_end:'00:00',prize_mode:'fixed',fixed_prize_gold:48,match_control:'5+0'};
const classroomKeys=['pawn','bishop','knight','rook','queen','king'] as const;
const classroomPackageMeta={pawn:{slots:5,time:'12 hours',symbol:'♟'},bishop:{slots:10,time:'1 day',symbol:'♝'},knight:{slots:15,time:'3 days',symbol:'♞'},rook:{slots:20,time:'5 days',symbol:'♜'},queen:{slots:30,time:'1 week',symbol:'♛'},king:{slots:40,time:'2 weeks',symbol:'♚'}} as const;
type ClassroomSettings={cbc_gold_price:number}&Record<`${typeof classroomKeys[number]}_${'cbg'|'cbc'}`,number>;
const defaultClassroomSettings={cbc_gold_price:0,...Object.fromEntries(classroomKeys.flatMap(k=>[[`${k}_cbg`,0],[`${k}_cbc`,0]]))} as ClassroomSettings;
type LoginReward={day:number;kind:"gold"|"banner"|"arena_ticket"|"bag_slot";amount:number;product_id?:string};
async function arenaCms<T>(action:string,body:Record<string,unknown>={}){const client=await getSupabase(),session=client?(await client.auth.getSession()).data.session:null;if(!session)throw Error('Sign in again.');const response=await fetch('/api/grand-arena',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...body}),cache:'no-store'}),data=await response.json() as T&{error?:string};if(!response.ok)throw Error(data.error??'Arena settings are unavailable.');return data;}
const logLabels:Record<string,string>={announcement_create:"Announcement published",announcement_update:"Announcement updated",announcement_delete:"Announcement deleted",set_app_feature:"App photo updated",grant_gold:"Gold granted",set_role:"User role changed",offline_result:"Offline result recorded",delete_user:"User deleted"};
function logSummary(log:Log){const d=log.details??{},parts:string[]=[];if(typeof d.amount==='number')parts.push(`${d.amount} Gold`);if(typeof d.username==='string')parts.push(`@${d.username}`);if(typeof d.role==='string')parts.push(`Role: ${d.role}`);if(typeof d.result==='string')parts.push(`Result: ${d.result}`);if(typeof d.expires_at==='string')parts.push(`Ends ${new Date(d.expires_at).toLocaleString()}`);if(typeof d.image_url==='string')parts.push(d.image_url?'Photo added':'Photo cleared');return parts.join(' · ')||'Completed successfully';}
export default function Cms({profile,onClose}:{profile:PlayerProfile;onClose:()=>void}){
 const[section,setSection]=useState("tournament"),[busy,setBusy]=useState(false),[text,setText]=useState(""),[image,setImage]=useState(""),[deadline,setDeadline]=useState(""),[editing,setEditing]=useState<string|null>(null),[posts,setPosts]=useState<Post[]>([]),[username,setUsername]=useState(""),[gold,setGold]=useState(10),[cardUrl,setCardUrl]=useState(""),[role,setRole]=useState("admin"),[deleteUsername,setDeleteUsername]=useState(""),[deleteConfirmation,setDeleteConfirmation]=useState(""),[logs,setLogs]=useState<Log[]>([]),[page,setPage]=useState(0),[logError,setLogError]=useState(""),[localLogs,setLocalLogs]=useState<Array<{at:string;actor:string;action:string;tournament:string}>>([]),[arenaSettings,setArenaSettings]=useState(defaultArenaSettings),[classroomSettings,setClassroomSettings]=useState(defaultClassroomSettings);
 const [featureLoaded,setFeatureLoaded]=useState(false);
 const [dailyRewards,setDailyRewards]=useState<LoginReward[]>([]),[dailyError,setDailyError]=useState("");
 const [crop,setCrop]=useState<{file:File;target:"announcement"|"card"}|null>(null);
 const owner=profile.role==="owner";
 const menu=[["tournament","Tournaments",Trophy],["announcement","Announcements",Megaphone],["card","App photo",ImageIcon],["gold","Gold",Coins],...(owner?[["arena","Grand Arena",Clock3],["classroom","Classroom",GraduationCap],["daily-login","Daily Login",Gift],["roles","Users",ShieldCheck]]:[]),["logs","Activity logs",ScrollText]] as const;
 async function run(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function loadPosts(){const data=await arena<{posts:Post[]}>("cms-announcements");setPosts(data.posts);}
 // Existing CMS tabs intentionally reset their loading/error state when the active panel changes.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(section==="card"){setFeatureLoaded(false);void arena<{image_url:string}>("app-feature",{},true).then(data=>{setCardUrl(data.image_url);setFeatureLoaded(true);}).catch(()=>toast.error("Could not load the app photo. Reopen this tab to retry."));}if(section==="announcement")void run(loadPosts);if(section==="arena"&&owner)void arenaCms<{settings:ArenaSettings}>('owner-settings').then(data=>setArenaSettings(data.settings)).catch(e=>toast.error((e as Error).message));if(section==="classroom"&&owner)void classroom<{settings:ClassroomSettings}>("state").then(data=>setClassroomSettings(data.settings)).catch(e=>toast.error((e as Error).message));if(section==="daily-login"&&owner){setDailyError("");void arena<{rewards:LoginReward[]}>("cms-daily-rewards").then(result=>setDailyRewards(result.rewards.map(reward=>({day:reward.day,kind:reward.kind,amount:reward.amount,product_id:reward.product_id||""})))).catch(e=>setDailyError((e as Error).message));}if(section==="logs"){setLogError("");void arena<{logs:Log[]}>("logs",{page}).then(data=>setLogs(data.logs)).catch(()=>setLogError("Activity logs are temporarily unavailable."));try{setLocalLogs(JSON.parse(localStorage.getItem("cb-offline-audit")??"[]"));}catch{setLocalLogs([]);}}},[section,page,owner]);
 async function publish(){
  if(!text.trim()&&!image)throw Error("Add text or an image.");
  const end=new Date(deadline);
  if(!Number.isFinite(end.getTime())||end.getTime()<=Date.now())throw Error("Choose a future end date.");
  const result=await arena<{ok?:boolean;post?:Post}>("save-announcement",{id:editing,content:text.trim(),image_url:image,expires_at:end.toISOString()});
  if(result.post){
    setPosts(current=>editing?current.map(post=>post.id===result.post!.id?result.post!:post):[result.post!,...current]);
  }else{
    await loadPosts();
  }
  setText("");setImage("");setDeadline("");setEditing(null);
  window.dispatchEvent(new Event("cb-profile-saved"));
  toast.success("Announcement published to the Community Feed.");
}
 async function upload(file:File,target:"announcement"|"card"){const url=await uploadStaffImage(file,profile.user_id);if(target==="announcement"){setImage(url);toast.success("Image uploaded. Save to publish it.");return;}setCardUrl(url);await arena("set-app-feature",{url});window.dispatchEvent(new Event("cb-app-feature-changed"));toast.success("Featured photo published beneath every User Card.");}
 if(!owner)return <p>Owner access is required.</p>;
 return <section className="cms-page"><div className="cms-heading"><div><span>OWNER CONTROL</span><h1>Chess Burger CMS</h1></div><button onClick={onClose}>Close</button></div><div className="cms-tabs">{menu.map(([key,label,Icon])=><button key={key as string} className={section===key?"active":""} onClick={()=>setSection(key as string)}><Icon/>{label as string}</button>)}</div>
 {section==="tournament"&&<Tournaments profile={profile} host/>}
 {section==="announcement"&&<div className="cms-panel announcement-cms">
  <div className="cms-panel-heading">
   <div><span>OFFICIAL UPDATE</span><h2>{editing?"Edit announcement":"Create announcement"}</h2></div>
   {editing&&<span className="cms-editing-badge">Editing active post</span>}
  </div>
  <label>Announcement text<textarea maxLength={500} value={text} onChange={e=>setText(e.target.value)} placeholder="Write the official announcement…"/></label>
  <label className="announcement-upload-control">Photo attachment<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const input=e.currentTarget,f=input.files?.[0];if(f)try{validateImageFile(f);setCrop({file:f,target:"announcement"});}catch(cause){toast.error(cause instanceof Error?cause.message:"Choose a valid photo.");input.value="";}}}/><small>{crop?.target==="announcement"?`Selected: ${crop.file.name}. Adjust and upload in the crop editor.`:image?"Photo uploaded and ready to publish.":"Choose a JPEG, PNG, or WebP. Crop it before upload (under 600 KB)."}</small></label>
  {image&&<div className="announcement-cms-preview"><img src={image} alt="Announcement preview"/><div><strong>Photo ready</strong><span>This will appear as a tappable thumbnail in the feed.</span><button type="button" disabled={busy} onClick={()=>setImage("")}>Remove photo</button></div></div>}
  <label>Display until<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label>
  <div className="cms-actions">
   <button className="gold-button" disabled={busy} onClick={()=>void run(publish)}>{busy?"Saving…":editing?"Update announcement":"Publish announcement"}</button>
   {editing&&<button type="button" disabled={busy} onClick={()=>{setEditing(null);setText("");setImage("");setDeadline("");}}>Cancel edit</button>}
  </div>
  <div className="active-announcement-heading"><div><span>LIVE</span><h3>Active announcements</h3></div><b>{posts.length}</b></div>
  <div className="cms-announcement-list">{posts.map(p=><article key={p.id} className="cms-announcement-card">{p.image_url&&<img src={p.image_url} alt=""/>}<div><p>{p.content||"Photo announcement"}</p><small>Ends {new Date(p.expires_at).toLocaleString()}</small><div className="cms-actions"><button type="button" onClick={()=>{setEditing(p.id);setText(p.content);setImage(p.image_url);const date=new Date(p.expires_at);setDeadline(new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16));window.scrollTo({top:0,behavior:"smooth"});}}>Edit</button><button type="button" disabled={busy} onClick={()=>void run(async()=>{await arena("delete-announcement",{id:p.id});await loadPosts();window.dispatchEvent(new Event("cb-profile-saved"));toast.success("Announcement removed.");})}>Delete</button></div></div></article>)}</div>
  {!posts.length&&!busy&&<p className="cms-note">No active announcements.</p>}
 </div>}
 {section==="card"&&<div className="cms-panel"><h2>App featured photo</h2><p>One announcement or advertisement displayed beneath every User Card. Only the Owner and GM Admins can replace it.</p><label>Choose replacement photo<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const input=e.currentTarget,f=input.files?.[0];input.value="";if(f)try{validateImageFile(f);void run(()=>upload(f,"card"));}catch(cause){toast.error(cause instanceof Error?cause.message:"Choose a valid photo.");}}}/></label>{busy&&<p className="cms-note" role="status">Converting to WebP and publishing…</p>}{cardUrl&&<img src={cardUrl} alt="App advertisement preview"/>}<button disabled={busy||!featureLoaded} onClick={()=>void run(async()=>{await arena("set-app-feature",{url:""});setCardUrl("");window.dispatchEvent(new Event("cb-app-feature-changed"));toast.success("Featured photo removed.");})}>Remove featured photo</button><p className="cms-note">Choose a JPG, PNG or WebP file. It is automatically converted below 600 KB, published immediately, and displayed beneath every User Card.</p></div>}
 {section==="gold"&&<div className="cms-panel"><h2>Grant Gold</h2><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username"/></label><label>Gold amount<input type="number" min={1} max={10000} value={gold} onChange={e=>setGold(Number(e.target.value))}/></label><button disabled={busy||!username.trim()} onClick={()=>void run(async()=>{if(!Number.isInteger(gold)||gold<1||gold>10000)throw Error("Enter 1–10,000 Gold.");await arena("grant-gold",{username,amount:gold,request_id:crypto.randomUUID()});toast.success("Gold granted and logged.");})}>Grant Gold</button></div>}
 {section==="arena"&&owner&&<div className="cms-panel arena-cms-panel"><div><span>OWNER CONTROL</span><h2>Grand Arena</h2><p className="cms-note">Times use Philippine time. Updated schedules and match controls apply to newly created sessions.</p></div><div className="arena-cms-times"><fieldset><legend>Session 1</legend><label>Starts<input type="time" value={arenaSettings.slot1_start.slice(0,5)} onChange={e=>setArenaSettings(v=>({...v,slot1_start:e.target.value}))}/></label><label>Ends<input type="time" value={arenaSettings.slot1_end.slice(0,5)} onChange={e=>setArenaSettings(v=>({...v,slot1_end:e.target.value}))}/></label></fieldset><fieldset><legend>Session 2</legend><label>Starts<input type="time" value={arenaSettings.slot2_start.slice(0,5)} onChange={e=>setArenaSettings(v=>({...v,slot2_start:e.target.value}))}/></label><label>Ends<input type="time" value={arenaSettings.slot2_end.slice(0,5)} onChange={e=>setArenaSettings(v=>({...v,slot2_end:e.target.value}))}/></label></fieldset></div><label>Arena match time control<select value={arenaSettings.match_control} onChange={e=>setArenaSettings(v=>({...v,match_control:e.target.value}))}>{TIME_CONTROLS.map(control=><option key={control.id} value={control.id}>{control.group} · {control.label}</option>)}</select></label><label>Champion Gold prize<select value={arenaSettings.prize_mode} onChange={e=>setArenaSettings(v=>({...v,prize_mode:e.target.value as 'fixed'|'auto'}))}><option value="fixed">Owner-set fixed prize</option><option value="auto">Auto · 10% of tickets used</option></select></label>{arenaSettings.prize_mode==='fixed'&&<label>Fixed Gold prize<input type="number" min={0} max={1000000} value={arenaSettings.fixed_prize_gold} onChange={e=>setArenaSettings(v=>({...v,fixed_prize_gold:Number(e.target.value)}))}/></label>}<div className="arena-cms-rules"><b>Scoring now active</b><span>Win +1 · Draw +0.5 · Three consecutive wins +2 bonus</span><span>Two losses eliminate · Each win grants +4 CBR</span><span>Pairing prioritizes the nearest Arena points.</span></div><button disabled={busy} onClick={()=>void run(async()=>{const data=await arenaCms<{settings:ArenaSettings}>('save-owner-settings',{settings:arenaSettings});setArenaSettings(data.settings);toast.success('Grand Arena controls saved.');})}>{busy?'Saving…':'Save Arena controls'}</button></div>}
 {section==="daily-login"&&owner&&<div className="cms-panel cms-daily-login"><header><small>OWNER SETTINGS</small><h2>Daily Login rewards</h2><p>Set the 7-day reward cycle. New claims use the updated rewards; existing claims stay recorded.</p></header>{dailyError&&<p role="alert" className="cms-daily-error">{dailyError}</p>}{dailyRewards.length===7?<><div className="cms-daily-grid">{dailyRewards.map((reward,index)=><fieldset key={reward.day}><legend>Day {reward.day}</legend><label>Reward type<select value={reward.kind} onChange={e=>{const kind=e.target.value as LoginReward["kind"];setDailyRewards(current=>current.map((item,i)=>i===index?{...item,kind,amount:kind==="banner"?3:kind==="gold"?10:1,product_id:kind==="banner"?FEED_BANNERS[0].id:""}:item))}}><option value="gold">Gold</option><option value="banner">Feed banner</option><option value="arena_ticket">Arena tickets</option><option value="bag_slot">Bag slots</option></select></label><label>{reward.kind==="banner"?"Rental days":"Amount"}<input type="number" min={1} max={10000} value={reward.amount} onChange={e=>setDailyRewards(current=>current.map((item,i)=>i===index?{...item,amount:Number(e.target.value)}:item))}/></label>{reward.kind==="banner"&&<label>Banner color<select value={reward.product_id||""} onChange={e=>setDailyRewards(current=>current.map((item,i)=>i===index?{...item,product_id:e.target.value}:item))}>{FEED_BANNERS.map(banner=><option key={banner.id} value={banner.id}>{banner.name} · {banner.tier}</option>)}</select></label>}</fieldset>)}</div><button className="gold-button" disabled={busy} onClick={()=>void run(async()=>{const result=await arena<{rewards:LoginReward[]}>("save-daily-rewards",{rewards:dailyRewards});setDailyRewards(result.rewards.map(reward=>({...reward,product_id:reward.product_id||""})));toast.success("Daily Login rewards saved.")})}>{busy?"Saving…":"Save Daily Login rewards"}</button></>:!dailyError&&<p role="status">Loading Daily Login settings…</p>}</div>}
 {section==="classroom"&&owner&&<div className="cms-panel classroom-cms-panel"><header className="classroom-cms-hero"><div><small>OWNER CLASSROOM CONTROL</small><h2>Classroom Economy</h2><p>Control CBC value and every teaching-room package from one branded dashboard.</p></div><img src="/classroom/cbc-token.webp" alt="CBC token"/></header><section className="cbc-master-rate"><div className="cbc-master-icon"><img src="/classroom/cbc-token.webp" alt=""/><span><small>GLOBAL TOKEN RATE</small><strong>CBC Selling Price</strong><p>CBG charged for every CBC purchased in Shop.</p></span></div><label><span>1 CBC costs</span><div><input type="number" min={0} max={1000000} value={classroomSettings.cbc_gold_price} onChange={e=>setClassroomSettings(v=>({...v,cbc_gold_price:Number(e.target.value)}))}/><b>CBG</b></div></label></section><div className="classroom-cms-section-title"><span>ROOM PACKAGE CATALOG</span><h3>Set package price and teacher CBC bundle</h3></div><div className="classroom-cms-grid">{classroomKeys.map(kind=>{const meta=classroomPackageMeta[kind];return <fieldset key={kind}><legend><i>{meta.symbol}</i><span><small>{meta.slots} STUDENTS · {meta.time}</small><strong>Room {kind[0].toUpperCase()+kind.slice(1)}</strong></span></legend><div className="classroom-price-fields"><label><span>Sale price</span><div><input type="number" min={0} max={1000000} value={classroomSettings[`${kind}_cbg`]} onChange={e=>setClassroomSettings(v=>({...v,[`${kind}_cbg`]:Number(e.target.value)}))}/><b>CBG</b></div></label><label><span>Teacher receives</span><div><input type="number" min={0} max={1000000} value={classroomSettings[`${kind}_cbc`]} onChange={e=>setClassroomSettings(v=>({...v,[`${kind}_cbc`]:Number(e.target.value)}))}/><b>CBC</b></div></label></div><p>After purchase, the CBC bundle goes directly to the teacher’s My Bag.</p></fieldset>})}</div><div className="classroom-cms-savebar"><span><b>Changes apply to new purchases</b><small>Existing rooms and balances remain unchanged.</small></span><button disabled={busy} onClick={()=>void run(async()=>{const data=await classroom<{settings:ClassroomSettings}>("save-settings",classroomSettings);setClassroomSettings(data.settings);toast.success("Classroom prices saved.")})}>{busy?"Saving…":"Save Classroom Pricing"}</button></div></div>}
 {section==="roles"&&owner&&<div className="cms-panel"><h2>Manage users</h2><p className="cms-note">Owners have full CMS access. GM/Admins have staff tools. Players have normal access.</p><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username"/></label><label>Access level<select value={role} onChange={e=>setRole(e.target.value)}><option value="owner">Owner</option><option value="admin">GM / Admin</option><option value="player">Player</option></select></label><button disabled={busy||!username.trim()} onClick={()=>void run(async()=>{await setCmsRole(username,role as "owner"|"admin"|"player");toast.success("Access level updated and logged.");})}>Save access level</button><div className="cms-danger-zone"><h3>Delete user</h3><p className="cms-note">Removes the player profile and app data. Owner accounts are protected.</p><label>Username<input value={deleteUsername} onChange={e=>{setDeleteUsername(e.target.value);setDeleteConfirmation("");}} placeholder="@username"/></label><label>Type the username again<input value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} placeholder={deleteUsername||"Confirm username"}/></label><button className="cms-delete-user" disabled={busy||!deleteUsername.trim()||deleteConfirmation.replace(/^@+/,"").toLowerCase()!==deleteUsername.replace(/^@+/,"").toLowerCase()} onClick={()=>void run(async()=>{const clean=deleteUsername.replace(/^@+/,"").trim();if(!window.confirm(`Permanently delete @${clean} from Chess Burger?`))return;await arena("delete-user",{username:clean,confirmation:deleteConfirmation});setDeleteUsername("");setDeleteConfirmation("");toast.success(`@${clean} was deleted.`);})}>Delete user permanently</button></div></div>}
 {section==="logs"&&<div className="cms-panel logs-panel"><div><h2>Owner and GM activity</h2><p className="cms-note">Latest staff changes, newest first.</p></div>{logError&&<p role="status">{logError}</p>}<ul className="activity-logs">{logs.map(log=><li key={log.id}><span className="log-icon" aria-hidden="true">{log.action.includes('announcement')?'📣':log.action.includes('gold')?'●':log.action.includes('role')?'♟':'✓'}</span><span className="log-copy"><strong>{logLabels[log.action]??log.action.replaceAll("_"," ")}</strong><small>{logSummary(log)}</small><span>{log.actor_name??(log.actor_user_id?`Staff …${log.actor_user_id.slice(-6)}`:"System")} · <time>{new Date(log.created_at).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></span></span></li>)}</ul>{!logs.length&&!logError&&<p>No activity recorded yet.</p>}<div className="cms-actions log-pagination"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={logs.length<20} onClick={()=>setPage(p=>p+1)}>Next</button></div><details className="offline-log-section"><summary>Offline activity on this device</summary><p className="cms-note">Informational device records only.</p><ul className="activity-logs">{localLogs.slice(0,50).map((log,i)=><li key={i}><span className="log-icon">✓</span><span className="log-copy"><strong>{log.action}</strong><small>{log.actor} · {log.tournament}</small><time>{new Date(log.at).toLocaleString()}</time></span></li>)}</ul></details></div>}
 <StaffImageEditor file={crop?.file??null} onCancel={()=>setCrop(null)} onSave={async file=>{if(!crop)return;await upload(file,crop.target);setCrop(null);}}/>
 </section>;
}
