'use client';
import {useEffect,useRef,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {Wifi,Copy,UsersRound,Globe2} from 'lucide-react';
import {LanConnection,decodeSignal} from './lan-connection';
import {arena} from './arena-client';
import type {ArenaMatch,ArenaPlayer} from './game-rules';
import {getSupabase,type PlayerProfile} from './supabase';
import type {RealtimeChannel} from '@supabase/supabase-js';
import TimePicker from './time-picker';
import MatchBoard from './match-board';
import QrInput from './qr-input';
export default function LocalPairing({profile,startSameDevice,startOnlineMatch,onResult}:{profile:PlayerProfile|null;startSameDevice:(control:string)=>void;startOnlineMatch:(id:string)=>void;onResult:(m:ArenaMatch,ownId:string)=>void}){
 const [control,setControl]=useState('10+0'),[role,setRole]=useState<'host'|'guest'|null>(null),[code,setCode]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[match,setMatch]=useState<ArenaMatch|null>(null),[error,setError]=useState(''),[own,setOwn]=useState<ArenaPlayer|null>(null),[,setConnectionRevision]=useState(0);
 const [internetCode,setInternetCode]=useState(''),[internetRoom,setInternetRoom]=useState<ArenaMatch|null>(null),[internetBusy,setInternetBusy]=useState(false);
 const connection=useRef<LanConnection|null>(null),signalChannel=useRef<RealtimeChannel|null>(null),completed=useRef(false),internetMatchCallback=useRef(startOnlineMatch);internetMatchCallback.current=startOnlineMatch;
 useEffect(()=>{const p=profile??{display_name:'Local Player',username:'local_player',cbr:88,avatar_url:'',country_code:'PH',gold_points:0,wins:0,losses:0,win_streak:0};let id=profile?.user_id;if(!id||id==='guest-device'){id=localStorage.getItem('cb-device-id')??crypto.randomUUID();localStorage.setItem('cb-device-id',id);}setOwn({user_id:id,display_name:p.display_name,username:p.username,avatar_url:p.avatar_url,country_code:p.country_code,cbr:p.cbr,gold_points:0,wins:p.wins,losses:p.losses,win_streak:p.win_streak});return()=>{connection.current?.close();void signalChannel.current?.unsubscribe();};},[]);
 function receive(m:ArenaMatch){setMatch(m);if(m.status==='finished'&&!completed.current){completed.current=true;onResult(m,own?.user_id??connection.current!.own.user_id);}}
 const connectionStatus=(message:string)=>{setStatus(message);setConnectionRevision(value=>value+1);if(message.startsWith('Connected'))closeSignal();};
 const closeSignal=()=>{void signalChannel.current?.unsubscribe();signalChannel.current=null;};
 const subscribe=(channel:RealtimeChannel)=>new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Pairing service timed out. Check the internet connection on both devices.')),10000);channel.subscribe(state=>{if(state==='SUBSCRIBED'){clearTimeout(timer);resolve();}else if(state==='CHANNEL_ERROR'||state==='TIMED_OUT'){clearTimeout(timer);reject(Error('Could not connect to the QR pairing service.'));}});});
 function chooseGuest(){connection.current?.close();connection.current=null;closeSignal();setRole('guest');setCode('');setMatch(null);setError('');setStatus('Join mode selected. Scan the host QR.');}
 async function create(){if(!own)return;setBusy(true);setError('');try{if(!navigator.onLine)throw Error('One-scan QR pairing needs internet briefly on both devices.');if(!('RTCPeerConnection' in window))throw Error('This browser does not support local device pairing. Use the shared board below.');connection.current?.close();closeSignal();const client=await getSupabase();if(!client)throw Error('QR pairing service is unavailable. Reload the app and try again.');const link=new LanConnection(true,own,control,receive,connectionStatus);connection.current=link;const channel=client.channel('offline-pair:'+link.room,{config:{broadcast:{self:false}}});channel.on('broadcast',{event:'guest-answer'},async({payload})=>{try{if(payload?.room!==link.room||typeof payload?.answer!=='string')return;await link.finish(await decodeSignal(payload.answer));connectionStatus('Joiner found. Establishing the direct connection…');}catch(e){setError((e as Error).message);}});await subscribe(channel);signalChannel.current=channel;setRole('host');setCode(await link.offer());setStatus('Host QR ready. Ask the joiner to scan it.');}catch(e){setError((e as Error).message);connection.current?.close();connection.current=null;closeSignal();}finally{setBusy(false);}}
 async function scan(value:string){if(!own)return;setBusy(true);setError('');try{if(!navigator.onLine)throw Error('One-scan QR pairing needs internet briefly on both devices.');const signal=await decodeSignal(value);if(signal.description.type!=='offer')throw Error('Scan the host QR, not another reply code.');connection.current?.close();closeSignal();const client=await getSupabase();if(!client)throw Error('QR pairing service is unavailable. Reload the app and try again.');const link=new LanConnection(false,own,control,receive,connectionStatus,signal.room);connection.current=link;setRole('guest');setCode('');const answer=await link.answer(signal),channel=client.channel('offline-pair:'+signal.room,{config:{broadcast:{self:false}}});await subscribe(channel);signalChannel.current=channel;const sent=await channel.send({type:'broadcast',event:'guest-answer',payload:{room:signal.room,answer}});if(sent!=='ok')throw Error('The connection answer was not delivered. Please scan the host QR again.');setStatus('Host notified. Establishing the direct connection…');}catch(e){setError((e as Error).message);connection.current?.close();connection.current=null;closeSignal();}finally{setBusy(false);}}
 async function createInternet(){setInternetBusy(true);setError('');try{const data=await arena<{match:ArenaMatch}>('room',{control});setInternetRoom(data.match);setInternetCode(data.match.code);setStatus('Internet room ready. Share the 8-character code.');}catch(e){setError((e as Error).message);}finally{setInternetBusy(false);}}
 async function joinInternet(){const entered=internetCode.trim().toUpperCase();if(!/^[A-Z0-9]{8}$/.test(entered)){setError('Enter the complete 8-character internet code.');return;}setInternetBusy(true);setError('');try{const data=await arena<{match:ArenaMatch}>('join',{code:entered});internetMatchCallback.current(data.match.id);}catch(e){setError((e as Error).message);}finally{setInternetBusy(false);}}
 useEffect(()=>{if(!internetRoom)return;let active=true,pending=false;const poll=async()=>{if(pending)return;pending=true;try{const data=await arena<{match:ArenaMatch}>('match',{id:internetRoom.id});if(active&&data.match.status==='active')internetMatchCallback.current(data.match.id);else if(active&&data.match.status==='cancelled')setInternetRoom(null);}catch{}finally{pending=false;}};void poll();const timer=setInterval(poll,1500);return()=>{active=false;clearInterval(timer);};},[internetRoom?.id]);
 if(match)return <><MatchBoard match={match} ownId={own?.user_id} onMove={m=>connection.current?.action(m)} onResign={()=>connection.current?.action(undefined,true)} connection={status}/>{match.status==='finished'&&<p className="account-note">Offline result and replay saved on this device.</p>}</>;
 const localLink=connection.current,connected=localLink?.channel?.readyState==='open',guestCanReady=role==='guest'&&connected&&!localLink?.match,hostCanStart=role==='host'&&!!localLink?.guestReady&&!localLink?.match,opponent=role==='host'?localLink?.guest:localLink?.peer;
 const avatar=(player:ArenaPlayer|null|undefined,label:string)=><article className={"pairing-player"+(player?" connected":"")}><span className="pairing-avatar">{player?.avatar_url?<img src={player.avatar_url} alt=""/>:(player?.display_name??"?").charAt(0)}</span><div><small>{label}</small><strong>{player?.display_name??"Waiting…"}</strong><span>{player?connected?"Connected":"Pairing…":"Not connected"}</span></div></article>;
 return <section className="local-pairing">
  <div className="page-heading"><h1>Offline Board</h1><Wifi size={22}/></div>
  <p className="page-caption">One-scan QR pairing uses internet briefly to connect the two devices. The chess game then runs directly between them.</p>
  <div className="cloud-panel"><TimePicker value={control} onChange={setControl} disabled={!!code||busy||!!internetRoom||internetBusy}/></div>
  <section className="cloud-panel internet-pairing"><div className="internet-pairing-title"><Globe2/><div><h2>Pair with internet code</h2><p>Enter the same 8-character room code on another phone or PC.</p></div></div>{internetRoom?<><strong className="internet-room-code">{internetRoom.code}</strong><button onClick={()=>void navigator.clipboard.writeText(internetRoom.code).catch(()=>setError('Copy the displayed code manually.'))}><Copy size={15}/>Copy code</button><p className="rules-caption">Waiting for the other player… This code expires after 2 minutes.</p></>:<div className="internet-code-actions"><button className="gold-button" disabled={internetBusy||!profile||profile.user_id==='guest-device'} onClick={()=>void createInternet()}>{internetBusy?'Please wait…':'Create 8-character code'}</button><span>or</span><input aria-label="Eight-character internet room code" inputMode="text" autoCapitalize="characters" maxLength={8} placeholder="AB12CD34" value={internetCode} onChange={e=>setInternetCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))}/><button disabled={internetBusy||internetCode.length!==8} onClick={()=>void joinInternet()}>Join</button></div>}<p className="rules-caption">Registered players only. Internet is required for this option.</p></section>
  <div className="pairing-divider"><span>One-scan QR pairing</span></div>
  <div className="offline-role-actions" role="group" aria-label="Choose offline pairing role"><button className="gold-button" aria-pressed={role==='host'} disabled={busy} onClick={()=>void create()}>Host game</button><button aria-pressed={role==='guest'} disabled={busy} onClick={chooseGuest}>Join game</button></div>
  <p className="pairing-role-note">{role==='host'?'Host: keep this page open and show the QR to the joiner.':role==='guest'?'Joiner: scan the host QR once. Your connection answer is sent automatically.':'Choose Host on one device and Join on the other device.'}</p>
  {role&&<div className="pairing-players">{avatar(own,role==='host'?'Host · You':'Joiner · You')}{avatar(opponent,role==='host'?'Joiner':'Host')}</div>}
  {role==='host'&&<div className="cloud-panel one-scan-panel"><h2>Host QR</h2>{code?<><div className="local-qr">{code.length<=2300?<QRCodeSVG value={code} size={230} level="L" marginSize={3}/>:<p className="inline-error">This connection code is too large for QR. Generate it again.</p>}</div><p>Ask the joiner to select Join game and scan this QR once.</p></>:<p>{busy?'Creating the secure QR…':'Select Host game to generate the QR.'}</p>}</div>}
  {role==='guest'&&<div className="cloud-panel one-scan-panel"><h2>{connected?'Host connected':'Scan host QR'}</h2>{!connected&&<QrInput label="Scan host QR" onValue={value=>void scan(value)}/>}<p>{connected?'The host is connected. Press Ready to play.':'The host will be notified automatically after a successful scan.'}</p></div>}
  {status&&<p className="connection-label" role="status">{status}</p>}
  {guestCanReady&&<button className="gold-button pairing-ready" onClick={()=>connection.current?.ready()}>Ready to play</button>}
  {hostCanStart&&<button className="gold-button pairing-ready" onClick={()=>connection.current?.start()}>Start game</button>}
  {error&&<p className="inline-error" role="alert">{error}</p>}
  <div className="cloud-panel shared-board-option"><UsersRound/><div><h2>One screen, two players</h2><p>Play together on this device.</p></div><button onClick={()=>startSameDevice(control)}>Open board</button></div>
  <p className="rules-caption">QR pairing needs internet only during connection setup. OCBR: winner +6, loser −9. Online CBR is never affected.</p>
 </section>;
}
