'use client';
import {useEffect,useRef,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {Wifi,Copy,UsersRound} from 'lucide-react';
import {LanConnection,decodeSignal} from './lan-connection';
import type {ArenaMatch,ArenaPlayer} from './game-rules';
import type {PlayerProfile} from './supabase';
import TimePicker from './time-picker';
import MatchBoard from './match-board';
import QrInput from './qr-input';
export default function LocalPairing({profile,startSameDevice,onResult}:{profile:PlayerProfile|null;startSameDevice:(control:string)=>void;onResult:(m:ArenaMatch,ownId:string)=>void}){
 const [control,setControl]=useState('10+0'),[host,setHost]=useState(false),[code,setCode]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[match,setMatch]=useState<ArenaMatch|null>(null),[error,setError]=useState(''),[own,setOwn]=useState<ArenaPlayer|null>(null);
 const connection=useRef<LanConnection|null>(null),completed=useRef(false);
 useEffect(()=>{const p=profile??{display_name:'Local Player',username:'local_player',cbr:88,avatar_url:'',country_code:'PH',gold_points:0,wins:0,losses:0,win_streak:0};let id=profile?.user_id;if(!id||id==='guest-device'){id=localStorage.getItem('cb-device-id')??crypto.randomUUID();localStorage.setItem('cb-device-id',id);}setOwn({user_id:id,display_name:p.display_name,username:p.username,avatar_url:'',country_code:p.country_code,cbr:p.cbr,gold_points:0,wins:p.wins,losses:p.losses,win_streak:p.win_streak});return()=>connection.current?.close();},[]);
 function receive(m:ArenaMatch){setMatch(m);if(m.status==='finished'&&!completed.current){completed.current=true;onResult(m,own?.user_id??connection.current!.own.user_id);}}
 async function create(){if(!own)return;setBusy(true);setError('');try{if(!('RTCPeerConnection' in window))throw Error('This browser does not support local device pairing. Use the shared board below.');connection.current?.close();const link=new LanConnection(true,own,control,receive,setStatus);connection.current=link;setHost(true);setCode(await link.offer());setStatus('Host QR ready. Ask the other player to scan it.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function scan(value:string){if(!own)return;setBusy(true);setError('');try{const signal=await decodeSignal(value);if(host&&connection.current){await connection.current.finish(signal);setStatus('Connecting both boards…');}else{connection.current?.close();const link=new LanConnection(false,own,control,receive,setStatus,signal.room);connection.current=link;setHost(false);setCode(await link.answer(signal));setStatus('Show this reply QR to the host to complete pairing.');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(match)return <><MatchBoard match={match} ownId={own?.user_id} onMove={m=>connection.current?.action(m)} onResign={()=>connection.current?.action(undefined,true)} connection={status}/>{match.status==='finished'&&<p className="account-note">Offline result and replay saved on this device.</p>}</>;
 return <section className="local-pairing"><div className="page-heading"><h1>Offline Board</h1><Wifi size={22}/></div><p className="page-caption">Connect both phones to the same Wi-Fi router or hotspot.</p><div className="cloud-panel"><TimePicker value={control} onChange={setControl} disabled={!!code||busy}/></div><div className="lobby-pair-grid"><div className="cloud-panel"><h2>{host?'Host QR':'Create a board'}</h2>{code?<><div className="local-qr">{code.length<=2300?<QRCodeSVG value={code} size={230} level="L" marginSize={3}/>:<p>Use the full pairing code below.</p>}</div><p>{host?'1. Guest scans this QR. 2. Host scans the guest’s reply.':'Reply QR · host scans this to connect.'}</p><button onClick={()=>void navigator.clipboard.writeText(code).catch(()=>setError('Select and copy the pairing text below.'))}><Copy size={15}/>Copy pairing code</button><details><summary>Full offline pairing code</summary><textarea readOnly value={code}/></details></>:<><p>You choose the time control and play White.</p><button className="gold-button" disabled={busy||!own} onClick={()=>void create()}>{busy?'Preparing…':'Generate QR & code'}</button></>}</div><div className="cloud-panel"><h2>{host?'Scan guest reply':'Join a board'}</h2><QrInput label={host?'Scan reply QR':'Scan host QR'} onValue={v=>void scan(v)}/><p className="rules-caption">Without internet, the full pairing code carries the connection details. A short room number alone cannot discover another phone.</p></div></div>{status&&<p className="connection-label" role="status">{status}</p>}{error&&<p className="inline-error" role="alert">{error}</p>}<div className="cloud-panel shared-board-option"><UsersRound/><div><h2>One screen, two players</h2><p>Play together on this device.</p></div><button onClick={()=>startSameDevice(control)}>Open board</button></div><p className="rules-caption">Local pairing needs a hotspot that allows devices to communicate. Bluetooth-only pairing requires a native app and is not available in this PWA.</p></section>;
}
