'use client';

import {Component,Fragment,useEffect,useRef,useState,type ErrorInfo,type ReactNode} from 'react';
import L,{type Map as LeafletMap,type LayerGroup as LeafletLayerGroup} from 'leaflet';
import {Crown,Flag,FlagTriangleRight,LocateFixed,MapPin,MapPinned,Satellite,Shield,Swords,Users,X} from 'lucide-react';
import {arena} from './arena-client';
import {TIME_CONTROLS,type ArenaMatch,type ArenaPlayer} from './game-rules';
import type {Position} from './gps-presence';
import {Avatar} from './match-board';
import {mapPlayerCard} from './map-player-card';
import {mapCoordinates,normalizeNearby,type NearbyPlayer,type Zone} from './map-data';

type TerritoryScope='barangay'|'city';
type Leaders={scope:TerritoryScope;label:string;players:ArenaPlayer[]};
type MapStats={online_users:number;registered_users:number;active_matches:number;gps_online:number;highest_online:{user_id:string;display_name:string;cbr:number}|null;updated_at:string};
type Props={enabled:boolean;position:Position|null;toggle:()=>void;error:string;onInvite:(p:ArenaPlayer)=>void;onOpenProfile:(userId:string)=>void;territory?:boolean;onClaimed:()=>void};

class MapBoundary extends Component<{children:ReactNode},{failed:boolean;attempt:number}>{
 state={failed:false,attempt:0};
 static getDerivedStateFromError(){return {failed:true};}
 componentDidCatch(error:Error,info:ErrorInfo){console.error('map.render-failed',{message:error.message,componentStack:info.componentStack});}
 render(){return this.state.failed?<section className="cloud-panel" role="alert"><h1>Map could not load</h1><p>You can retry or use the navigation below. Retrying does not claim or rename a kingdom.</p><button className="gold-button" onClick={()=>this.setState(state=>({failed:false,attempt:state.attempt+1}))}>Retry Map</button></section>:<Fragment key={this.state.attempt}>{this.props.children}</Fragment>;}
}
export default function NearbyMap(props:Props){return <MapBoundary><NearbyMapContent {...props}/></MapBoundary>;}

function NearbyMapContent({enabled,position,toggle,error:gpsError,onInvite,onOpenProfile,territory=true,onClaimed}:Props){
 const node=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),layer=useRef<LeafletLayerGroup|null>(null),centered=useRef(false),visiblePlayers=useRef(''),hoverCard=useRef<HTMLDivElement>(null);
 const [players,setPlayers]=useState<NearbyPlayer[]>([]),[zones,setZones]=useState<Zone[]>([]),[selected,setSelected]=useState<NearbyPlayer|null>(null),[hovered,setHovered]=useState<NearbyPlayer|null>(null);
 const [selectedZone,setSelectedZone]=useState<Zone|null>(null),[control,setControl]=useState('10+0'),[challengeStatus,setChallengeStatus]=useState(''),[kingdomName,setKingdomName]=useState(''),[renameName,setRenameName]=useState('');
 const [error,setError]=useState(''),[mapError,setMapError]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[leaders,setLeaders]=useState<Leaders|null>(null),[leaderBusy,setLeaderBusy]=useState(false),[stats,setStats]=useState<MapStats|null>(null),[statsError,setStatsError]=useState('');
 const [territoryDataReady,setTerritoryDataReady]=useState(false);
 const hasPosition=!!position&&!!mapCoordinates(position.lat,position.lng);

 useEffect(()=>{
  if(!node.current)return;
  let disposed=false,fallback=false,frame:number|undefined,instance:LeafletMap|undefined;
  try{
   instance=L.map(node.current,{zoomControl:true}).setView([11.244,125.003],14);
   const primary=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19});
   primary.on('tileerror',()=>{if(disposed||fallback||!instance)return;fallback=true;primary.remove();L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO',subdomains:'abcd',maxZoom:20}).addTo(instance);setMapError('');});
   primary.addTo(instance);layer.current=L.layerGroup().addTo(instance);map.current=instance;
   frame=requestAnimationFrame(()=>{if(disposed||!instance)return;instance.invalidateSize();setReady(true);});
  }catch(error){console.error('map.initialization-failed',error);setMapError('The map could not load. Leave Map and open it again to retry.');}
  return()=>{disposed=true;if(frame!==undefined)cancelAnimationFrame(frame);instance?.remove();if(map.current===instance){map.current=null;layer.current=null;}centered.current=false;};
 },[]);
 useEffect(()=>{let alive=true,pending=false;const load=async()=>{if(pending||!navigator.onLine)return;pending=true;try{const data=await arena<MapStats>('map-stats');if(alive){setStats(data);setStatsError('');}}catch{if(alive)setStatsError('Live activity is temporarily unavailable.');}finally{pending=false;}};void load();const timer=setInterval(load,10000);window.addEventListener('online',load);return()=>{alive=false;clearInterval(timer);window.removeEventListener('online',load);};},[]);
 useEffect(()=>{if(!enabled||!hasPosition){visiblePlayers.current='';centered.current=false;setPlayers([]);setZones([]);setSelected(null);setHovered(null);setSelectedZone(null);setTerritoryDataReady(false);return;}let alive=true,pending=false;const load=async()=>{if(pending)return;pending=true;try{const data=normalizeNearby(await arena<unknown>('nearby'));if(alive){setPlayers(data.players);setSelected(old=>old?data.players.find(p=>p.user_id===old.user_id)??null:null);setHovered(old=>old?data.players.find(p=>p.user_id===old.user_id)??null:null);setZones(data.territories);setSelectedZone(old=>old?data.territories.find(z=>z.id===old.id)??null:null);setTerritoryDataReady(data.territoriesComplete);setError(data.territoriesComplete?'':'Some kingdom records could not be displayed. Claiming is paused until they reload.');}}catch(e){if(alive){setTerritoryDataReady(false);setError((e as Error).message);}}finally{pending=false;}};void load();const timer=setInterval(load,2000);return()=>{alive=false;clearInterval(timer);};},[enabled,hasPosition]);
 useEffect(()=>{if(!hoverCard.current)return;hoverCard.current.replaceChildren();if(hovered)hoverCard.current.append(mapPlayerCard(hovered));},[hovered]);
 useEffect(()=>{setRenameName(selectedZone?.is_owner?selectedZone.kingdom_name:'');},[selectedZone?.id,selectedZone?.kingdom_name,selectedZone?.is_owner]);

 useEffect(()=>{if(!ready||!map.current||!layer.current)return;layer.current.clearLayers();const location=position?mapCoordinates(position.lat,position.lng):null;if(location&&enabled){if(!centered.current){map.current.setView([location.lat,location.lng],16);centered.current=true;}L.circleMarker([location.lat,location.lng],{radius:8,color:'#157b90',weight:3,fillColor:'#64e1ec',fillOpacity:1}).bindTooltip('You').addTo(layer.current);}
  for(const p of players){const el=document.createElement('div');el.className='map-avatar';el.textContent=p.display_name.slice(0,1).toUpperCase();if(p.avatar_url){const img=document.createElement('img');img.src=p.avatar_url;img.alt=p.display_name;img.loading='eager';img.decoding='async';img.referrerPolicy='no-referrer';Object.assign(img.style,{display:'block',position:'absolute',inset:'0',width:'100%',height:'100%',maxWidth:'none',objectFit:'cover',opacity:'1',zIndex:'2'});img.onerror=()=>img.remove();el.appendChild(img);}el.setAttribute('aria-label',p.display_name+' · invite to match');const marker=L.marker([p.lat,p.lng],{icon:L.divIcon({html:'',className:'map-player-pin',iconSize:[40,40],iconAnchor:[20,20]})}).on('mouseover',()=>setHovered(p)).on('mouseout',()=>setHovered(current=>current?.user_id===p.user_id?null:current)).on('click',()=>setSelected(p)).addTo(layer.current);marker.getElement()?.replaceChildren(el);}
  for(const zone of zones){const polygon=L.geoJSON(zone.boundary as never,{style:{color:'#28dff1',weight:3,opacity:.9,fillColor:zone.online?'#27bd78':'#737c84',fillOpacity:.16}}).on('click',()=>{setSelectedZone(zone);setChallengeStatus('');}).addTo(layer.current);polygon.bindTooltip(`${zone.barangay} · ${zone.defense_points??'—'} defense`);const pin=document.createElement('button');pin.type='button';pin.className=`territory-king-pin ${zone.online?'online':'offline'}`;pin.setAttribute('aria-label',`${zone.display_name}, KING of ${zone.barangay}, ${zone.defense_points??'—'} defense points`);const flag=document.createElement('span');flag.className='king-flag';flag.textContent='⚑';const badge=document.createElement('b');badge.textContent='KING';pin.append(flag,badge);const marker=L.marker([zone.centroid_lat,zone.centroid_lng],{icon:L.divIcon({html:'',className:'territory-king-marker',iconSize:[64,58],iconAnchor:[32,52]})}).on('click',()=>{setSelectedZone(zone);setChallengeStatus('');}).addTo(layer.current);marker.getElement()?.replaceChildren(pin);}
  if(location&&players.length){const signature=players.map(p=>`${p.user_id}:${p.lat.toFixed(4)}:${p.lng.toFixed(4)}`).join('|');if(signature!==visiblePlayers.current){visiblePlayers.current=signature;map.current.fitBounds(L.latLngBounds([[location.lat,location.lng],...players.map(p=>[p.lat,p.lng] as [number,number])]),{padding:[42,42],maxZoom:15,animate:true});}}
 },[ready,position,enabled,players,zones]);

 async function reloadZones(){const data=normalizeNearby(await arena<unknown>('nearby'));setZones(data.territories);return data.territories;}
 async function syncCurrentGps(){if(!position)throw new Error('Waiting for a current GPS reading.');await arena('presence',{gps:true,...position});}
 async function claim(){if(!territoryDataReady)return;setBusy(true);setError('');try{await syncCurrentGps();const result=await arena<{claimed:boolean;defense_points:number}>('claim',{kingdom_name:kingdomName,...position!});onClaimed();const current=await reloadZones();setSelectedZone(current[0]??null);setChallengeStatus(result.claimed?`${kingdomName.trim()} was claimed with ${result.defense_points} defense points.`:'Your kingdom territory was restored.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function renameKingdom(zone:Zone){setBusy(true);setError('');setChallengeStatus('');try{const result=await arena<{territory:{id:string;kingdom_name:string}}>('territory-name',{territory_id:zone.id,kingdom_name:renameName});const current=await reloadZones();const updated=current.find(item=>item.id===result.territory.id)??null;setSelectedZone(updated);setChallengeStatus(`Your kingdom is now named ${result.territory.kingdom_name}.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function relocateKingdom(zone:Zone){setBusy(true);setError('');setChallengeStatus('');try{await syncCurrentGps();await arena('territory-relocate',{territory_id:zone.id,...position!});const current=await reloadZones();setSelectedZone(current.find(item=>item.id===zone.id)??null);setChallengeStatus('Your kingdom was moved to your current GPS location.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function challenge(zone:Zone){setBusy(true);setError('');setChallengeStatus('');try{await arena<{match:ArenaMatch}>('invasion-challenge',{territory_id:zone.id,control});setChallengeStatus(`Challenge sent to ${zone.display_name}. The 18 Gold fee is charged only when the KING accepts.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function openLeaders(scope:TerritoryScope){setLeaderBusy(true);setError('');try{setLeaders(await arena<Leaders>('territory-leaders',{scope}));}catch(e){setError((e as Error).message);}finally{setLeaderBusy(false);}}
 const ownerPlayer=(zone:Zone):Pick<ArenaPlayer,'display_name'|'avatar_url'>=>({display_name:zone.display_name,avatar_url:zone.avatar_url});

 return <section className="nearby-page"><div className="page-heading"><h1>{territory?'Territory Invasion':'Nearby Match'}</h1><button className={'gps-toggle '+(enabled?'on':'')} aria-pressed={enabled} onClick={toggle}><LocateFixed size={16}/>{enabled?'GPS on':'Enable GPS'}</button></div><p className="page-caption">{enabled?'Your GPS defines a responsive 2 km² kingdom square. Green KING flags are online; gray KING flags are offline.':'Share your GPS location to discover your kingdom range and nearby players.'}</p><div className="map-shell"><div className="live-map" ref={node}/><div ref={hoverCard} className={'map-centered-card '+(hovered?'visible':'')} aria-hidden={!hovered}/><div className="map-territory-controls" aria-label="Territory rankings"><button className="territory-fab city" disabled={!enabled||leaderBusy} onClick={()=>void openLeaders('city')} title="City territory leaderboard"><FlagTriangleRight size={21}/><span>City</span></button><button className="territory-fab barangay" disabled={!enabled||leaderBusy} onClick={()=>void openLeaders('barangay')} title="Barangay territory leaderboard"><Flag size={21}/><span>Brgy</span></button><button className="territory-fab king" disabled={!zones.length} onClick={()=>setSelectedZone(zones[0]??null)} title="Current kingdom KING"><Crown size={21}/><span>KING</span></button></div>
 {leaders&&<div className="territory-leaders" role="dialog" aria-modal="true" aria-label={`${leaders.label} leaderboard`}><button className="territory-close" aria-label="Close territory leaderboard" onClick={()=>setLeaders(null)}><X size={18}/></button><div className="territory-title"><MapPinned size={18}/><div><span>{leaders.scope==='city'?'City / town territory':'Barangay territory'}</span><h2>{leaders.label}</h2></div></div><p>Top 10 Chess Burger players by CBR</p><ol>{leaders.players.map((p,i)=><li key={p.user_id}><b>{i+1}</b><Avatar player={p}/><strong>{p.display_name}</strong><span>{p.cbr} CBR</span></li>)}</ol>{!leaders.players.length&&<p>No players have joined this territory yet.</p>}</div>}
 {selectedZone&&<article className="territory-owner-card" role="dialog" aria-label={`${selectedZone.barangay} kingdom owner`}><button className="territory-close" aria-label="Close KING card" onClick={()=>setSelectedZone(null)}><X size={17}/></button><div className="king-card-label"><Crown size={18}/><span>KINGDOM KING</span></div><div className="king-card-owner"><Avatar player={ownerPlayer(selectedZone)}/><button onClick={()=>onOpenProfile(selectedZone.user_id)}><strong>{selectedZone.display_name}</strong><small>{selectedZone.username?'@'+selectedZone.username+' · ':''}{selectedZone.cbr===null?'Rating unavailable':selectedZone.cbr+' CBR'}</small></button></div><h2>{selectedZone.barangay}</h2><p>2 km² kingdom square{selectedZone.locality?` · ${selectedZone.locality}`:''}</p><div className="king-defense"><Shield size={20}/><div><strong>{selectedZone.defense_points??'—'}</strong><span>Defense points</span></div><i className={selectedZone.online?'online':'offline'}>{selectedZone.online?'Online':'Offline'}</i></div>{!selectedZone.is_owner&&<div className="king-challenge"><label>Invasion time control<select value={control} onChange={e=>setControl(e.target.value)}>{TIME_CONTROLS.map(option=><option key={option.id} value={option.id}>{option.group} · {option.label}</option>)}</select></label><button className="gold-button" disabled={!selectedZone.online||busy} onClick={()=>void challenge(selectedZone)}><Swords size={15}/>{busy?'Sending…':'Challenge · 18 Gold'}</button>{!selectedZone.online&&<small>The KING must be online to accept an invasion.</small>}</div>}{selectedZone.is_owner&&<><label className="kingdom-name">Kingdom name<input value={renameName} maxLength={48} onChange={e=>setRenameName(e.target.value)} placeholder="Example: Omega Kingdom"/></label><button className="gold-button kingdom-save" disabled={busy||renameName.trim().length<3||renameName.trim()===selectedZone.kingdom_name} onClick={()=>void renameKingdom(selectedZone)}>{busy?'Saving…':'Save name'}</button><button className="gold-button" disabled={busy||!hasPosition} onClick={()=>void relocateKingdom(selectedZone)}>{busy?'Moving…':'Move kingdom to my GPS'}</button><p className="king-owned-note">You rule this 2 km² kingdom. Every successful defense adds +1 point.</p></>}{challengeStatus&&<p className="king-status" role="status">{challengeStatus}</p>}</article>}
 </div>{(gpsError||mapError||error)&&<p className="inline-error" role="status">{gpsError||mapError||error}</p>}
 {territory&&<div className="cloud-panel territory-panel"><Flag/><div><h2>{zones.length?'This kingdom has a KING':'Claim your 2 km² kingdom'}</h2><p>{zones.length?`${zones[0]?.display_name} has ${zones[0]?.defense_points??'—'} defense points. Challenge them while they are online.`:'Name your kingdom. A fresh 2 km² square costs 48 Gold and starts with 10 defense points.'}</p>{!zones.length&&<label className="kingdom-name">Kingdom name<input value={kingdomName} maxLength={48} onChange={e=>setKingdomName(e.target.value)} placeholder="Example: Omega Kingdom"/></label>}</div><button className="gold-button" disabled={!hasPosition||!enabled||busy||(!zones.length&&(!territoryDataReady||kingdomName.trim().length<3))} onClick={()=>zones.length?setSelectedZone(zones[0]):void claim()}>{zones.length?'View KING':busy?'Claiming…':!territoryDataReady?'Waiting for kingdoms…':'Claim · 48 Gold'}</button></div>}
 {selected&&<div className="cloud-panel selected-neighbor"><Avatar player={selected}/><button className="selected-player-profile" onClick={()=>onOpenProfile(selected.user_id)}><h2>{selected.display_name}</h2><p>{selected.cbr} CBR · {selected.distance} m away</p><small>View profile</small></button><button className="gold-button" onClick={()=>onInvite(selected)}>Invite</button><button aria-label="Close selected player" onClick={()=>setSelected(null)}>×</button></div>}
 <div className="nearby-list cloud-panel"><div className="section-title"><h2>Available nearby</h2><span>{players.length} players</span></div>{players.map(p=><button className="nearby-player" key={p.user_id} onClick={()=>setSelected(p)}><Avatar player={p}/><span><strong>{p.display_name}</strong><small>{p.cbr} CBR · {p.distance} m</small></span><MapPin size={16}/></button>)}{!players.length&&<p>{enabled?'No available players are sharing GPS nearby yet.':'GPS sharing is off. Your location is hidden.'}</p>}</div>
 <section className="map-live-stats" aria-label="Chess Burger live activity"><article><Users/><div><strong>{stats?stats.online_users:'—'} <small>/ {stats?stats.registered_users:'—'}</small></strong><span>Online / registered</span></div></article><article><Swords/><div><strong>{stats?.active_matches??'—'}</strong><span>Active matches</span></div></article><article><Satellite/><div><strong>{stats?.gps_online??'—'}</strong><span>GPS online</span></div></article><article><Crown/><div><strong>{stats?.highest_online?stats.highest_online.cbr+' CBR':'—'}</strong><span>{stats?.highest_online?stats.highest_online.display_name:'Highest online rank'}</span></div></article></section>{statsError&&<p className="account-note" role="status">{statsError}</p>}
 </section>;
}
