'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Leaflet from 'leaflet';
import {LocateFixed,MapPin,Flag,FlagTriangleRight,MapPinned,X} from 'lucide-react';
import {arena} from './arena-client';
import {Avatar} from './match-board';
import {mapPlayerCard} from './map-player-card';
import type {ArenaPlayer} from './game-rules';
import type {Position} from './gps-presence';
type NearbyPlayer=ArenaPlayer&{lat:number;lng:number;distance:number};
type Zone={id:string;user_id:string;lat:number;lng:number;display_name:string};
type TerritoryScope='barangay'|'city';
type Leaders={scope:TerritoryScope;label:string;players:ArenaPlayer[]};
export default function NearbyMap({enabled,position,toggle,error:gpsError,onInvite,territory=false,onClaimed}:{enabled:boolean;position:Position|null;toggle:()=>void;error:string;onInvite:(p:ArenaPlayer)=>void;territory?:boolean;onClaimed:()=>void}){
 const node=useRef<HTMLDivElement>(null),map=useRef<Leaflet.Map|null>(null),layer=useRef<Leaflet.LayerGroup|null>(null),lib=useRef<typeof Leaflet|null>(null),centered=useRef(false),visiblePlayers=useRef(''),hoverCard=useRef<HTMLDivElement>(null);
 const [players,setPlayers]=useState<NearbyPlayer[]>([]),[zones,setZones]=useState<Zone[]>([]),[selected,setSelected]=useState<NearbyPlayer|null>(null),[hovered,setHovered]=useState<NearbyPlayer|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[leaders,setLeaders]=useState<Leaders|null>(null),[leaderBusy,setLeaderBusy]=useState(false);
 useEffect(()=>{let alive=true;void import('leaflet').then(L=>{if(!alive||!node.current)return;lib.current=L;const instance=L.map(node.current,{zoomControl:true}).setView([11.244,125.003],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(instance);layer.current=L.layerGroup().addTo(instance);map.current=instance;setReady(true);}).catch(()=>setError('The map could not load. Please reconnect and try again.'));return()=>{alive=false;map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!enabled||!position){visiblePlayers.current='';setPlayers([]);setZones([]);setSelected(null);setHovered(null);return;}let alive=true,pending=false;const load=async()=>{if(pending)return;pending=true;try{const data=await arena<{players:NearbyPlayer[];territories:Zone[]}>('nearby');if(alive){setPlayers(data.players);setSelected(old=>old?data.players.find(p=>p.user_id===old.user_id)??null:null);setHovered(old=>old?data.players.find(p=>p.user_id===old.user_id)??null:null);setZones(data.territories);setError('');}}catch(e){if(alive)setError((e as Error).message);}finally{pending=false;}};void load();const timer=setInterval(load,2000);return()=>{alive=false;clearInterval(timer);};},[enabled,!!position]);
 useEffect(()=>{if(!hoverCard.current)return;hoverCard.current.replaceChildren();if(hovered)hoverCard.current.append(mapPlayerCard(hovered));},[hovered]);
 useEffect(()=>{if(!ready||!lib.current||!map.current||!layer.current)return;const L=lib.current;layer.current.clearLayers();if(position&&enabled){if(!centered.current){map.current.setView([position.lat,position.lng],16);centered.current=true;}L.circleMarker([position.lat,position.lng],{radius:8,color:'#157b90',weight:3,fillColor:'#64e1ec',fillOpacity:1}).bindTooltip('You').addTo(layer.current);if(territory)L.circle([position.lat,position.lng],{radius:200,color:'#b99747',weight:2,fillOpacity:.08}).addTo(layer.current);}
  for(const p of players){const el=document.createElement('div');el.className='map-avatar';el.textContent=p.display_name.slice(0,1).toUpperCase();if(p.avatar_url){const img=document.createElement('img');img.src=p.avatar_url;img.alt=p.display_name;img.loading='eager';img.decoding='async';img.referrerPolicy='no-referrer';Object.assign(img.style,{display:'block',position:'absolute',inset:'0',width:'100%',height:'100%',maxWidth:'none',objectFit:'cover',opacity:'1',zIndex:'2'});img.onerror=()=>img.remove();el.appendChild(img);}el.setAttribute('aria-label',p.display_name+' · invite to match');const marker=L.marker([p.lat,p.lng],{icon:L.divIcon({html:'',className:'map-player-pin',iconSize:[40,40],iconAnchor:[20,20]})}).on('mouseover',()=>setHovered(p)).on('mouseout',()=>setHovered(current=>current?.user_id===p.user_id?null:current)).on('click',()=>setSelected(p)).addTo(layer.current);marker.getElement()?.replaceChildren(el);}
  for(const zone of zones){const label=document.createElement('span');label.textContent=zone.display_name+' · 200 m territory';L.circle([zone.lat,zone.lng],{radius:200,color:'#ae8b37',weight:1.5,fillOpacity:.14}).bindTooltip(label).addTo(layer.current);}
  // Keep every active GPS avatar in view. The former fixed zoom could leave a
  // valid nearby player several kilometres off-screen, making the map look empty.
  if(position&&players.length){const signature=players.map(p=>`${p.user_id}:${p.lat.toFixed(4)}:${p.lng.toFixed(4)}`).join('|');if(signature!==visiblePlayers.current){visiblePlayers.current=signature;map.current.fitBounds(L.latLngBounds([[position.lat,position.lng],...players.map(p=>[p.lat,p.lng] as [number,number])]),{padding:[42,42],maxZoom:15,animate:true});}}
 },[ready,position,enabled,players,zones,territory]);
 async function claim(){setBusy(true);setError('');try{await arena('claim');onClaimed();const d=await arena<{territories:Zone[]}>('nearby');setZones(d.territories);setError('Territory claimed · +10 CBR.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function openLeaders(scope:TerritoryScope){setLeaderBusy(true);setError('');try{setLeaders(await arena<Leaders>('territory-leaders',{scope}));}catch(e){setError((e as Error).message);}finally{setLeaderBusy(false);}}
 return <section className="nearby-page"><div className="page-heading"><h1>{territory?'Territory Invasion':'Nearby Match'}</h1><button className={'gps-toggle '+(enabled?'on':'')} aria-pressed={enabled} onClick={toggle}><LocateFixed size={16}/>{enabled?'GPS on':'Enable GPS'}</button></div><p className="page-caption">{enabled?'Online players sharing GPS appear automatically as avatar markers. Hover an avatar to view their card, or tap it to invite them.':'Share your GPS location to find players within 10 km.'}</p><div className="map-shell"><div className="live-map" ref={node}/><div ref={hoverCard} className={'map-centered-card '+(hovered?'visible':'')} aria-hidden={!hovered}/><div className="map-territory-controls" aria-label="Territory rankings"><button className="territory-fab city" disabled={!enabled||leaderBusy} onClick={()=>void openLeaders('city')} title="City territory leaderboard"><FlagTriangleRight size={21}/><span>City</span></button><button className="territory-fab barangay" disabled={!enabled||leaderBusy} onClick={()=>void openLeaders('barangay')} title="Barangay territory leaderboard"><Flag size={21}/><span>Brgy</span></button></div>{leaders&&<div className="territory-leaders" role="dialog" aria-modal="true" aria-label={`${leaders.label} leaderboard`}><button className="territory-close" aria-label="Close territory leaderboard" onClick={()=>setLeaders(null)}><X size={18}/></button><div className="territory-title"><MapPinned size={18}/><div><span>{leaders.scope==='city'?'City / town territory':'Barangay territory'}</span><h2>{leaders.label}</h2></div></div><p>Top 10 Chess Burger players by CBR</p><ol>{leaders.players.map((p,i)=><li key={p.user_id}><b>{i+1}</b><Avatar player={p}/><strong>{p.display_name}</strong><span>{p.cbr} CBR</span></li>)}</ol>{!leaders.players.length&&<p>No players have joined this territory yet.</p>}</div>}</div>{(gpsError||error)&&<p className="inline-error" role="status">{gpsError||error}</p>}
 {territory&&<div className="cloud-panel territory-panel"><Flag/><div><h2>Claim a 200 m territory</h2><p>+10 CBR for a new unoccupied zone. One claim per day.</p></div><button className="gold-button" disabled={!position||!enabled||busy} onClick={()=>void claim()}>Invade</button></div>}
 {selected&&<div className="cloud-panel selected-neighbor"><Avatar player={selected}/><div><h2>{selected.display_name}</h2><p>{selected.cbr} CBR · {selected.distance} m away</p></div><button className="gold-button" onClick={()=>onInvite(selected)}>Invite</button><button aria-label="Close selected player" onClick={()=>setSelected(null)}>×</button></div>}
 <div className="nearby-list cloud-panel"><div className="section-title"><h2>Available nearby</h2><span>{players.length} players</span></div>{players.map(p=><button className="nearby-player" key={p.user_id} onClick={()=>setSelected(p)}><Avatar player={p}/><span><strong>{p.display_name}</strong><small>{p.cbr} CBR · {p.distance} m</small></span><MapPin size={16}/></button>)}{!players.length&&<p>{enabled?'No available players are sharing GPS nearby yet.':'GPS sharing is off. Your location is hidden.'}</p>}</div></section>;
}
