'use client';
import {useEffect,useRef,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {Search,Copy,X} from 'lucide-react';
import {arena} from './arena-client';
import {type ArenaMatch,type ArenaPlayer,timeControl} from './game-rules';
import type {PlayerProfile} from './supabase';
import TimePicker from './time-picker';
import MatchBoard,{Avatar} from './match-board';
import QrInput from './qr-input';
import {saveGame} from './game-history';
export function OnlineGame({id,profile,onFinished,watch=false}:{id:string;profile:PlayerProfile|null;onFinished:(match:ArenaMatch)=>void;watch?:boolean}){
 const [match,setMatch]=useState<ArenaMatch|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const finished=useRef(false),alive=useRef(true),latest=useRef(0);
 function accept(m:ArenaMatch){if(!alive.current||m.version<latest.current)return;latest.current=m.version;setMatch(m);setError('');if(m.status==='finished'&&!finished.current){finished.current=true;if(!watch){try{saveGame({id:m.id,white:m.white?.display_name??'White',black:m.black?.display_name??'Black',pgn:m.pgn,score:m.result==='draw'?'½–½':m.result==='white'?'1–0':'0–1',startedAt:new Date(m.created_at).toISOString(),updatedAt:new Date().toISOString(),ratedAt:new Date().toISOString()});}catch{}onFinished(m);}}}
 useEffect(()=>{alive.current=true;let pending=false;const poll=async()=>{if(pending)return;pending=true;try{const r=await arena<{match:ArenaMatch}>(watch?'watch':'match',{id},watch);accept(r.match);}catch(e){if(alive.current)setError((e as Error).message);}finally{pending=false;}};void poll();const timer=setInterval(poll,1500);return()=>{alive.current=false;clearInterval(timer);};},[id,watch]);
 async function move(action:'move'|'resign',move?:{from:string;to:string;promotion?:string}){if(!match||busy)return;setBusy(true);try{const r=await arena<{match:ArenaMatch}>(action,{id,version:match.version,move});accept(r.match);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!match)return <p className="cloud-panel" role="status">{error||'Opening your board…'}</p>;
 return <>{error&&<p className="inline-error" role="alert">{error}</p>}<MatchBoard match={match} ownId={profile?.user_id} onMove={watch?undefined:m=>void move('move',m)} onResign={watch?undefined:()=>void move('resign')} busy={busy} connection={error?'Reconnecting…':watch?'Spectating':'Live'}/></>;
}
export default function OnlinePlay({profile,onMatch,onLogin,target}:{profile:PlayerProfile|null;onMatch:(id:string)=>void;onLogin:()=>void;target?:ArenaPlayer|null}){
 const [control,setControl]=useState('10+0'),[searching,setSearching]=useState(false),[room,setRoom]=useState<ArenaMatch|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const cancelled=useRef(false),callback=useRef(onMatch);callback.current=onMatch;
 useEffect(()=>{if(!searching)return;cancelled.current=false;let pending=false;const poll=async()=>{if(pending)return;pending=true;try{const r=await arena<{match:ArenaMatch|null}>('queue',{control});if(cancelled.current){await arena('cancel-queue');return;}if(r.match){setSearching(false);callback.current(r.match.id);}}catch(e){setError((e as Error).message);setSearching(false);}finally{pending=false;}};void poll();const timer=setInterval(poll,2000);return()=>{cancelled.current=true;clearInterval(timer);void arena('cancel-queue').catch(()=>{});};},[searching,control]);
 useEffect(()=>{if(!room)return;let active=true;const poll=async()=>{try{const r=await arena<{match:ArenaMatch}>('match',{id:room.id});if(active&&r.match.status==='active')callback.current(r.match.id);else if(active&&(r.match.status==='cancelled'||Date.now()-r.match.created_at>120000)){setRoom(null);setError('Invitation expired. Create another room.');}}catch(e){if(active)setError((e as Error).message);}};const timer=setInterval(poll,2000);return()=>{active=false;clearInterval(timer);};},[room?.id]);
 async function create(){setBusy(true);setError('');try{const r=await arena<{match:ArenaMatch}>('room',{control,target:target?.user_id});setRoom(r.match);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function join(value:string){setBusy(true);setError('');try{let code=value.trim();try{const link=new URL(value);code=new URLSearchParams(link.hash.slice(1)).get('match')??value;}catch{}const r=await arena<{match:ArenaMatch}>('join',{code});onMatch(r.match.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!profile||profile.user_id==='guest-device')return <section className="cloud-panel login-prompt"><h1>Play Online</h1><p>Sign in and save your player profile to find an opponent.</p><button className="gold-button" onClick={onLogin}>Sign in</button></section>;
 return <section className="match-setup"><div className="page-heading"><h1>{target?'Invite to a match':'Play Online'}</h1><span className="sample-label">{profile.cbr} CBR</span></div>{target?<div className="invite-player cloud-panel"><Avatar player={target}/><span><strong>{target.display_name}</strong><small>{target.cbr} CBR · You host this match</small></span></div>:<p className="page-caption">Random opponents within 20 CBR of your rating.</p>}
 <div className="cloud-panel"><TimePicker value={control} onChange={setControl} disabled={searching||!!room||busy}/>{searching?<div className="search-status"><Search size={20}/><strong>Finding an available player…</strong><p>{Math.max(0,profile.cbr-20)}–{profile.cbr+20} CBR · {timeControl(control).label}</p><button onClick={()=>setSearching(false)}><X size={15}/>Cancel search</button></div>:!room&&<button disabled={busy} className="gold-button wide" onClick={()=>{setError('');target?void create():setSearching(true);}}>{target?'Send match invitation':'Find opponent'}</button>}
 <p className="rules-caption">Win +8 CBR · loss −10 · 4+ win streak +2. If the rating gap exceeds 10, the winner also earns 10% of the opponent’s starting CBR, rounded down.</p></div>
 {!target&&!searching&&!room&&<div className="lobby-pair-grid"><div className="cloud-panel"><h2>Host with QR</h2><p>Invite a friend with a QR or short code.</p><button disabled={busy} onClick={()=>void create()}>Create room</button></div><div className="cloud-panel"><h2>Join a room</h2><QrInput label="Scan match QR" onValue={v=>void join(v)}/></div></div>}
 {room&&<div className="cloud-panel room-waiting"><QRCodeSVG value={typeof window==='undefined'?room.code:window.location.origin+'/#match='+room.code} size={190} marginSize={3}/><strong className="room-code">{room.code}</strong><button onClick={()=>void navigator.clipboard.writeText(room.code).catch(()=>setError('Copy the displayed code manually.'))}><Copy size={15}/>Copy code</button><p>{target?'Invitation sent to '+target.display_name:'Waiting for your opponent'} · {timeControl(room.control).label}</p><button onClick={()=>{void arena('cancel-room',{id:room.id});setRoom(null);}}>Cancel invitation</button></div>}{error&&<p className="inline-error" role="alert">{error}</p>}</section>;
}
