"use client";
import {useEffect,useMemo,useState} from "react";
import {Chess,type Square} from "chess.js";
import {ArrowLeft,Check,Coins,Flame,Lightbulb,RotateCcw,Star,Target,Volume2} from "lucide-react";
import {toast} from "sonner";
import {arena} from "./arena-client";
import {DAILY_PUZZLES,type DailyPuzzle} from "./puzzle-data";

const symbols:Record<string,string>={wk:"♚︎",wq:"♛︎",wr:"♜︎",wb:"♝︎",wn:"♞︎",wp:"♟︎",bk:"♚︎",bq:"♛︎",br:"♜︎",bb:"♝︎",bn:"♞︎",bp:"♟︎"};
const tracks=[{key:"easy",label:"Easy",description:"25 tactical patterns · 1 CBG each"},{key:"regular",label:"Regular",description:"25 balanced challenges · 2 CBG each"},{key:"hard",label:"Hard",description:"25 deep calculations · 3 CBG each"},{key:"random",label:"Random",description:"25 surprises · 1–3 CBG each"}]as const;
const fallbackDaily=[...DAILY_PUZZLES.slice(0,25),...DAILY_PUZZLES.slice(30,55),...DAILY_PUZZLES.slice(70,95),...DAILY_PUZZLES.slice(25,30),...DAILY_PUZZLES.slice(55,70),...DAILY_PUZZLES.slice(95)];
type Track=(typeof tracks)[number]["key"];
type PuzzleState={completed:string[];gold:number;bonus_claimed:boolean;day:string;daily_puzzle_ids:string[];puzzle_rating:number;solved_total:number;correct_streak:number;best_streak:number};

export default function Puzzles({onClose,onReward}:{onClose:()=>void;onReward:()=>void}){
  const [state,setState]=useState<PuzzleState|null>(null),[track,setTrack]=useState<Track>("easy"),[slot,setSlot]=useState(0),[selected,setSelected]=useState<Square|null>(null),[message,setMessage]=useState("Find the winning move."),[hintOpen,setHintOpen]=useState(false),[busy,setBusy]=useState(false),[step,setStep]=useState(0);
  const dailyPuzzles=useMemo(()=>state?.daily_puzzle_ids?.length===100?state.daily_puzzle_ids.map(id=>DAILY_PUZZLES.find(puzzle=>puzzle.id===id)).filter((puzzle):puzzle is DailyPuzzle=>Boolean(puzzle)):fallbackDaily,[state?.daily_puzzle_ids]);
  const trackIndex=tracks.findIndex(item=>item.key===track),trackPuzzles=dailyPuzzles.slice(trackIndex*25,trackIndex*25+25),puzzle=(trackPuzzles[slot]??trackPuzzles[0]??DAILY_PUZZLES[0])as DailyPuzzle,completed=new Set(state?.completed??[]),solved=completed.has(puzzle.id);
  const [game,setGame]=useState(()=>new Chess(DAILY_PUZZLES[0].fen));
  const legal=useMemo(()=>selected?game.moves({square:selected,verbose:true}).map(move=>move.to):[],[game,selected]);
  useEffect(()=>{arena<PuzzleState>("puzzle-state").then(setState).catch(error=>setMessage(error instanceof Error?error.message:"Puzzle progress could not load."))},[]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{setGame(new Chess(puzzle.fen));setStep(0);setSelected(null);setHintOpen(false);setMessage(solved?"Solved today. Replay it for practice.":"Find the best move.")},[puzzle.id,solved]);
  function reset(){setGame(new Chess(puzzle.fen));setStep(0);setSelected(null);setBusy(false);setMessage("Try again. Calculate checks, captures and threats.")}
  async function play(square:Square){
    if(busy)return;const piece=game.get(square);if(!selected){if(piece?.color===game.turn())setSelected(square);return}if(piece?.color===game.turn()){setSelected(square);return}
    const copy=new Chess(game.fen());let move;try{move=copy.move({from:selected,to:square,promotion:"q"})}catch{setSelected(null);return}const uci=`${move.from}${move.to}${move.promotion??""}`;setSelected(null);if(uci!==puzzle.moves[step]){setMessage("That is legal, but not the best continuation. Try again.");return}setGame(copy);const opponentStep=step+1;
    if(opponentStep<puzzle.moves.length){setBusy(true);setMessage("Correct. Coach Patty is playing the forced reply…");await new Promise(resolve=>window.setTimeout(resolve,420));const reply=puzzle.moves[opponentStep];try{copy.move({from:reply.slice(0,2),to:reply.slice(2,4),promotion:reply.slice(4)||undefined})}catch{setBusy(false);setMessage("Puzzle line could not continue. Please reload.");return}setGame(new Chess(copy.fen()));setStep(opponentStep+1);setBusy(false);setMessage("Good. Continue with the strongest move.");return}
    if(solved){setMessage("Correct — excellent pattern recognition!");toast.success(`${tracks.find(item=>item.key===track)?.label} puzzle solved again!`,{description:"Practice replay · rating unchanged"});return}
    setBusy(true);setMessage("Correct! Updating your Puzzle Rating…");try{const result=await arena<PuzzleState&{awarded:boolean;gold_delta:number;rating_delta:number}>("claim-puzzle",{puzzle_id:puzzle.id,proof:puzzle.moves.join(" ")});setState(result);onReward();setMessage(result.awarded?`Solved! +${result.rating_delta} Puzzle Rating · +${result.gold_delta} Gold.`:"Already completed today.");toast.success(`${tracks.find(item=>item.key===track)?.label} puzzle solved!`,{description:result.awarded?`+${result.rating_delta} Puzzle Rating · +${result.gold_delta} Gold`:"Daily reward already claimed"});const next=trackPuzzles.findIndex((item,index)=>index>slot&&!result.completed.includes(item.id));if(next>=0)setSlot(next)}catch(error){setMessage(error instanceof Error?error.message:"Reward could not be claimed.")}finally{setBusy(false)}
  }
  function coachSpeak(){const text=hintOpen?puzzle.hint:`${puzzle.title}. ${puzzle.theme}. Find the winning move.`;if("speechSynthesis"in window){const speech=window.speechSynthesis,utterance=new SpeechSynthesisUtterance(text),voices=speech.getVoices(),femaleName=/(female|samantha|zira|aria|jenny|ava|susan|karen|moira|tessa|victoria|serena|siri)/i;utterance.voice=voices.find(voice=>/^en-PH$/i.test(voice.lang)&&femaleName.test(voice.name))??voices.find(voice=>/^en-PH$/i.test(voice.lang))??voices.find(voice=>/^en-(US|GB|AU)$/i.test(voice.lang)&&femaleName.test(voice.name))??voices.find(voice=>/^en/i.test(voice.lang))??null;utterance.lang=utterance.voice?.lang??"en-PH";utterance.rate=.94;utterance.pitch=1.12;speech.cancel();speech.speak(utterance)}setHintOpen(true)}
  return <section className="puzzle-page">
    <button className="back-button" type="button" onClick={onClose}><ArrowLeft size={16}/>Match Lobby</button>
    <header className="puzzle-hero"><div><span>100 DAILY PUZZLES · RESETS 12:00 AM PH</span><h1>Puzzle Quest</h1><p>Play 25 Easy, 25 Regular, 25 Hard, and 25 Random puzzles every day. Every solve rewards 1–3 CBG.</p></div><div className="puzzle-gold"><Coins/><strong>{state?.gold??"—"}</strong><small>Your Gold</small></div></header>
    <section className="puzzle-rating-card"><div><Target/><span><small>PUZZLE RATING</small><strong>{state?.puzzle_rating??1000}</strong></span></div><div><Check/><span><small>TOTAL SOLVED</small><strong>{state?.solved_total??0}</strong></span></div><div><Flame/><span><small>CURRENT STREAK</small><strong>{state?.correct_streak??0}</strong></span></div><div><Star/><span><small>BEST STREAK</small><strong>{state?.best_streak??0}</strong></span></div></section>
    <div className="daily-puzzle-tracks" aria-label="Daily puzzle difficulty">{tracks.map((item,index)=>{const group=dailyPuzzles.slice(index*25,index*25+25),doneCount=group.filter(entry=>completed.has(entry.id)).length,done=doneCount===25;return <button type="button" key={item.key} className={`${track===item.key?"active":""} ${done?"done":""}`} onClick={()=>{setTrack(item.key);const next=group.findIndex(entry=>!completed.has(entry.id));setSlot(next<0?24:next)}}><span>{done?<Check/>:index+1}</span><div><small>TODAY · {item.label}</small><strong>{doneCount}/25 solved</strong><p>{item.description}</p></div></button>})}</div>
    <div className="daily-reset-status"><span>{state?.completed.length??0}/100 completed today</span><strong>{state?.bonus_claimed?"Daily 100 complete · bonus claimed":`Daily date: ${state?.day??"Loading…"}`}</strong></div>
    <div className="puzzle-trail" aria-label={`${track} daily puzzles`}>{trackPuzzles.map((item,index)=>{const done=completed.has(item.id);return <button type="button" key={item.id} className={`${slot===index?"active":""} ${done?"done":""}`} onClick={()=>setSlot(index)}><span>{done?<Check/>:index+1}</span><small>{done?"Solved":"Play"}</small></button>})}</div>
    <div className="puzzle-workspace"><div className="puzzle-board-wrap"><div className="puzzle-board" aria-label={`Chess puzzle: ${puzzle.title}`}>{game.board().flat().map((piece,cell)=>{const row=Math.floor(cell/8),column=cell%8,square=(`${"abcdefgh"[column]}${8-row}`)as Square;return <button type="button" key={square} aria-label={`${square}${piece?` ${piece.color==="w"?"white":"black"} ${piece.type}`:" empty"}`} className={`puzzle-square ${(row+column)%2?"dark":"light"} ${selected===square?"selected":""} ${legal.includes(square)?"legal":""} ${piece?.color==="w"?"white-piece":"black-piece"}`} onClick={()=>void play(square)}><span className="puzzle-piece">{piece?symbols[piece.color+piece.type]:""}</span>{column===0&&<small className="puzzle-rank">{8-row}</small>}{row===7&&<small className="puzzle-file">{"abcdefgh"[column]}</small>}</button>})}</div></div>
      <aside className="puzzle-coach"><div className="coach-avatar"><img src="/puzzles/coach-patty.webp" alt="Coach Patty, a friendly white queen chess character"/></div><span>DAILY {tracks.find(item=>item.key===track)?.label} COACH</span><h2>Coach Patty</h2><p>{message}</p>{hintOpen&&<div className="coach-hint"><Lightbulb/>{puzzle.hint}</div>}<div className="coach-actions"><button type="button" onClick={()=>setHintOpen(value=>!value)}><Lightbulb/>Hint</button><button type="button" onClick={coachSpeak}><Volume2/>Read</button><button type="button" onClick={reset}><RotateCcw/>Reset</button></div><div className="puzzle-detail"><span>{tracks.find(item=>item.key===track)?.label} daily challenge</span><strong>{puzzle.title}</strong><small>Rated {puzzle.rating} · {puzzle.theme} · {new Chess(puzzle.fen).turn()==="w"?"White":"Black"} to move</small><a href={puzzle.sourceUrl} target="_blank" rel="noreferrer">Lichess CC0 source · {puzzle.sourceId}</a></div></aside>
    </div>
  </section>
}
