"use client";
import {useEffect,useMemo,useState} from "react";
import {Chess,type Square} from "chess.js";
import {ArrowLeft,CalendarDays,Check,Coins,Crown,Flame,Lightbulb,RotateCcw,Star,Target,Trophy,Volume2} from "lucide-react";
import {toast} from "sonner";
import {arena} from "./arena-client";
import {DAILY_PUZZLES,type DailyPuzzle} from "./puzzle-data";

const symbols:Record<string,string>={wk:"♚︎",wq:"♛︎",wr:"♜︎",wb:"♝︎",wn:"♞︎",wp:"♟︎",bk:"♚︎",bq:"♛︎",br:"♜︎",bb:"♝︎",bn:"♞︎",bp:"♟︎"};
const tracks=[{key:"easy",label:"Easy",count:5,description:"5 tactical patterns · 1 CBG each"},{key:"regular",label:"Regular",count:5,description:"5 balanced challenges · 2 CBG each"},{key:"hard",label:"Hard",count:5,description:"5 deep calculations · 3 CBG each"},{key:"random",label:"Random",count:100,description:"100 daily surprises · 1–3 CBG each"}]as const;
const fallbackTracks={easy:DAILY_PUZZLES.slice(0,5).map(item=>item.id),regular:DAILY_PUZZLES.slice(30,35).map(item=>item.id),hard:DAILY_PUZZLES.slice(70,75).map(item=>item.id),random:DAILY_PUZZLES.map(item=>item.id)};
type Track=(typeof tracks)[number]["key"];
type Leader={user_id:string;username?:string;display_name?:string;avatar_url?:string;value:number;puzzle_rating?:number;solved_total?:number};
type PuzzleState={completed:string[];gold:number;bonus_claimed:boolean;day:string;daily_puzzle_ids:string[];daily_tracks:Record<Track,string[]>;leaders:{all_time:Leader|null;today:Leader|null;rating:Leader|null};puzzle_rating:number;solved_total:number;correct_streak:number;best_streak:number};

export default function Puzzles({onClose,onReward}:{onClose:()=>void;onReward:()=>void}){
  const [state,setState]=useState<PuzzleState|null>(null),[track,setTrack]=useState<Track>("easy"),[slot,setSlot]=useState(0),[selected,setSelected]=useState<Square|null>(null),[message,setMessage]=useState("Find the winning move."),[hintOpen,setHintOpen]=useState(false),[busy,setBusy]=useState(false),[step,setStep]=useState(0);
  const dailyTracks=state?.daily_tracks??fallbackTracks;
  const trackPuzzles=useMemo(()=>(dailyTracks[track]||[]).map(id=>DAILY_PUZZLES.find(puzzle=>puzzle.id===id)).filter((puzzle):puzzle is DailyPuzzle=>Boolean(puzzle)),[dailyTracks,track]);
  const puzzle=(trackPuzzles[slot]??trackPuzzles[0]??DAILY_PUZZLES[0])as DailyPuzzle,completed=new Set(state?.completed??[]),solved=completed.has(puzzle.id);
  const [game,setGame]=useState(()=>new Chess(DAILY_PUZZLES[0].fen));
  const legal=useMemo(()=>selected?game.moves({square:selected,verbose:true}).map(move=>move.to):[],[game,selected]);
  useEffect(()=>{arena<PuzzleState>("puzzle-state").then(setState).catch(error=>setMessage(error instanceof Error?error.message:"Puzzle progress could not load."))},[]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{setGame(new Chess(puzzle.fen));setStep(0);setSelected(null);setHintOpen(false);setMessage(solved?"Solved today. Replay it for practice.":"Find the best move.")},[puzzle.id,solved]);
  function reset(){setGame(new Chess(puzzle.fen));setStep(0);setSelected(null);setBusy(false);setMessage("Try again. Calculate checks, captures and threats.")}
  async function play(square:Square){
    if(busy)return;const piece=game.get(square);if(!selected){if(piece?.color===game.turn())setSelected(square);return}if(piece?.color===game.turn()){setSelected(square);return}
    const copy=new Chess(game.fen());let move;try{move=copy.move({from:selected,to:square,promotion:"q"})}catch{setSelected(null);return}const uci=`${move.from}${move.to}${move.promotion??""}`;setSelected(null);if(uci!==puzzle.moves[step]){setMessage("That is legal, but not the best continuation. Try again.");return}setGame(copy);const opponentStep=step+1;
    if(opponentStep<puzzle.moves.length){setBusy(true);setMessage("Correct. Coach Patty is playing the forced reply…");await new Promise(resolve=>window.setTimeout(resolve,420));const reply=puzzle.moves[opponentStep];try{copy.move({from:reply.slice(0,2),to:reply.slice(2,4),promotion:reply.slice(4)||undefined})}catch{setBusy(false);setMessage("Puzzle line could not continue. Please reload.");return}setGame(new Chess(copy.fen()));setStep(opponentStep+1);setBusy(false);setMessage("Good. Continue with the strongest move.");return}
    if(solved){setMessage("Correct — excellent pattern recognition!");toast.success(`${tracks.find(item=>item.key===track)?.label} puzzle solved again!`,{description:"Practice replay · rating unchanged"});return}
    setBusy(true);setMessage("Correct! Updating your Puzzle Rating…");try{const result=await arena<PuzzleState&{awarded:boolean;gold_delta:number;rating_delta:number}>("claim-puzzle",{puzzle_id:puzzle.id,proof:puzzle.moves.join(" ")});setState(result);onReward();setMessage(result.awarded?`Solved! +${result.rating_delta} Puzzle Rating · +${result.gold_delta} Gold.`:"Already completed today.");toast.success(`${tracks.find(item=>item.key===track)?.label} puzzle solved!`,{description:result.awarded?`+${result.rating_delta} Puzzle Rating · +${result.gold_delta} Gold`:"Daily reward already claimed"});const next=trackPuzzles.findIndex((item,index)=>index>slot&&!result.completed.includes(item.id));if(next>=0)setSlot(next)}catch(error){setMessage(error instanceof Error?error.message:"Reward could not be claimed.")}finally{setBusy(false)}
  }
  function coachSpeak(){const text=hintOpen?puzzle.hint:`${puzzle.title}. ${puzzle.theme}. Find the winning move.`;if("speechSynthesis"in window){const speech=window.speechSynthesis,utterance=new SpeechSynthesisUtterance(text),voices=speech.getVoices(),femaleName=/(female|samantha|zira|aria|jenny|ava|susan|karen|moira|tessa|victoria|serena|siri)/i;utterance.voice=voices.find(voice=>/^en-PH$/i.test(voice.lang)&&femaleName.test(voice.name))??voices.find(voice=>/^en-PH$/i.test(voice.lang))??voices.find(voice=>/^en-(US|GB|AU)$/i.test(voice.lang)&&femaleName.test(voice.name))??voices.find(voice=>/^en/i.test(voice.lang))??null;utterance.lang=utterance.voice?.lang??"en-PH";utterance.rate=.94;utterance.pitch=1.12;speech.cancel();speech.speak(utterance)}setHintOpen(true)}
  return <section className="puzzle-page">
    <button className="back-button" type="button" onClick={onClose}><ArrowLeft size={16}/>Match Lobby</button>
    <header className="puzzle-hero"><div><span>NEW PUZZLES DAILY · RESETS 12:00 AM PH</span><h1>Puzzle Quest</h1><p>Play 5 Easy, 5 Regular, 5 Hard, and 100 Random puzzles. Every daily set changes and every solve rewards 1–3 CBG.</p></div><div className="puzzle-gold"><Coins/><strong>{state?.gold??"—"}</strong><small>Your Gold</small></div></header>
    <section className="puzzle-rating-card"><div><Target/><span><small>PUZZLE RATING</small><strong>{state?.puzzle_rating??1000}</strong></span></div><div><Check/><span><small>TOTAL SOLVED</small><strong>{state?.solved_total??0}</strong></span></div><div><Flame/><span><small>CURRENT STREAK</small><strong>{state?.correct_streak??0}</strong></span></div><div><Star/><span><small>BEST STREAK</small><strong>{state?.best_streak??0}</strong></span></div></section>
    <div className="daily-puzzle-tracks" aria-label="Daily puzzle difficulty">{tracks.map((item,index)=>{const group=(dailyTracks[item.key]||[]).map(id=>DAILY_PUZZLES.find(puzzle=>puzzle.id===id)).filter((puzzle):puzzle is DailyPuzzle=>Boolean(puzzle)),doneCount=group.filter(entry=>completed.has(entry.id)).length,done=doneCount===item.count;return <button type="button" key={item.key} className={`${track===item.key?"active":""} ${done?"done":""}`} onClick={()=>{setTrack(item.key);const next=group.findIndex(entry=>!completed.has(entry.id));setSlot(next<0?Math.max(0,item.count-1):next)}}><span>{done?<Check/>:index+1}</span><div><small>TODAY · {item.label}</small><strong>{doneCount}/{item.count} solved</strong><p>{item.description}</p></div></button>})}</div>
    <div className="daily-reset-status"><span>{state?.completed.length??0}/100 completed today</span><strong>{state?.bonus_claimed?"Daily 100 complete · bonus claimed":`Daily date: ${state?.day??"Loading…"}`}</strong></div>
    <div className="puzzle-workspace"><div className="puzzle-board-wrap"><div className="puzzle-board" aria-label={`Chess puzzle: ${puzzle.title}`}>{game.board().flat().map((piece,cell)=>{const row=Math.floor(cell/8),column=cell%8,square=(`${"abcdefgh"[column]}${8-row}`)as Square;return <button type="button" key={square} aria-label={`${square}${piece?` ${piece.color==="w"?"white":"black"} ${piece.type}`:" empty"}`} className={`puzzle-square ${(row+column)%2?"dark":"light"} ${selected===square?"selected":""} ${legal.includes(square)?"legal":""} ${piece?.color==="w"?"white-piece":"black-piece"}`} onClick={()=>void play(square)}><span className="puzzle-piece">{piece?symbols[piece.color+piece.type]:""}</span>{column===0&&<small className="puzzle-rank">{8-row}</small>}{row===7&&<small className="puzzle-file">{"abcdefgh"[column]}</small>}</button>})}</div></div>
      <div className="puzzle-right-rail"><aside className="puzzle-coach"><div className="coach-avatar"><img src="/puzzles/coach-patty.webp" alt="Coach Patty, a friendly white queen chess character"/></div><span>DAILY {tracks.find(item=>item.key===track)?.label} COACH</span><h2>Coach Patty</h2><p>{message}</p>{hintOpen&&<div className="coach-hint"><Lightbulb/>{puzzle.hint}</div>}<div className="coach-actions"><button type="button" onClick={()=>setHintOpen(value=>!value)}><Lightbulb/>Hint</button><button type="button" onClick={coachSpeak}><Volume2/>Read</button><button type="button" onClick={reset}><RotateCcw/>Reset</button></div><div className="puzzle-detail"><span>{tracks.find(item=>item.key===track)?.label} daily challenge</span><strong>{puzzle.title}</strong><small>Rated {puzzle.rating} · {puzzle.theme} · {new Chess(puzzle.fen).turn()==="w"?"White":"Black"} to move</small></div></aside><section className="puzzle-leaders"><header><Trophy/><span><small>PUZZLE LEADERBOARD</small><h2>TOP RANK</h2></span></header>{([{key:"today",label:"Most Solved · Today",icon:<CalendarDays/>,suffix:"today"},{key:"all_time",label:"Most Solved · All Time",icon:<Crown/>,suffix:"solved"},{key:"rating",label:"Highest Puzzle Rating",icon:<Star/>,suffix:"rating"}]as const).map(item=>{const leader=state?.leaders?.[item.key];return <article key={item.key}>{leader?.avatar_url?<img src={leader.avatar_url} alt=""/>:<span className="leader-icon">{item.icon}</span>}<div><small>{item.label}</small><strong>{leader?.display_name||leader?.username||"No leader yet"}</strong><p>{leader?`${leader.value.toLocaleString()} ${item.suffix}`:"Complete a puzzle to rank"}</p></div></article>})}</section></div>
    </div>
  </section>
}
