"use client";
import {useEffect,useRef,useState} from 'react';
import jsQR from 'jsqr';
type Detector={detect:(source:HTMLVideoElement)=>Promise<Array<{rawValue:string}>>};
export default function QrInput({onValue,label='Scan QR code'}:{onValue:(value:string)=>void;label?:string}){
 const [manual,setManual]=useState(''),[active,setActive]=useState(false),[error,setError]=useState('');const video=useRef<HTMLVideoElement>(null),callback=useRef(onValue);callback.current=onValue;
 useEffect(()=>{if(!active)return;let stopped=false,stream:MediaStream|undefined,timer:ReturnType<typeof setTimeout>;const DetectorClass=(window as unknown as {BarcodeDetector?:new(options:{formats:string[]})=>Detector}).BarcodeDetector;
 async function start(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(stopped){stream.getTracks().forEach(t=>t.stop());return;}if(video.current){video.current.srcObject=stream;await video.current.play();}const detector=DetectorClass?new DetectorClass({formats:['qr_code']}):null,canvas=document.createElement('canvas');async function scan(){if(stopped)return;try{if(video.current&&video.current.readyState>=2){let value='';if(detector){const hits=await detector.detect(video.current);value=hits[0]?.rawValue??'';}else{const v=video.current;canvas.width=Math.min(960,v.videoWidth);canvas.height=Math.round(v.videoHeight*canvas.width/v.videoWidth);const ctx=canvas.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(v,0,0,canvas.width,canvas.height);const frame=ctx.getImageData(0,0,canvas.width,canvas.height);value=jsQR(frame.data,frame.width,frame.height)?.data??'';}if(value){callback.current(value);setActive(false);return;}}}catch{}timer=setTimeout(scan,300);}void scan();}catch(e){setError((e as Error).message);setActive(false);}}void start();return()=>{stopped=true;clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());};
 },[active]);
 return <div><button type="button" onClick={()=>{setError('');setActive(v=>!v);}}>{active?'Stop camera':label}</button>{active&&<video className="scan-video" ref={video} muted playsInline/>}<label>QR text or invitation link<textarea value={manual} onChange={e=>setManual(e.target.value)} placeholder="Paste the scanned QR text here"/></label><button type="button" disabled={!manual.trim()} onClick={()=>onValue(manual.trim())}>Use code</button>{error&&<p role="status">{error}</p>}</div>;
}
