export type Board={key:string;title:string;unit:string;description:string};
export const cbrBoard:Board={key:'cbr',title:'CBR Rankings',unit:'CBR',description:'Highest Chess Burger Rating. Wins break a tie. Daily CBG rewards apply to the top 10.'};
const b=(key:string,title:string,unit:string,description:string):Board=>({key,title,unit,description});
export const rankingModes=[
 {key:'puzzle',label:'Puzzle Quest',boards:[b('puzzle_today','Most solved today','solved','Resets at 12:01 AM Philippine time.'),b('puzzle_total','Most solved · all time','solved','Total successful Puzzle Quest solves.'),b('puzzle_rating','Highest puzzle rating','rating','Puzzle rating; total solves break a tie.'),b('puzzle_streak','Best solving streak','streak','Longest recorded correct-answer streak.')]},
 {key:'arena',label:'Grand Arena',boards:[b('arena_all','All-time Arena points','points','Session points combined. Wins break a tie.'),b('arena_today','Arena points today','points','Points from sessions scheduled today · Philippine time.'),b('arena_week','Arena points this week','points','Monday–Sunday · Philippine time.'),b('arena_session','Session standings','points','Checked-in players in the chosen session, including eliminated players. Registrations alone do not score.'),b('arena_champions','Session champions','titles','Number of awarded session championships.')]},
 {key:'math',label:'Chess Math',boards:[...(['easy','medium','hard'] as const).flatMap(level=>[b(`math_${level}_score`,`${level} · highest score`,'correct','Best completed attempt. Faster completion breaks a tie.'),b(`math_${level}_speed`,`${level} · fastest solver`,'ms / correct','Lowest time per correct answer. Fully answered quizzes with at least 70% accuracy.'),b(`math_${level}_finishers`,`${level} · top finishers`,'quizzes','Number of fully answered quizzes.')]),b('attack_score','Quiz Attack · best score','correct','Most correct answers in one finished attempt.'),b('attack_pace','Quiz Attack · best pace','correct / min','Fastest answering pace, with at least 10 correct answers.'),b('attack_total','Quiz Attack · lifetime','correct','All correct answers across completed attempts.')]},
 {key:'cpu',label:'Play with CPU',boards:[b('cpu_today','CPU wins today','wins','Wins today · Philippine time. CBR gained breaks a tie.'),b('cpu_week','CPU wins this week','wins','Monday–Sunday · Philippine time. CBR gained breaks a tie.'),b('cpu_all','CPU wins · all time','wins','Every recorded CPU victory. CBR gained breaks a tie.'),b('cpu_rapid','Rapid CPU wins','wins','All-time Rapid victories.'),b('cpu_blitz','Blitz CPU wins','wins','All-time Blitz victories.'),b('cpu_bullet','Bullet CPU wins','wins','All-time Bullet victories.')]},
 {key:'offline',label:'Offline Board',boards:[b('ocbr','Offline rankings','OCBR','Offline Chess Burger Rating, kept separate from CBR.')]},
];
export type RankingRow={rank:number;user_id:string;display_name:string|null;username:string|null;avatar_url:string|null;value:number;detail:string};
export type RankingResult={rows:RankingRow[];total:number;pages:number;page:number;page_size:number;mine:RankingRow|null;sessions?:{id:string;title:string;starts_at:string;ends_at:string}[]};
