'use client';
import {useEffect,useState} from 'react';
import {Crown,Medal,Swords,Trophy,X} from 'lucide-react';
import {arena} from './arena-client';
import {Avatar} from './match-board';
import {levelFor} from './cbr';
import type {ArenaPlayer} from './game-rules';
import type {PlayerProfile} from './supabase';
import './rank-player-card.css';

export default function Rankings({profile,onChallenge}:{profile:PlayerProfile|null;onChallenge:(player:ArenaPlayer)=>void}){
 const [players,setPlayers]=useState<ArenaPlayer[]>([]),[mine,setMine]=useState<{profile:PlayerProfile;rank:number}|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<ArenaPlayer|null>(null);
 useEffect(()=>{let alive=true;const load=async()=>{try{const d=await arena<{players:ArenaPlayer[]}>('ranks',{},true);if(alive){setPlayers(d.players);setSelected(current=>current?d.players.find(player=>player.user_id===current.user_id)??null:null);setError('');}if(profile&&profile.user_id!=='guest-device'){const m=await arena<{profile:PlayerProfile;rank:number}>('me');if(alive)setMine(m);}}catch(e){if(alive)setError((e as Error).message);}};void load();const timer=setInterval(load,15000);return()=>{alive=false;clearInterval(timer);};},[profile?.user_id]);
 const self=mine?.profile??profile;
 const dailyGold=(rank:number)=>rank===1?10:rank===2?9:rank===3?8:5;
 const selectedLevel=selected?levelFor(selected.cbr):null;
 const selectedGames=selected?selected.wins+selected.losses:0;
 const selectedRate=selectedGames&&selected?Math.round(selected.wins/selectedGames*100):0;
 return <section className="rank-page"><div className="page-heading"><h1>CBR Rankings</h1><span className="sample-label">Daily Gold rewards</span></div><div className="leaderboard cloud-leaderboard"><div className="leaderboard-heading"><h2>Top 10</h2><span>CBR / Daily reward</span></div>{players.map((p,i)=>{const Icon=[Crown,Medal,Trophy][i],rank=i+1;return <div className="ranking-line" key={p.user_id}><span className={'rank-number podium-'+i}>{Icon?<Icon aria-label={'Rank '+rank} size={19}/>:String(rank).padStart(2,'0')}</span><button type="button" className="rank-avatar-button" onClick={()=>setSelected(p)} aria-label={`Open ${p.display_name}'s player card`}><Avatar player={p}/>{p.online&&<i className="rank-online-dot" aria-label="Online"/>}</button><strong>{p.display_name}</strong><span className="rating">{p.cbr.toLocaleString()}<small>+{dailyGold(rank)} Gold / day</small></span></div>})}{!players.length&&<p className="account-note">{error||'Players will appear after signing in to the updated app.'}</p>}</div><div className="current-rank current-rank-bottom"><span>Your rank<strong>{mine?'#'+mine.rank:'Unranked'}</strong></span><span>CBR<strong>{self?.cbr??88}</strong></span><span>Level<strong>{levelFor(self?.cbr??88).level}</strong></span></div>{error&&players.length>0&&<p role="status">{error}</p>}{selected&&<div className="rank-card-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null);}}><article className="rank-player-card" role="dialog" aria-modal="true" aria-label={`${selected.display_name} player card`}><button type="button" className="rank-card-close" onClick={()=>setSelected(null)} aria-label="Close player card"><X/></button><div className="rank-card-profile"><span className="rank-card-avatar"><Avatar player={selected}/>{selected.online&&<i className="rank-online-dot"/>}</span><div><small>{selected.online?'ONLINE NOW':'OFFLINE'}</small><h2>{selected.display_name}</h2><p>@{selected.username} · {selected.country_code}</p></div></div><div className="rank-card-stats"><span><b>{selected.cbr.toLocaleString()}</b>CBR</span><span><b>{selectedLevel?.level??1}</b>Level</span><span><b>{selectedRate}%</b>Win rate</span></div><button type="button" className="rank-challenge-button" disabled={selected.user_id===profile?.user_id} onClick={()=>onChallenge(selected)}><Swords/>{selected.user_id===profile?.user_id?'Your player card':'Challenge player'}</button></article></div>}</section>;
}
