"use client";
import {useCallback,useEffect,useState} from "react";
import {classroom} from "./classroom-client";
import {toast} from "sonner";
import {Folder,FolderPlus,PenLine,Save,Send,X} from "lucide-react";
import "./seba-material-library.css";
type Puzzle={id:string;title:string;fen:string;hint:string;moves:string[];theme:string};
type FolderRow={id:string;name:string};type Material={id:string;folder_id:string;name:string;fen:string;annotations:unknown[];source_puzzle_id:string|null;hint:string;solution:string[]};
async function query<T>(action:string,body:Record<string,unknown>={}){return classroom<T>(`library-${action}`,body)}
export default function SebaMaterialLibrary({roomId,fen,annotations,puzzle,onClose,onLoad,onAssign}:{roomId:string;fen:string;annotations:unknown[];puzzle?:Puzzle|null;onClose:()=>void;onLoad:(material:Material)=>void;onAssign:(material:Material)=>void}){
 const [folders,setFolders]=useState<FolderRow[]>([]),[materials,setMaterials]=useState<Material[]>([]),[folder,setFolder]=useState(""),[name,setName]=useState(puzzle?.title||""),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState<string|null>(null),[error,setError]=useState("");
 const refresh=useCallback(async()=>{try{const data=await query<{folders:FolderRow[];materials:Material[]}>("list");setFolders(data.folders);setMaterials(data.materials);setFolder(current=>current||data.folders[0]?.id||"");setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load library.")}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 const act=async(action:string,body:Record<string,unknown>={})=>{setBusy(true);try{await query(action,{room_id:roomId,...body});await refresh();toast.success("Library updated.")}catch(e){toast.error(e instanceof Error?e.message:"Library action failed.")}finally{setBusy(false)}};
 const createFolder=()=>{const value=window.prompt("New folder name")?.trim();if(value)void act("folder-create",{name:value})};
 const save=()=>{if(!folder)return toast.error("Create a folder first.");if(!name.trim())return toast.error("Name the position first.");void act("save",{folder_id:folder,name:name.trim(),fen:puzzle?.fen||fen,annotations:puzzle?[]:annotations,source_puzzle_id:puzzle?.id,hint:puzzle?.hint,solution:puzzle?.moves})};
 return <div className="seba-material-overlay" role="dialog" aria-modal="true" aria-label="My teaching library"><section className="seba-material-panel"><header><div><small>SEba · TEACHER MATERIALS</small><h2>My teaching library</h2><p>Keep your positions and puzzles in private folders.</p></div><button aria-label="Close library" onClick={onClose}><X size={18}/></button></header>{error&&<p role="alert" className="seba-material-error">{error}</p>}
 <div className="seba-material-body"><aside><div className="seba-material-side-title"><b>Folders</b><button title="Create folder" onClick={createFolder}><FolderPlus size={16}/></button></div>{folders.map(f=><div key={f.id} className={`seba-material-folder ${folder===f.id?"active":""}`}><button onClick={()=>setFolder(f.id)}><Folder size={15}/><span>{f.name}</span></button><button title="Rename folder" aria-label={`Rename ${f.name}`} onClick={()=>{const value=window.prompt("Rename folder",f.name)?.trim();if(value&&value!==f.name)void act("folder-rename",{folder_id:f.id,name:value})}}><PenLine size={13}/></button></div>)}{!folders.length&&<p>Create a folder to begin.</p>}</aside><div className="seba-material-content"><div className="seba-material-save"><div><b>{puzzle?`Save puzzle: ${puzzle.title}`:"Save current teacher board"}</b><small>{puzzle?"Hint and solution will be saved with the puzzle.":"Keep this board position and its annotations."}</small></div><input value={name} maxLength={90} aria-label="Material name" onChange={e=>setName(e.target.value)} placeholder="Position name"/><button disabled={busy||!folder} onClick={save}><Save size={14}/>Save</button></div><div className="seba-material-list"><h3>{folders.find(f=>f.id===folder)?.name||"Choose a folder"} <span>{materials.filter(m=>m.folder_id===folder).length} materials</span></h3>{materials.filter(m=>m.folder_id===folder).map(m=><article key={m.id}><div><strong>{m.name}</strong><small>{m.source_puzzle_id?"PUZZLE · ":"POSITION · "}{m.fen.split(" ")[1]==="w"?"White":"Black"} to move</small></div><div className="seba-material-row-actions"><button title="Load on teacher board" onClick={()=>{onLoad(m);onClose()}}>Load</button><button title="Assign to students" onClick={()=>{onAssign(m);onClose()}}><Send size={13}/>Assign</button><button title="Guide and details" onClick={()=>setExpanded(expanded===m.id?null:m.id)}>Guide</button><button title="Rename material" aria-label={`Rename ${m.name}`} onClick={()=>{const value=window.prompt("Rename material",m.name)?.trim();if(value&&value!==m.name)void act("rename",{material_id:m.id,name:value})}}><PenLine size={13}/></button></div>{expanded===m.id&&<p className="seba-material-guide">{m.hint||"Custom board position"}{m.solution?.length?` · Solution: ${m.solution.join(" → ")}`:""}</p>}</article>)}{folder&&!materials.some(m=>m.folder_id===folder)&&<p className="seba-material-empty">No saved materials in this folder yet.</p>}</div></div></div></section></div>
}
