"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Chess,type Square} from "chess.js";
import {getSupabase} from "./supabase";
import {toast} from "sonner";
import "./seba-tournament.css";
type Person={user_id:string;student_name:string;points:number;rank:number;wins:number};
type Game={id:string;white_id:string;black_id:string|null;fen:string|null;status:string;result:string|null;round:number;white_ms:number;black_ms:number;last_move_at:string};
type Certificate={id:string;student_name:string;title:string;coach_name:string;session_started_at:string;rank:number|null;issued_at:string};
type State={tournament:{id:string;title:string;coach_name:string;status:string;current_round:number;total_rounds:number;time_minutes:number;increment_seconds:number;ai_level:number;certificates_published:boolean}|null;standings:Person[];games:Game[];online:{user_id:string;name:string}[];certificates:Certificate[];teacher:boolean};
const glyph:Record<string,string>={wp:"♙",wn:"♘",wb:"♗",wr:"♖",wq:"♕",wk:"♔",bp:"♟",bn:"♞",bb:"♝",br:"♜",bq:"♛",bk:"♚"};
async function request<T>(action:string,room_id:string,body:Record<string,unknown>={}):Promise<T>{const client=await getSupabase(),session=client?(await client.auth.getSession()).data.session:null;if(!session)throw Error("Sign in to use the classroom.");const response=await fetch("/api/classroom-tournament",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,room_id,...body}),cache:"no-store"});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error||"Tournament unavailable.");return data as T}
const clock=(ms:number)=>`${Math.floor(Math.max(0,ms)/60000)}:${String(Math.floor(Math.max(0,ms)%60000/1000)).padStart(2,"0")}`;
export default function SebaTournament({roomId,teacher,ownId,archive=false}:{roomId:string;teacher:boolean;ownId?:string|null;archive?:boolean}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[minutes,setMinutes]=useState(10),[increment,setIncrement]=useState(0),[rounds,setRounds]=useState(3),[level,setLevel]=useState(5),[selected,setSelected]=useState<Square|null>(null),[promotion,setPromotion]=useState<{from:Square;to:Square}|null>(null),[certificate,setCertificate]=useState<Certificate|null>(null),[now,setNow]=useState(Date.now());
 const refresh=useCallback(async()=>{try{const next=await request<State>("state",roomId);setState(next);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load tournament.")}},[roomId]);
 useEffect(()=>{void request("presence",roomId).catch(()=>{});void refresh();const pulse=setInterval(()=>{void request("presence",roomId).catch(()=>{});void refresh()},15000),tick=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(pulse);clearInterval(tick)}},[refresh,roomId]);
 const run=async(action:string,body:Record<string,unknown>={})=>{setBusy(true);try{await request(action,roomId,body);await refresh();toast.success(action==="certificate"?"Certificates are ready for students.":"Tournament updated.")}catch(e){toast.error(e instanceof Error?e.message:"Tournament action failed.")}finally{setBusy(false)}};
 const removeCertificates=async(certificateId?:string)=>{const message=certificateId?"Delete this certificate? The teacher can generate it again later.":"Delete every certificate in this classroom? You can generate them again afterward.";if(!window.confirm(message))return;await run(certificateId?"certificate-delete":"certificate-clear",certificateId?{certificate_id:certificateId}:{})};
 const t=state?.tournament,game=state?.games.find(g=>g.status==="playing"&&(g.white_id===ownId||g.black_id===ownId))||state?.games.find(g=>g.round===t?.current_round)||null;
 const board=useMemo(()=>{try{return new Chess(game?.fen||undefined)}catch{return new Chess()}},[game?.fen]);const myColor=game?.white_id===ownId?"w":game?.black_id===ownId?"b":null;const myTurn=Boolean(myColor&&board.turn()===myColor&&game?.status==="playing");
 const available=selected&&myTurn?board.moves({square:selected,verbose:true}).map(m=>m.to):[];
 const play=(from:Square,to:Square,piece?:string)=>{setPromotion(null);setSelected(null);void run("move",{game_id:game?.id,from,to,promotion:piece||"q"})};
 const choose=(square:Square)=>{if(!myTurn||busy)return;const piece=board.get(square);if(selected&&available.includes(square)){const origin=board.get(selected);if(origin?.type==="p"&&(square.endsWith("8")||square.endsWith("1")))setPromotion({from:selected,to:square});else play(selected,square);return}setSelected(piece?.color===myColor?square:null)};
 const name=(id:string|null)=>id?state?.standings.find(p=>p.user_id===id)?.student_name||"Student":`AI level ${t?.ai_level||1}`;
 const remaining=(color:"white"|"black")=>{if(!game)return 0;const base=color==="white"?game.white_ms:game.black_ms;if(game.status!=="playing"||board.turn()!==(color==="white"?"w":"b"))return base;return Math.max(0,base-(now-new Date(game.last_move_at).getTime()))};
 useEffect(()=>{if(game?.status!=="playing"||!ownId)return;const color=board.turn()==="w"?"white":"black",ms=remaining(color);if(ms>0)return;const timeout=setTimeout(()=>void run("timeout",{game_id:game.id}),1000);return()=>clearTimeout(timeout)},[game?.id,game?.status,game?.last_move_at,now,ownId]);
 return <section className="seba-tournament" aria-label="Classroom mini tournament"><div className="seba-tournament-heading"><span className="seba-tournament-badge">♞ SEba CHESS</span><h2>Classroom mini tournament</h2><p>Play classmates in timed rounds. Your ranking updates as games finish.</p></div>
 {error&&<p role="alert" className="seba-tournament-error">{error}</p>}
 {teacher&&!archive&&!t?.status?.includes("running")&&<div className="seba-tournament-setup"><div><strong>Set up the next tournament</strong><small>{state?.online.length||0} students online in this classroom</small></div><div className="seba-tournament-fields"><label>Time control<select value={`${minutes}+${increment}`} onChange={e=>{const [m,i]=e.target.value.split("+").map(Number);setMinutes(m);setIncrement(i)}}>{["3+0","5+0","10+0","15+10","30+0"].map(v=><option key={v}>{v}</option>)}</select></label><label>Rounds<select value={rounds} onChange={e=>setRounds(Number(e.target.value))}>{Array.from({length:10},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><label>Odd player · AI level<select value={level} onChange={e=>setLevel(Number(e.target.value))}>{Array.from({length:10},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label></div><button disabled={busy||!state?.online.length} onClick={()=>void run("create",{minutes,increment,rounds,ai_level:level})}>Start tournament</button></div>}
 {t&&!archive&&<div className="seba-tournament-content"><div className="seba-tournament-status"><strong>{t.status==="finished"?"Final standings":`Round ${t.current_round} of ${t.total_rounds}`}</strong><span>{t.time_minutes}+{t.increment_seconds} min · AI level {t.ai_level}</span></div><div className="seba-tournament-columns"><div><h3>Rankings</h3><ol className="seba-rankings">{state?.standings.map(p=><li key={p.user_id}><b>#{p.rank}</b><span>{p.student_name}</span><strong>{p.points} pts</strong></li>)}</ol><h3>Round games</h3><div className="seba-game-list">{state?.games.filter(g=>g.round===t.current_round).map(g=><div key={g.id} className={g.id===game?.id?"current":""}><span>{name(g.white_id)} vs {name(g.black_id)}</span><b>{g.status==="finished"?(g.result==="draw"?"½–½":g.result==="white"?"1–0":"0–1"):"Playing"}</b></div>)}</div>{teacher&&t.status==="running"&&<div className="seba-tournament-actions"><button disabled={busy||state?.games.some(g=>g.round===t.current_round&&g.status!=="finished")} onClick={()=>void run(t.current_round<t.total_rounds?"next":"finish")}>{t.current_round<t.total_rounds?"Start next round":"Finish tournament"}</button></div>}</div><div className="seba-game-panel"><h3>{game?`${name(game.white_id)} vs ${name(game.black_id)}`:"Awaiting pairings"}</h3>{game&&game.fen&&<><div className="seba-game-clock"><span>Black · {clock(remaining("black"))}</span><span>{game.status==="finished"?"Game finished":myTurn?"Your move":"Waiting"}</span></div><div className="seba-game-board">{board.board().flatMap((rank,r)=>rank.map((piece,c)=>{const sq=(`${"abcdefgh"[c]}${8-r}`) as Square;return <button type="button" key={sq} className={`${(r+c)%2?"dark":"light"} ${selected===sq?"selected":""} ${available.includes(sq)?"available":""}`} aria-label={`${sq} ${piece?piece.color+piece.type:"empty"}`} onClick={()=>choose(sq)}>{piece?glyph[piece.color+piece.type]:""}</button>}))}</div><div className="seba-game-clock"><span>White · {clock(remaining("white"))}</span><span>{board.isCheckmate()?"Checkmate":board.isCheck()?"Check":""}</span></div>{promotion&&<div className="seba-promotion" role="dialog" aria-label="Choose promotion"><strong>Promote pawn</strong>{["q","r","b","n"].map(piece=><button key={piece} onClick={()=>play(promotion.from,promotion.to,piece)}>{glyph[(myColor||"w")+piece]}</button>)}</div>}</>}{game&&!game.fen&&<p>Play your own game to see its board. Results appear here when games finish.</p>}</div></div></div>}
 {teacher&&!archive&&<div className="seba-certificate-publish"><div><strong>Classroom certificates</strong><p>Generate certificates after a lesson, or after the tournament for ranked certificates.</p></div><button disabled={busy||t?.status==="running"} onClick={()=>void run("certificate")}>Generate certificates</button></div>}
 {archive&&!state?.certificates.length&&!error&&<p>No certificates issued for this session yet.</p>}
 {!!state?.certificates.length&&<div className="seba-certificates"><header><h3>Certificates</h3>{teacher&&!archive&&<button type="button" className="seba-certificates-clear" disabled={busy} onClick={()=>void removeCertificates()}>Delete all</button>}</header><div>{state.certificates.map(c=><div className="seba-certificate-entry" key={c.id}><button className="seba-certificate-row" title={`${c.title} · Coach ${c.coach_name} · ${new Date(c.session_started_at).toLocaleString()}`} onClick={()=>setCertificate(c)}><span className="seba-certificate-row-icon">✦</span><strong>{c.student_name}</strong><small>{c.rank?`#${c.rank} · `:""}{new Date(c.issued_at).toLocaleDateString()}</small><span className="seba-certificate-row-arrow">View ↗</span><span className="seba-certificate-row-detail" aria-hidden="true">{c.title} · Coach {c.coach_name} · {new Date(c.session_started_at).toLocaleString()}</span></button>{teacher&&!archive&&<button type="button" className="seba-certificate-delete" disabled={busy} aria-label={`Delete certificate for ${c.student_name}`} onClick={()=>void removeCertificates(c.id)}>Delete</button>}</div>)}</div></div>}
 {certificate&&<div className="seba-certificate-overlay" role="dialog" aria-modal="true" aria-label="Classroom certificate" onClick={()=>setCertificate(null)}><div className="seba-certificate-shell" onClick={e=>e.stopPropagation()}><button className="seba-certificate-close" onClick={()=>setCertificate(null)}>Close ×</button><div className="seba-certificate-paper"><div className="seba-certificate-border"><img src="/seba-certificate-logo.png" alt="Chess Burger logo"/><span className="seba-certificate-brand">CHESS BURGER</span><small>SEba CLASSROOM</small><h2>Certificate of Achievement</h2><p>Presented to</p><h3>{certificate.student_name}</h3><p>for participating in</p><strong>{certificate.title}</strong>{certificate.rank&&<div className="seba-certificate-rank">Tournament ranking · #{certificate.rank}</div>}<div className="seba-certificate-footer"><span>Session started<br/><b>{new Date(certificate.session_started_at).toLocaleString()}</b></span><span>Coach<br/><b>{certificate.coach_name}</b></span></div></div></div><p className="seba-certificate-tip">Certificate expanded · take a screenshot to save it</p></div></div>}
 </section>
}
