"use client";
import {useCallback,useEffect,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {toast} from 'sonner';
import {getSupabase,PlayerProfile} from './supabase';
import QrInput from './qr-input';
import {Tournament,Result,assertReady,exportTrf,pairOffline,parseTournament,standings,validatePairs} from './tournament-engine';
const KEY='cb-tournaments-v8';
function readLocal():Tournament[]{try{return JSON.parse(localStorage.getItem(KEY)??'[]').map(parseTournament);}catch{return [];}}
function saveLocal(t:Tournament){const all=readLocal();localStorage.setItem(KEY,JSON.stringify([t,...all.filter(x=>x.id!==t.id)]));}
function audit(t:Tournament,action:string){const key='cb-offline-audit';const items=JSON.parse(localStorage.getItem(key)??'[]');localStorage.setItem(key,JSON.stringify([{at:new Date().toISOString(),actor:t.hostName,action,tournament:t.title},...items].slice(0,200)));}
function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
type Invite={id:string;code:string;title:string;hostName:string};
export default function Tournaments({profile,host=false}:{profile:PlayerProfile|null;host?:boolean}){
 const[all,setAll]=useState<Tournament[]>([]),[event,setEvent]=useState<Tournament|null>(null),[title,setTitle]=useState(''),[rounds,setRounds]=useState(5),[mode,setMode]=useState<'offline'|'api'>('offline'),[names,setNames]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[invite,setInvite]=useState<Invite|null>(null),[joinQr,setJoinQr]=useState(''),[joinName,setJoinName]=useState(profile?.display_name??''),[registrations,setRegistrations]=useState<Array<{user_id:string;display_name:string}>>([]);
 const staff=host&&!!profile&&['owner','admin'].includes(profile.role),editable=staff&&event?.hostId===profile?.user_id;
 useEffect(()=>{setAll(readLocal());let live=true;if(host&&profile&&navigator.onLine)void getSupabase().then(async c=>{if(!c)return;const{data,error}=await c.from('cb_tournaments').select('state,revision').eq('host_id',profile.user_id).order('updated_at',{ascending:false});if(error||!live)return;const local=readLocal();const remote=(data??[]).map((row:{state:unknown;revision:number})=>({...parseTournament(row.state),revision:row.revision}));const merged=[...local,...remote.filter((r:Tournament)=>!local.some(l=>l.id===r.id))];localStorage.setItem(KEY,JSON.stringify(merged));setAll(merged);}).catch(()=>{});return()=>{live=false;};},[host,profile?.user_id]);
 const receiveInvite=useCallback((raw:string)=>{try{let data:unknown;if(raw.includes('#tournament=')){data=JSON.parse(decodeURIComponent(raw.split('#tournament=')[1]));}else data=JSON.parse(raw);const d=data as Invite&{type:string};if(d.type!=='cb-tournament'||!d.id?.match(/^[0-9a-f-]{36}$/i)||!d.code?.match(/^[A-Z0-9]{8}$/)||typeof d.title!=='string'||typeof d.hostName!=='string')throw Error();setInvite(d);setNotice('Invitation loaded. Register online or show the host your registration QR.');}catch{toast.error('This is not a Chess Burger tournament invitation.');}},[]);
 useEffect(()=>{if(window.location.hash.startsWith('#tournament='))receiveInvite(window.location.href);},[receiveInvite]);
 function persist(next:Tournament,action:string){const saved={...next,updatedAt:new Date().toISOString()};saveLocal(saved);audit(saved,action);setEvent(saved);setAll(readLocal());return saved;}
 async function sync(t:Tournament){const c=await getSupabase();if(!c)throw Error('Connect your account to publish this tournament.');const {data,error}=await c.rpc('cb_save_tournament',{p_id:t.id,p_code:t.code,p_title:t.title,p_state:t,p_revision:t.revision??0});if(error)throw Error(error.message);const saved={...t,revision:Number(data)};saveLocal(saved);setEvent(saved);setAll(readLocal());return saved;}
 async function perform(action:()=>Promise<void>){setBusy(true);setNotice('');try{await action();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 function create(){if(!staff||!profile)return;if(!title.trim()||!Number.isInteger(rounds)||rounds<1||rounds>23){setNotice('Enter a title and 1–23 rounds.');return;}const t:Tournament={id:crypto.randomUUID(),code:crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase(),title:title.trim().slice(0,100),hostId:profile.user_id,hostName:profile.display_name,rounds,mode,players:[],history:[],status:'registration',updatedAt:new Date().toISOString()};persist(t,'Created offline tournament');setNotice('Registration is open. Add players or share the host QR.');}
 function addNames(){if(!event||!editable||event.status!=='registration')return;const incoming=names.split(/\n|,/).map(n=>n.trim()).filter(Boolean);const players=[...event.players];for(const name of incoming){if(name.length>60){setNotice('Player names must be 60 characters or fewer.');return;}if(!players.some(p=>p.name.toLowerCase()===name.toLowerCase()))players.push({id:players.length+1,name,rating:0});}if(players.length>100){setNotice('Maximum 100 players per event.');return;}persist({...event,players},'Added players');setNames('');}
 const acceptQr=useCallback((raw:string)=>{try{if(!event||!editable||event.status!=='registration')throw Error('Registration is closed.');const d=JSON.parse(raw.includes('#registration=')?decodeURIComponent(raw.split('#registration=')[1]):raw);if(d.type!=='cb-registration'||d.eventId!==event.id||d.code!==event.code||typeof d.name!=='string'||!d.name.trim()||d.name.length>60)throw Error('Registration QR does not match this tournament.');if(event.players.some(p=>p.name.toLowerCase()===d.name.toLowerCase()))throw Error('This player is already registered.');if(event.players.length>=100)throw Error('The event is full.');persist({...event,players:[...event.players,{id:event.players.length+1,name:d.name.trim(),rating:0}]},'Accepted QR registration');toast.success('Player added. Offline identity is confirmed by the host.');}catch(e){toast.error((e as Error).message);}},[event,editable]);
 async function nextRound(){if(!event||!editable)return;assertReady(event);let pairs;if(event.mode==='offline'){pairs=pairOffline(event);}else{const c=await getSupabase();const session=await c?.auth.getSession();const token=session?.data.session?.access_token;if(!token)throw Error('Sign in and connect to the internet to use the Swiss API.');const r=await fetch('/api/swiss',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({trf:exportTrf(event)})});const data=await r.json() as {error?:string;pairings:unknown;round?:number};if(!r.ok)throw Error(data.error??'Pairing service is unavailable.');if(data.round!==undefined&&Number(data.round)!==event.history.length+1)throw Error("The provider returned the wrong round number.");pairs=validatePairs(event,data.pairings);}
 const next=persist({...event,status:'playing',history:[...event.history,pairs]},'Paired round '+(event.history.length+1));if(navigator.onLine&&next.revision){try{await sync(next);}catch(e){setNotice('Saved on this device. '+(e as Error).message);}}}
 function result(board:number,value:Result){if(!event||!editable||event.status==='completed')return;const history=event.history.map(r=>r.map(g=>({...g})));history[history.length-1][board].result=value;persist({...event,history},'Recorded round '+history.length+' board '+(board+1));}
 async function loadRegistrations(){if(!event)return;const c=await getSupabase();if(!c)throw Error('Connect to load registrations.');const{data,error}=await c.from('cb_tournament_entries').select('user_id,display_name').eq('tournament_id',event.id);if(error)throw Error(error.message);setRegistrations(data??[]);}
 function acceptOnline(){if(!event||!editable||event.status!=='registration')return;const players=[...event.players];for(const p of registrations)if(!players.some(x=>x.userId===p.user_id||x.name.toLowerCase()===p.display_name.toLowerCase()))players.push({id:players.length+1,name:p.display_name,userId:p.user_id,rating:0});if(players.length>100){setNotice('The event exceeds 100 players.');return;}persist({...event,players},'Accepted online registrations');setRegistrations([]);}
 async function register(){if(!invite)return;const c=await getSupabase();if(!c)throw Error('Sign in or use the offline registration QR.');const {error}=await c.rpc('cb_join_tournament',{p_id:invite.id,p_code:invite.code});if(error)throw Error(error.message);setNotice('Registered online. The host will add you to the roster.');}
 async function refreshOnline(){if(!event)return;const c=await getSupabase();if(!c)throw Error('Connect to load the saved event.');const{data,error}=await c.from('cb_tournaments').select('state,revision').eq('id',event.id).single();if(error)throw Error(error.message);const next={...parseTournament(data.state),revision:data.revision};saveLocal(next);setEvent(next);setAll(readLocal());setNotice('Loaded the published version.');}
 const qr=event?JSON.stringify({type:'cb-tournament',id:event.id,code:event.code,title:event.title,hostName:event.hostName}):'';
 const qrLink=event&&typeof window!=='undefined'?window.location.origin+'/#tournament='+encodeURIComponent(qr):'';
 return <div className="cms-panel"><h2>{staff?'Tournament host':'Join a tournament'}</h2>{notice&&<p className="offline-banner" role="status">{notice}</p>}
 {staff&&!event&&<><div className="cms-grid"><label>Tournament name<input maxLength={100} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Rounds<input type="number" min={1} max={23} value={rounds} onChange={e=>setRounds(Number(e.target.value))}/></label></div><label>Pairing engine<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="offline">Offline club Swiss</option><option value="api">Online Swiss REST API</option></select></label><button onClick={create}>Create tournament</button><p className="cms-note">Offline club pairings work on this device. The online engine needs a configured API key. Have an arbiter verify pairings for rated events.</p>{all.filter(t=>t.hostId===profile?.user_id).map(t=><button key={t.id} onClick={()=>setEvent(t)}>{t.title} · {t.history.length}/{t.rounds} rounds</button>)}<label className="import-label">Restore tournament backup<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)void perform(async()=>{if(file.size>2_000_000)throw Error('Backup is too large.');const t=parseTournament(JSON.parse(await file.text()));if(t.hostId!==profile?.user_id)throw Error('This backup belongs to another host account.');persist(t,'Restored backup');});}}/></label></>}
 {staff&&event&&<><div className="cms-actions"><button onClick={()=>setEvent(null)}>All tournaments</button><button disabled={busy} onClick={()=>void perform(async()=>{await sync(event);setNotice('Tournament published and activity logged.');})}>Publish / sync</button><button disabled={busy||!event.revision} onClick={()=>void perform(refreshOnline)}>Load published version</button></div><h3>{event.title}</h3><p className="tournament-state">Host: {event.hostName} · {event.status} · {event.mode==='offline'?'Offline club Swiss':'Swiss REST API'}</p><p className="cms-note">Saved on this device. Export a backup after each round. Publishing saves the host state online; loading the published version replaces local changes.</p>{editable&&event.status==='registration'&&<><div className="tournament-qr"><QRCodeSVG value={qrLink} size={240}/><strong>{event.code}</strong><span>Players scan this invitation, then show their registration QR to the host.</span></div><label>Players · one per line<textarea value={names} onChange={e=>setNames(e.target.value)}/></label><button onClick={addNames}>Add players</button><QrInput label="Scan player registration" onValue={acceptQr}/><div className="cms-actions"><button disabled={busy} onClick={()=>void perform(loadRegistrations)}>Load online registrations</button>{registrations.length>0&&<button onClick={acceptOnline}>Accept {registrations.length} registrations</button>}</div></>}
 <div className="standings"><table><thead><tr><th>Rank</th><th>Player</th><th>Score</th><th>Buchholz</th></tr></thead><tbody>{standings(event).map((p,i)=><tr key={p.id}><td>{i+1}</td><td>{p.name}</td><td>{p.score}</td><td>{p.buchholz}</td></tr>)}</tbody></table></div>
 {event.history.map((round,ri)=><div className="pair-list" key={ri}><h3>Round {ri+1}</h3>{round.map((g,bi)=><article key={bi}><strong>Board {bi+1}</strong><span>{event.players.find(p=>p.id===g.white)?.name} (White) · {g.black?event.players.find(p=>p.id===g.black)?.name+' (Black)':'BYE'}</span>{g.black&&ri===event.history.length-1&&editable&&event.status!=='completed'?<label>Result<select value={g.result} onChange={e=>result(bi,e.target.value as Result)}><option value="">Awaiting result</option><option value="1-0">White wins · 1–0</option><option value="0-1">Black wins · 0–1</option><option value="1/2-1/2">Draw · ½–½</option></select></label>:<span>{g.result||'Awaiting result'}</span>}</article>)}</div>)}
 {editable&&event.status!=='completed'&&<div className="cms-actions">{event.history.length<event.rounds?<button disabled={busy||event.players.length<2||event.history.at(-1)?.some(g=>!g.result)} onClick={()=>void perform(nextRound)}>Pair round {event.history.length+1}</button>:<button disabled={event.history.at(-1)?.some(g=>!g.result)} onClick={()=>persist({...event,status:'completed'},'Completed tournament')}>Complete tournament</button>}</div>}
 <div className="cms-actions"><button onClick={()=>download('chess-burger-'+event.code+'.json',JSON.stringify(event,null,2))}>Export backup</button><button disabled={busy||event.history.at(-1)?.some(g=>!g.result)} onClick={()=>void perform(async()=>download('chess-burger-'+event.code+'.trf',exportTrf(event),'text/plain'))}>Export TRF</button></div></>}
 {!staff&&<><QrInput onValue={receiveInvite}/>{invite&&<><h3>{invite.title}</h3><p>Host: {invite.hostName} · Code: {invite.code}</p><button disabled={busy} onClick={()=>void perform(register)}>Register online</button><label>Name for offline registration<input maxLength={60} value={joinName} onChange={e=>setJoinName(e.target.value)}/></label><button disabled={!joinName.trim()} onClick={()=>setJoinQr(JSON.stringify({type:'cb-registration',eventId:invite.id,code:invite.code,name:joinName.trim()}))}>Create my registration QR</button>{joinQr&&<div className="tournament-qr"><QRCodeSVG value={joinQr} size={240}/><span>Show this QR to the host to finish joining.</span><textarea aria-label="Registration QR text" readOnly value={joinQr}/></div>}<p className="cms-note">Offline joining uses two scans: your phone reads the host invitation, then the host reads your registration. Both devices must have opened the app online first. Play on a physical board or the app’s offline board; the host records results.</p></>}</>}
 </div>;
}
