import {createClient} from "@supabase/supabase-js";
import {Chess} from "chess.js";
import {DAILY_PUZZLES} from "../app/puzzle-data";
type Req={method?:string;headers:{authorization?:string|string[]};body?:Record<string,unknown>};
type Res={status:(n:number)=>Res;json:(v:unknown)=>void;setHeader:(k:string,v:string)=>void};
const fail=(status:number,message:string):never=>{throw Object.assign(new Error(message),{status})};
const uuid=(v:unknown)=>/^[a-f0-9]{8}-[a-f0-9-]{27}$/i.test(String(v||""));
export default async function handler(req:Req,res:Res){res.setHeader("Cache-Control","no-store");try{
 if(req.method!=="POST")fail(405,"POST required.");const url=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.VITE_SUPABASE_URL||process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)fail(503,"Classroom server unavailable.");const db=createClient(url!,key!,{auth:{persistSession:false}}),raw=req.headers.authorization,token=(Array.isArray(raw)?raw[0]:raw||"").replace(/^Bearer\s+/i,"");const auth=await db.auth.getUser(token);if(auth.error||!auth.data.user)fail(401,"Please sign in again.");const userId=auth.data.user!.id,body=req.body||{},action=String(body.action||"");
 const q=async(query:any)=>{const result=await query;if(result.error)fail(500,result.error.message);return result.data};
 if(action==="list"){const [folders,materials]=await Promise.all([q(db.from("cb_seba_folders").select("id,name,created_at").eq("teacher_id",userId).order("created_at")),q(db.from("cb_seba_materials").select("id,folder_id,name,fen,annotations,source_puzzle_id,hint,solution,updated_at").eq("teacher_id",userId).order("updated_at",{ascending:false}).limit(300))]);return res.status(200).json({folders,materials})}
 const roomId=String(body.room_id||"");if(!uuid(roomId))fail(400,"Choose an active classroom.");const room=await q(db.from("cb_classroom_rooms").select("id").eq("id",roomId).eq("teacher_id",userId).eq("status","active").gt("expires_at",new Date().toISOString()).maybeSingle());if(!room)fail(403,"Only the active teacher can edit teaching materials.");
 if(action==="folder-create"){const name=String(body.name||"").trim().slice(0,60);if(!name)fail(400,"Name your folder.");const folder=await q(db.from("cb_seba_folders").insert({teacher_id:userId,name}).select("id,name").single());return res.status(200).json({folder})}
 if(action==="folder-rename"){if(!uuid(body.folder_id))fail(400,"Choose a folder.");const name=String(body.name||"").trim().slice(0,60);if(!name)fail(400,"Name your folder.");const folder=await q(db.from("cb_seba_folders").update({name}).eq("teacher_id",userId).eq("id",String(body.folder_id)).select("id,name").maybeSingle());if(!folder)fail(404,"Folder not found.");return res.status(200).json({folder})}
 if(action==="save"){const folderId=String(body.folder_id||"");if(!uuid(folderId))fail(400,"Choose a folder.");const folder=await q(db.from("cb_seba_folders").select("id").eq("id",folderId).eq("teacher_id",userId).maybeSingle());if(!folder)fail(403,"This is not your folder.");const name=String(body.name||"").trim().slice(0,90);if(!name)fail(400,"Name the material.");const sourceId=String(body.source_puzzle_id||"");const puzzle=sourceId?DAILY_PUZZLES.find(p=>p.id===sourceId):null;if(sourceId&&!puzzle)fail(400,"Puzzle not found.");let fen=puzzle?.fen||String(body.fen||"");try{fen=new Chess(fen==="start"?undefined:fen,{skipValidation:true}).fen()}catch{fail(400,"Invalid board position.")}const annotations=Array.isArray(body.annotations)?body.annotations.slice(0,120):[];const material=await q(db.from("cb_seba_materials").insert({teacher_id:userId,folder_id:folderId,name,fen,annotations,source_puzzle_id:puzzle?.id||null,hint:puzzle?.hint||"",solution:puzzle?.moves||[]}).select("id").single());return res.status(200).json({material})}
 if(action==="rename"){const id=String(body.material_id||""),name=String(body.name||"").trim().slice(0,90);if(!uuid(id)||!name)fail(400,"Choose and name a material.");const material=await q(db.from("cb_seba_materials").update({name,updated_at:new Date().toISOString()}).eq("id",id).eq("teacher_id",userId).select("id").maybeSingle());if(!material)fail(404,"Material not found.");return res.status(200).json({material})}
 fail(400,"Unknown material action.");
 }catch(e){const error=e as Error&{status?:number};return res.status(error.status||500).json({error:error.message||"Could not update library."})}}
