import {createClient} from "@supabase/supabase-js";
import {Chess} from "chess.js";
import {hashCode,issueProof,unseal,type CertificateRow} from "./_certificate-proof.js";
type Req={method?:string;headers:{authorization?:string|string[]};body?:Record<string,unknown>};
type Res={status:(n:number)=>Res;json:(v:unknown)=>void;setHeader:(k:string,v:string)=>void};
const err=(status:number,message:string):never=>{throw Object.assign(new Error(message),{status})};
const uuid=(v:unknown)=>/^[a-f0-9-]{36}$/i.test(String(v||""));
const material:Record<string,number>={p:1,n:3,b:3,r:5,q:9,k:0};
function aiMove(board:Chess,level:number){const moves=board.moves({verbose:true});if(!moves.length)return null;const scored=moves.map(move=>{const next=new Chess(board.fen());next.move(move);let score=(move.captured?material[move.captured]:0)*10+(move.promotion?material[move.promotion]*8:0)+(next.isCheckmate()?10000:next.isCheck()?2:0);if(level>=5){const replies=next.moves({verbose:true});score-=Math.max(0,...replies.map(reply=>(reply.captured?material[reply.captured]:0)*10+(reply.promotion?material[reply.promotion]*8:0)))*(level-3)/7}return {move,score:score+(Math.random()-.5)*(11-level)*4}}).sort((a,b)=>b.score-a.score);return scored[0].move}
export default async function handler(req:Req,res:Res){res.setHeader("Cache-Control","no-store");try{
 if(req.method!=="POST")err(405,"Method not allowed.");const url=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.VITE_SUPABASE_URL||process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)err(503,"Classroom database is not configured.");
 const db=createClient(url!,key!,{auth:{persistSession:false}}),body=req.body||{},action=String(body.action||""),roomId=String(body.room_id||"");
 if(action==="certificate-verify"){
  const code=String(body.code||"");if(!/^[A-Za-z0-9_-]{43}$/.test(code))return res.status(200).json({valid:false});
  const proof=await db.from("cb_seba_certificate_proofs").select("certificate_id,sealed_snapshot").eq("code_hash",hashCode(code)).maybeSingle();if(proof.error)err(500,proof.error.message);
  if(!proof.data)return res.status(200).json({valid:false});
  const active=await db.from("cb_seba_certificates").select("id").eq("id",proof.data.certificate_id).maybeSingle();if(active.error)err(500,active.error.message);
  return res.status(200).json(active.data?{valid:true,certificate:unseal(proof.data.sealed_snapshot)}:{valid:false});
 }
 const raw=req.headers.authorization,token=(Array.isArray(raw)?raw[0]:raw||"").replace(/^Bearer\s+/i,"");const auth=await db.auth.getUser(token);if(auth.error||!auth.data.user)err(401,"Sign in again.");const userId=auth.data.user!.id;
 if(action==="certificate-list"){
  const found=await db.from("cb_seba_certificates").select("id,student_id,student_name,title,coach_name,session_started_at,issued_at,rank").eq("student_id",userId).neq("student_name","").order("issued_at",{ascending:false}).limit(100);
  if(found.error)err(500,found.error.message);
  const certificates=await Promise.all((found.data||[]).map(async(row:CertificateRow)=>({...row,code:await issueProof(db,row)})));
  return res.status(200).json({certificates});
 }
 if(!uuid(roomId))err(400,"Choose a classroom.");
 const q=async(query:any)=>{const r=await query;if(r.error)err(500,r.error.message);return r.data};
 const room=await q(db.from("cb_classroom_rooms").select("id,name,teacher_id,status,created_at,expires_at").eq("id",roomId).maybeSingle());if(!room)err(404,"Classroom not found.");const teacher=room.teacher_id===userId,now=new Date(),live=room.status==="active"&&new Date(room.expires_at)>now;
 const settings=await q(db.from("cb_classroom_settings").select("cbc_enabled").eq("id",true).single());const enrollment=teacher?null:await q(db.from("cb_classroom_enrollments").select("student_id,access_expires_at").eq("room_id",roomId).eq("student_id",userId).maybeSingle());if(!teacher&&!enrollment)err(403,"Join this classroom first.");const allowed=teacher||settings?.cbc_enabled===false||new Date(enrollment.access_expires_at)>now;
 if(action==="presence"){if(!live||!allowed)err(403,"Classroom access has ended.");if(!teacher)await q(db.from("cb_seba_presence").upsert({room_id:roomId,user_id:userId,seen_at:now.toISOString()},{onConflict:"room_id,user_id"}));return res.status(200).json({ok:true})}
 const tournaments=await q(db.from("cb_seba_tournaments").select("*").eq("room_id",roomId).order("created_at",{ascending:false}).limit(8));let tournament=(tournaments||[]).find((t:any)=>t.status==="running")||tournaments?.[0]||null;
 const participants=tournament?await q(db.from("cb_seba_participants").select("user_id,student_name").eq("tournament_id",tournament.id)):[];
 const games=tournament?await q(db.from("cb_seba_games").select("*").eq("tournament_id",tournament.id).order("round")):[];
 const certificateRows=await q(db.from("cb_seba_certificates").select("*").eq("room_id",roomId).or(teacher?"id.not.is.null":`student_id.eq.${userId}`).order("issued_at",{ascending:false}));
 const certificates=action==="state"?await Promise.all(certificateRows.map(async(row:any)=>{try{return {...row,code:await issueProof(db,row)}}catch(error){if(["42P01","PGRST205"].includes(String((error as {code?:string}).code)))return {...row,code:null};throw error}})):certificateRows;
 const standings=()=>participants.map((p:any)=>{let points=0,wins=0;for(const g of games||[]){if(g.status!=="finished"||g.white_id!==p.user_id&&g.black_id!==p.user_id)continue;const own=g.white_id===p.user_id?"white":"black";if(g.result===own){points++;wins++}else if(g.result==="draw")points+=.5}return {...p,points,wins}}).sort((a:any,b:any)=>b.points-a.points||b.wins-a.wins||a.student_name.localeCompare(b.student_name)).map((p:any,i:number)=>({...p,rank:i+1}));
 if(action==="state"){if(!live&&!tournament&&!certificates?.length)err(403,"Classroom is no longer active.");if(live&&!allowed&&!tournament&&!certificates?.length)err(403,"Classroom access has ended.");const online=teacher&&live?await q(db.from("cb_seba_presence").select("user_id").eq("room_id",roomId).gte("seen_at",new Date(Date.now()-60000).toISOString())):[];const eligible=teacher&&live?await q(db.from("cb_classroom_enrollments").select("student_id,access_expires_at").eq("room_id",roomId)):[];const ids=(eligible||[]).filter((e:any)=>settings?.cbc_enabled===false||new Date(e.access_expires_at)>now).filter((e:any)=>online.some((o:any)=>o.user_id===e.student_id)).map((e:any)=>e.student_id);const pendingIds=teacher?[...new Set((certificates||[]).filter((c:any)=>!c.student_name?.trim()).map((c:any)=>c.student_id))] as string[]:[];const profileIds=[...new Set([...ids,...pendingIds])];const profiles=profileIds.length?await q(db.from("cb_profiles").select("user_id,display_name,username").in("user_id",profileIds)):[];return res.status(200).json({tournament,participants,standings:standings(),games:teacher?games:(games||[]).map((g:any)=>({...g,fen:g.white_id===userId||g.black_id===userId||g.status==="finished"?g.fen:null})),online:(profiles||[]).filter((p:any)=>ids.includes(p.user_id)).map((p:any)=>({user_id:p.user_id,name:p.display_name||p.username||"Student"})),pending_names:teacher?Object.fromEntries((profiles||[]).filter((p:any)=>pendingIds.includes(p.user_id)).map((p:any)=>[p.user_id,p.display_name||p.username||"Student"])):{},certificates,room:{name:room.name,created_at:room.created_at},teacher})}
 if(action==="certificate-name"){
   if(teacher)err(403,"Only the student can confirm their certificate name.");
   const name=String(body.student_name||"").trim().replace(/\s+/g," ");
   if(name.length<2||name.length>80||!/^\p{L}[\p{L}\p{M} .,'’\-]*$/u.test(name)||(name.match(/\p{L}/gu)?.length||0)<2)err(400,"Enter your real name (2–80 characters) and check its spelling.");
   const updated=await q(db.from("cb_seba_certificates").update({student_name:name}).eq("room_id",roomId).eq("student_id",userId).eq("student_name","").select("id"));
   if(!updated?.length)err(409,"No certificate is waiting for your name. Refresh the classroom.");
   return res.status(200).json({ok:true,updated:updated.length});
 }
 if(!live||!allowed)err(403,"Active classroom access is required.");
 if(action==="create"){if(!teacher)err(403,"Teacher only.");if(tournament?.status==="running")err(409,"Finish the current tournament first.");const online=await q(db.from("cb_seba_presence").select("user_id").eq("room_id",roomId).gte("seen_at",new Date(Date.now()-60000).toISOString()));const enrolled=await q(db.from("cb_classroom_enrollments").select("student_id,access_expires_at").eq("room_id",roomId));const ids=(enrolled||[]).filter((e:any)=>settings?.cbc_enabled===false||new Date(e.access_expires_at)>now).filter((e:any)=>online.some((o:any)=>o.user_id===e.student_id)).map((e:any)=>e.student_id);if(!ids.length)err(400,"Wait for students to open this classroom.");const minutes=Number(body.minutes),increment=Number(body.increment),rounds=Number(body.rounds),level=Number(body.ai_level);if(![3,5,10,15,30].includes(minutes)||![0,10].includes(increment)||!Number.isInteger(rounds)||rounds<1||rounds>10||!Number.isInteger(level)||level<1||level>10)err(400,"Invalid tournament settings.");const profiles=await q(db.from("cb_profiles").select("user_id,display_name,username").in("user_id",ids));const coach=await q(db.from("cb_profiles").select("display_name,username").eq("user_id",userId).maybeSingle());const inserted=await q(db.from("cb_seba_tournaments").insert({room_id:roomId,title:room.name,teacher_id:userId,coach_name:coach?.display_name||coach?.username||"Coach",session_started_at:room.created_at,time_minutes:minutes,increment_seconds:increment,total_rounds:rounds,ai_level:level}).select().single());try{await q(db.from("cb_seba_participants").insert(ids.map((id:string)=>({tournament_id:inserted.id,user_id:id,student_name:profiles.find((p:any)=>p.user_id===id)?.display_name||profiles.find((p:any)=>p.user_id===id)?.username||"Student"}))));await pair(inserted,1,ids,[])}catch(e){await db.from("cb_seba_tournaments").delete().eq("id",inserted.id);throw e}return res.status(200).json({ok:true})}
 async function pair(t:any,round:number,ids:string[],prior:any[]){const ordered=[...ids].sort((a,b)=>{const score=(id:string)=>prior.reduce((n,g)=>n+(g.status==="finished"&&(g.white_id===id||g.black_id===id)?g.result==="draw"?.5:g.result===(g.white_id===id?"white":"black")?1:0:0),0);return score(b)-score(a)||a.localeCompare(b)});const rows:any[]=[];while(ordered.length){const a=ordered.shift()!;let index=ordered.findIndex(b=>!prior.some(g=>g.white_id===a&&g.black_id===b||g.white_id===b&&g.black_id===a));if(index<0)index=0;const b=ordered.length?ordered.splice(index,1)[0]:null;const flip=(round+rows.length)%2===0;rows.push({tournament_id:t.id,round,white_id:b&&flip?b:a,black_id:b&&flip?a:b,fen:new Chess().fen(),white_ms:t.time_minutes*60000,black_ms:t.time_minutes*60000})}await q(db.from("cb_seba_games").insert(rows))}
 if(action==="next"){if(!teacher||!tournament||tournament.status!=="running")err(403,"No active tournament.");if(games.some((g:any)=>g.round===tournament.current_round&&g.status!=="finished"))err(409,"Finish all games in this round first.");if(tournament.current_round>=tournament.total_rounds)err(409,"Finish the tournament to publish rankings.");const next=tournament.current_round+1;const update=await q(db.from("cb_seba_tournaments").update({current_round:next}).eq("id",tournament.id).eq("current_round",tournament.current_round).select("id"));if(!update?.length)err(409,"Round already started. Refresh.");await pair(tournament,next,participants.map((p:any)=>p.user_id),games);return res.status(200).json({ok:true})}
 if(action==="finish"){if(!teacher||!tournament||tournament.status!=="running")err(403,"No active tournament.");if(tournament.current_round<tournament.total_rounds||games.some((g:any)=>g.status!=="finished"))err(409,"Complete every round first.");await q(db.from("cb_seba_tournaments").update({status:"finished"}).eq("id",tournament.id));return res.status(200).json({ok:true})}
 if(action==="certificate-delete"||action==="certificate-clear"){
   if(!teacher)err(403,"Teacher only.");
   const id=String(body.certificate_id||"");
   if(action==="certificate-delete"&&!uuid(id))err(400,"Choose a certificate.");
   let deleteQuery=db.from("cb_seba_certificates").delete().eq("room_id",roomId);
   if(action==="certificate-delete")deleteQuery=deleteQuery.eq("id",id);
   const removed=await q(deleteQuery.select("id,tournament_id"));
   if(action==="certificate-delete"&&!removed?.length)err(404,"Certificate not found.");
   const tournamentIds=[...new Set((removed||[]).map((c:any)=>c.tournament_id).filter(Boolean))];
   for(const tournamentId of tournamentIds){
     const left=await q(db.from("cb_seba_certificates").select("id").eq("tournament_id",tournamentId).limit(1));
     if(left?.length===0)await q(db.from("cb_seba_tournaments").update({certificates_published:false}).eq("id",tournamentId));
   }
   return res.status(200).json({ok:true,deleted:removed?.length||0});
 }
 if(action==="certificate"){if(!teacher)err(403,"Teacher only.");const rows=tournament?.status==="finished"?(standings().map((p:any)=>({room_id:roomId,tournament_id:tournament.id,student_id:p.user_id,student_name:"",title:tournament.title,coach_name:tournament.coach_name,session_started_at:tournament.session_started_at,rank:p.rank}))):await (async()=>{const enrolled=await q(db.from("cb_classroom_enrollments").select("student_id").eq("room_id",roomId));const ids=enrolled.map((e:any)=>e.student_id);if(!ids.length)return [];const coach=await q(db.from("cb_profiles").select("display_name,username").eq("user_id",userId).maybeSingle());return ids.map((id:string)=>({room_id:roomId,student_id:id,student_name:"",title:room.name,coach_name:coach?.display_name||coach?.username||"Coach",session_started_at:room.created_at}))})();if(!rows.length)err(400,"There are no students to certify.");let created=0;for(const row of rows){const saved=await db.from("cb_seba_certificates").insert(row);if(saved.error&&saved.error.code!=="23505")err(500,saved.error.message);if(!saved.error)created++}if(!created)err(409,"Certificates already exist. Delete them before generating a new set.");if(tournament?.status==="finished")await q(db.from("cb_seba_tournaments").update({certificates_published:true}).eq("id",tournament.id));return res.status(200).json({ok:true,created})}
 if(action==="move"||action==="timeout"){const id=String(body.game_id||"");const game=games.find((g:any)=>g.id===id);if(!game||game.status!=="playing"||!participants.some((p:any)=>p.user_id===userId))err(403,"Game unavailable.");const board=new Chess(game.fen),turn=board.turn()==="w"?"white":"black";if(action==="move"&&(turn==="white"?game.white_id:game.black_id)!==userId)err(403,"Wait for your turn.");if(action==="timeout"&&game.white_id!==userId&&game.black_id!==userId&&!teacher)err(403,"Not your game.");const elapsed=Math.max(0,Date.now()-new Date(game.last_move_at).getTime()),remaining=(turn==="white"?game.white_ms:game.black_ms)-elapsed;let result:string|null=null,whiteMs=game.white_ms,blackMs=game.black_ms;if(remaining<=0){result=turn==="white"?"black":"white";if(turn==="white")whiteMs=0;else blackMs=0}else{if(action==="timeout")err(409,"Clock has not expired.");const from=String(body.from||""),to=String(body.to||""),promotion=String(body.promotion||"q");if(!/^[a-h][1-8]$/.test(from)||!/^[a-h][1-8]$/.test(to)||!/^[qrbn]$/.test(promotion))err(400,"Invalid move.");try{board.move({from,to,promotion})}catch{err(400,"Illegal chess move.")}if(turn==="white")whiteMs=remaining+tournament.increment_seconds*1000;else blackMs=remaining+tournament.increment_seconds*1000;if(board.isGameOver())result=board.isCheckmate()?turn:"draw";if(!result&&!game.black_id){const move=aiMove(board,tournament.ai_level);if(move){board.move(move);if(board.isGameOver())result=board.isCheckmate()?"black":"draw"}}}const committed=await q(db.rpc("cb_seba_commit_game",{p_id:id,p_version:game.version,p_fen:board.fen(),p_white_ms:Math.round(whiteMs),p_black_ms:Math.round(blackMs),p_result:result}));if(!committed)err(409,"Board changed. Refresh and try again.");return res.status(200).json({ok:true})}
 err(400,"Unknown tournament action.");
 }catch(e){const error=e as Error&{status?:number};return res.status(error.status||500).json({error:error.message||"Tournament request failed."})}}
