/* eslint-disable @typescript-eslint/no-explicit-any */
import {createClient} from '@supabase/supabase-js';

type Req={method?:string;query?:Record<string,string|string[]|undefined>;body?:unknown;headers:Record<string,string|string[]|undefined>};
type Res={status:(code:number)=>Res;json:(body:unknown)=>void;setHeader:(name:string,value:string)=>void};
type Db=any;
class ArenaError extends Error{constructor(message:string,public status=409){super(message);}}
const fail=(status:number,message:string):never=>{throw new ArenaError(message,status);};
const db=():Db=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL??process.env.VITE_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY??'';if(!url||!key)fail(503,'Arena database configuration is unavailable.');return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});};
async function account(client:Db,req:Req){const h=req.headers.authorization,t=(Array.isArray(h)?h[0]:h??'').replace(/^Bearer\s+/i,'');if(!t)fail(401,'Please sign in again.');const a=await client.auth.getUser(t);if(a.error||!a.data.user)fail(401,'Please sign in again.');const p=await client.from('cb_profiles').select('*').eq('user_id',a.data.user.id).single();if(p.error)fail(500,p.error.message);return{id:a.data.user.id,profile:p.data};}
type ArenaSettings={slot1_start:string;slot1_end:string;slot2_start:string;slot2_end:string;entry_closes_minutes:number;prize_mode:'fixed'|'auto';fixed_prize_gold:number;auto_prize_percent:number;ticket_value_gold:number;max_pair_gap:number;fallback_wait_seconds:number;match_control:string};
const defaults:ArenaSettings={slot1_start:'19:00',slot1_end:'21:00',slot2_start:'22:00',slot2_end:'00:00',entry_closes_minutes:10,prize_mode:'fixed',fixed_prize_gold:48,auto_prize_percent:10,ticket_value_gold:28,max_pair_gap:2,fallback_wait_seconds:180,match_control:'5+0'};
const arenaControls:Record<string,{seconds:number}>={'1+0':{seconds:60},'1+1':{seconds:60},'2+1':{seconds:120},'3+0':{seconds:180},'3+2':{seconds:180},'5+0':{seconds:300},'10+0':{seconds:600},'10+5':{seconds:600},'15+10':{seconds:900}};
async function settings(client:Db):Promise<ArenaSettings>{const result=await client.from('cb_arena_settings').select('*').eq('id',true).maybeSingle();if(result.error)return defaults;return{...defaults,...result.data};}
const clockMinutes=(value:string)=>{const [h,m]=String(value).slice(0,5).split(':').map(Number);return h*60+m;};

export function arenaWindow(at=Date.now(),config:ArenaSettings=defaults){
  const manila=new Date(at+8*60*60*1000),year=manila.getUTCFullYear(),month=manila.getUTCMonth(),day=manila.getUTCDate();
  const starts=[clockMinutes(config.slot1_start),clockMinutes(config.slot2_start)],ends=[clockMinutes(config.slot1_end),clockMinutes(config.slot2_end)];
  const session=(slot:1|2,offset=0)=>{const start=starts[slot-1],end=ends[slot-1],base=Date.UTC(year,month,day+offset);return{date:new Date(base).toISOString().slice(0,10),slot,starts_at:new Date(base+(start-480)*60000).toISOString(),ends_at:new Date(base+((end<=start?end+1440:end)-480)*60000).toISOString()};};
  const today=[session(1),session(2)],current=today.find(x=>at>=Date.parse(x.starts_at)&&at<Date.parse(x.ends_at))??null;
  const next=today.find(x=>at<Date.parse(x.starts_at))??session(1,1);
  return{open:!!current,current,next,entry_open:!!current&&at<Date.parse(current.ends_at)-config.entry_closes_minutes*60000,server_now:new Date(at).toISOString(),settings:config};
}
async function ensureSession(client:Db,window:ReturnType<typeof arenaWindow>){const target=window.current??window.next,config=window.settings;const prize=config.prize_mode==='fixed'?config.fixed_prize_gold:0;const saved=await client.from('cb_arena_sessions').upsert({session_date:target.date,slot:target.slot,starts_at:target.starts_at,ends_at:target.ends_at,prize_mode:config.prize_mode,prize_gold:prize,match_control:config.match_control},{onConflict:'session_date,slot'}).select('*').single();if(saved.error)fail(/cb_arena_sessions|schema cache/i.test(saved.error.message)?503:500,/cb_arena_sessions|schema cache/i.test(saved.error.message)?'Run Grand Arena migrations through 0032, then try again.':saved.error.message);return saved.data;}
async function players(client:Db,ids:string[]){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return new Map();const r=await client.from('cb_profiles').select('user_id,username,display_name,avatar_url,cbr').in('user_id',unique);if(r.error)fail(500,r.error.message);return new Map((r.data??[]).map((p:any)=>[p.user_id,p]));}
async function pair(client:Db,session:any,userId:string){
  const mine=await client.from('cb_arena_entries').select('*').eq('session_id',session.id).eq('user_id',userId).single();if(mine.error||mine.data.status!=='waiting')return null;
  const config=await settings(client),waiting=await client.from('cb_arena_entries').select('*').eq('session_id',session.id).eq('status','waiting').neq('user_id',userId).limit(50);if(waiting.error||!waiting.data?.length)return null;
  const nearest=[...waiting.data].sort((a:any,b:any)=>Math.abs(Number(a.arena_points)-Number(mine.data.arena_points))-Math.abs(Number(b.arena_points)-Number(mine.data.arena_points))||Date.parse(a.seen_at)-Date.parse(b.seen_at))[0],gap=Math.abs(Number(nearest.arena_points)-Number(mine.data.arena_points)),waited=(Date.now()-Date.parse(mine.data.seen_at))/1000;
  if(gap>config.max_pair_gap&&waited<config.fallback_wait_seconds){const active=await client.from('cb_arena_entries').select('id',{count:'exact',head:true}).eq('session_id',session.id).eq('status','playing');if((active.count??0)>0)return null;}
  const ids=[nearest.user_id,userId].sort(),profiles=await players(client,ids),matchId=crypto.randomUUID(),stamp=new Date().toISOString(),control=arenaControls[session.match_control]?session.match_control:config.match_control,clock=(arenaControls[control]??arenaControls['5+0']).seconds*1000;
  const match=await client.from('cb_matches').insert({id:matchId,host_id:ids[0],white_id:ids[0],black_id:ids[1],invite_to:null,code:Math.random().toString(36).slice(2,10).toUpperCase(),control,status:'active',white_ms:clock,black_ms:clock,last_tick:stamp,white_cbr:Number((profiles.get(ids[0]) as any)?.cbr??88),black_cbr:Number((profiles.get(ids[1]) as any)?.cbr??88),play_mode:'arena',wager_gold:0,arena_session_id:session.id,rating_applied:false}).select('*').single();
  if(match.error)return null;
  const claimed=await client.from('cb_arena_entries').update({status:'playing',current_match_id:matchId,seen_at:stamp}).eq('session_id',session.id).in('user_id',ids).eq('status','waiting').select('user_id');
  if(claimed.error||(claimed.data??[]).length!==2){await client.from('cb_matches').delete().eq('id',matchId);await client.from('cb_arena_entries').update({status:'waiting',current_match_id:null}).eq('session_id',session.id).in('user_id',ids);return null;}
  return match.data;
}
async function state(client:Db,a:any,tryPair=true){
  await client.rpc('cb_finalize_arena_sessions');const config=await settings(client),window=arenaWindow(Date.now(),config),session=await ensureSession(client,window);
  let entry=(await client.from('cb_arena_entries').select('*').eq('session_id',session.id).eq('user_id',a.id).maybeSingle()).data??null;
  let match:any=null;if(entry?.current_match_id){match=(await client.from('cb_matches').select('*').eq('id',entry.current_match_id).maybeSingle()).data??null;if(match&&match.status==='cancelled')await client.rpc('cb_resolve_arena_cancelled_match',{p_match_id:match.id});}
  if(tryPair&&window.open&&entry?.status==='waiting'&&!match){match=await pair(client,session,a.id);entry=(await client.from('cb_arena_entries').select('*').eq('session_id',session.id).eq('user_id',a.id).maybeSingle()).data??entry;}
  const ranks=await client.from('cb_arena_entries').select('*').eq('session_id',session.id).order('arena_points',{ascending:false}).order('wins',{ascending:false}).order('joined_at',{ascending:true}).limit(25);if(ranks.error)fail(500,ranks.error.message);
  const history=await client.from('cb_arena_sessions').select('id,session_date,slot,ends_at,champion_id').not('champion_id','is',null).order('ends_at',{ascending:false}).limit(10);if(history.error)fail(500,history.error.message);
  const featured:any[]=[];for(const slot of [1,2]){const winner=(history.data??[]).find((row:any)=>Number(row.slot)===slot);if(winner)featured.push(winner);}const people=await players(client,[...(ranks.data??[]).map((r:any)=>r.user_id),...featured.map(r=>r.champion_id)]);
  const tickets=await client.from('cb_arena_tickets').select('quantity').eq('user_id',a.id).maybeSingle();if(tickets.error)fail(/cb_arena_tickets|schema cache/i.test(tickets.error.message)?503:500,/cb_arena_tickets|schema cache/i.test(tickets.error.message)?'Run supabase/0027_grand_arena.sql, then try again.':tickets.error.message);
  return{window,session,entry,match,leaderboard:(ranks.data??[]).map((r:any,i:number)=>({...r,rank:i+1,player:people.get(r.user_id)})),tickets:Number(tickets.data?.quantity??0),gold:Number(a.profile.gold_points??0),champions:featured.map(r=>({...r,player:people.get(r.champion_id)})),server_now:new Date().toISOString()};
}

export default async function handler(req:Req,res:Res){res.setHeader('Cache-Control','no-store');try{const client=db(),body=(req.body&&typeof req.body==='object'?req.body:{}) as Record<string,any>,action=String(req.method==='GET'?req.query?.action??'window':body.action??'state');if(req.method==='GET'){const config=await settings(client);return res.status(200).json(arenaWindow(Date.now(),config));}const a=await account(client,req);if(action==='owner-settings'){if(a.profile.role!=='owner')fail(403,'Owner access is required.');return res.status(200).json({settings:await settings(client)});}if(action==='save-owner-settings'){if(a.profile.role!=='owner')fail(403,'Owner access is required.');const input=body.settings??{},validTime=(x:unknown)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(String(x));if(!['slot1_start','slot1_end','slot2_start','slot2_end'].every(k=>validTime(input[k])))fail(400,'Choose valid Arena times.');const prizeMode=input.prize_mode==='auto'?'auto':'fixed',fixed=Math.round(Number(input.fixed_prize_gold)),matchControl=String(input.match_control??'');if(!Number.isFinite(fixed)||fixed<0||fixed>1000000)fail(400,'Choose a valid fixed Gold prize.');if(!arenaControls[matchControl])fail(400,'Choose a valid Arena match time control.');const saved=await client.from('cb_arena_settings').upsert({id:true,slot1_start:input.slot1_start,slot1_end:input.slot1_end,slot2_start:input.slot2_start,slot2_end:input.slot2_end,prize_mode:prizeMode,fixed_prize_gold:fixed,auto_prize_percent:10,match_control:matchControl,updated_by:a.id,updated_at:new Date().toISOString()}).select('*').single();if(saved.error)fail(500,saved.error.message);return res.status(200).json({settings:{...defaults,...saved.data}});}if(action==='state')return res.status(200).json(await state(client,a,body.pair!==false));if(action==='buy'){const quantity=Number(body.quantity),requestId=String(body.request_id??'');if(![1,3,5].includes(quantity)||!/^[a-f0-9-]{36}$/i.test(requestId))fail(400,'Choose a valid Arena Ticket package.');const bought=await client.rpc('cb_buy_arena_tickets',{p_user_id:a.id,p_quantity:quantity,p_request_id:requestId});if(bought.error)fail(409,bought.error.message);return res.status(200).json(await state(client,{...a,profile:{...a.profile,gold_points:bought.data?.gold}},false));}if(action==='enter'){const config=await settings(client),window=arenaWindow(Date.now(),config);if(!window.current||!window.entry_open)fail(409,'Arena entry is currently closed.');const session=await ensureSession(client,window),entered=await client.rpc('cb_enter_grand_arena',{p_user_id:a.id,p_session_id:session.id});if(entered.error)fail(409,entered.error.message);return res.status(200).json(await state(client,a));}fail(404,'Unknown Arena request.');}catch(error){const e=error as ArenaError;return res.status(e.status??500).json({error:e.message||'Grand Arena is temporarily unavailable.'});}}
